import { Dish } from '@/types'

const FIXED_TIMESTAMP = 1700000000000

export const BBQ_DISHES: Dish[] = [
  {
    id: 'demo-bq1',
    name: '羊肉串',
    tags: ['cuisine-bbq', 'taste-salty', 'taste-fragrant', 'taste-mild-spicy', 'type-snack', 'price-moderate', 'time-normal', 'period-dinner', 'period-midnight', 'temp-hot', 'season-summer'],
    stats: { pickCount: 0, rejectCount: 0 },
    createdAt: FIXED_TIMESTAMP,
  },
  {
    id: 'demo-bq2',
    name: '烤鱼',
    tags: ['cuisine-bbq', 'taste-medium-spicy', 'taste-fragrant', 'taste-umami', 'type-hot', 'price-premium', 'time-slow', 'period-dinner', 'period-midnight', 'temp-hot', 'season-all'],
    stats: { pickCount: 0, rejectCount: 0 },
    createdAt: FIXED_TIMESTAMP,
  },
  {
    id: 'demo-bq3',
    name: '烤翅',
    tags: ['cuisine-bbq', 'taste-salty', 'taste-fragrant', 'taste-crispy', 'type-snack', 'price-moderate', 'time-normal', 'period-dinner', 'period-midnight', 'temp-hot', 'season-all'],
    stats: { pickCount: 0, rejectCount: 0 },
    createdAt: FIXED_TIMESTAMP,
  },
  {
    id: 'demo-bq4',
    name: '生蚝',
    tags: ['cuisine-bbq', 'taste-umami', 'taste-fresh', 'taste-fragrant', 'type-snack', 'price-moderate', 'time-normal', 'period-dinner', 'period-midnight', 'temp-hot', 'season-summer'],
    stats: { pickCount: 0, rejectCount: 0 },
    createdAt: FIXED_TIMESTAMP,
  },
  {
    id: 'demo-bq5',
    name: '烤茄子',
    tags: ['cuisine-bbq', 'taste-salty', 'taste-fragrant', 'taste-soft', 'type-snack', 'price-budget', 'time-normal', 'period-dinner', 'period-midnight', 'temp-hot', 'season-summer'],
    stats: { pickCount: 0, rejectCount: 0 },
    createdAt: FIXED_TIMESTAMP,
  },
  {
    id: 'demo-bq6',
    name: '烤面筋',
    tags: ['cuisine-bbq', 'taste-mild-spicy', 'taste-salty', 'taste-chewy', 'type-snack', 'price-budget', 'time-fast', 'period-snack', 'period-midnight', 'temp-hot', 'season-all'],
    stats: { pickCount: 0, rejectCount: 0 },
    createdAt: FIXED_TIMESTAMP,
  },
  {
    id: 'demo-bq7',
    name: '烤韭菜',
    tags: ['cuisine-bbq', 'taste-salty', 'taste-fragrant', 'type-snack', 'price-budget', 'time-fast', 'period-dinner', 'period-midnight', 'temp-hot', 'season-spring'],
    stats: { pickCount: 0, rejectCount: 0 },
    createdAt: FIXED_TIMESTAMP,
  },
  {
    id: 'demo-bq8',
    name: '锡纸花甲',
    tags: ['cuisine-bbq', 'taste-mild-spicy', 'taste-umami', 'taste-fragrant', 'type-snack', 'price-moderate', 'time-normal', 'period-dinner', 'period-midnight', 'temp-hot', 'season-summer'],
    stats: { pickCount: 0, rejectCount: 0 },
    createdAt: FIXED_TIMESTAMP,
  },
  {
    id: 'demo-bq9',
    name: '烤全羊',
    tags: ['cuisine-bbq', 'taste-salty', 'taste-fragrant', 'taste-heavy', 'type-hot', 'price-luxury', 'time-slow', 'period-dinner', 'temp-hot', 'season-autumn'],
    stats: { pickCount: 0, rejectCount: 0 },
    createdAt: FIXED_TIMESTAMP,
  },
  {
    id: 'demo-bq10',
    name: '烤猪蹄',
    tags: ['cuisine-bbq', 'taste-salty', 'taste-fragrant', 'taste-crispy', 'type-snack', 'price-moderate', 'time-normal', 'period-dinner', 'period-midnight', 'temp-hot', 'season-all'],
    stats: { pickCount: 0, rejectCount: 0 },
    createdAt: FIXED_TIMESTAMP,
  },
  {
    id: 'demo-bq11',
    name: '烤牛肉串',
    tags: ['cuisine-bbq', 'taste-salty', 'taste-fragrant', 'taste-tender', 'type-snack', 'price-moderate', 'time-normal', 'period-dinner', 'period-midnight', 'temp-hot', 'season-all'],
    stats: { pickCount: 0, rejectCount: 0 },
    createdAt: FIXED_TIMESTAMP,
  },
  {
    id: 'demo-bq12',
    name: '烤鸡翅',
    tags: ['cuisine-bbq', 'taste-salty', 'taste-fragrant', 'taste-crispy', 'type-snack', 'price-budget', 'time-normal', 'period-dinner', 'period-midnight', 'temp-hot', 'season-all'],
    stats: { pickCount: 0, rejectCount: 0 },
    createdAt: FIXED_TIMESTAMP,
  },
  {
    id: 'demo-bq13',
    name: '烤玉米',
    tags: ['cuisine-bbq', 'taste-sweet', 'taste-fragrant', 'type-snack', 'price-budget', 'time-fast', 'period-snack', 'period-midnight', 'temp-hot', 'season-summer'],
    stats: { pickCount: 0, rejectCount: 0 },
    createdAt: FIXED_TIMESTAMP,
  },
  {
    id: 'demo-bq14',
    name: '烤排骨',
    tags: ['cuisine-bbq', 'taste-salty', 'taste-fragrant', 'taste-heavy', 'type-hot', 'price-premium', 'time-slow', 'period-dinner', 'period-midnight', 'temp-hot', 'season-all'],
    stats: { pickCount: 0, rejectCount: 0 },
    createdAt: FIXED_TIMESTAMP,
  },
  {
    id: 'demo-bq15',
    name: '烤鸡心',
    tags: ['cuisine-bbq', 'taste-salty', 'taste-fragrant', 'taste-chewy', 'type-snack', 'price-budget', 'time-normal', 'period-dinner', 'period-midnight', 'temp-hot', 'season-all'],
    stats: { pickCount: 0, rejectCount: 0 },
    createdAt: FIXED_TIMESTAMP,
  },
  {
    id: 'demo-bq16',
    name: '烤豆腐',
    tags: ['cuisine-bbq', 'taste-mild-spicy', 'taste-fragrant', 'taste-soft', 'type-snack', 'price-budget', 'time-fast', 'period-dinner', 'period-midnight', 'temp-hot', 'season-all'],
    stats: { pickCount: 0, rejectCount: 0 },
    createdAt: FIXED_TIMESTAMP,
  },
  {
    id: 'demo-bq17',
    name: '烤金针菇',
    tags: ['cuisine-bbq', 'taste-salty', 'taste-fragrant', 'taste-tender', 'type-snack', 'price-budget', 'time-fast', 'period-dinner', 'period-midnight', 'temp-hot', 'season-all'],
    stats: { pickCount: 0, rejectCount: 0 },
    createdAt: FIXED_TIMESTAMP,
  },
  {
    id: 'demo-bq18',
    name: '烤五花肉',
    tags: ['cuisine-bbq', 'taste-salty', 'taste-fragrant', 'taste-crispy', 'type-snack', 'price-moderate', 'time-normal', 'period-dinner', 'period-midnight', 'temp-hot', 'season-all'],
    stats: { pickCount: 0, rejectCount: 0 },
    createdAt: FIXED_TIMESTAMP,
  },
  {
    id: 'demo-bq19',
    name: '锡纸烤脑花',
    tags: ['cuisine-bbq', 'taste-mild-spicy', 'taste-fragrant', 'taste-soft', 'type-snack', 'price-moderate', 'time-normal', 'period-dinner', 'period-midnight', 'temp-hot', 'season-all'],
    stats: { pickCount: 0, rejectCount: 0 },
    createdAt: FIXED_TIMESTAMP,
  },
  {
    id: 'demo-bq20',
    name: '铁板鱿鱼',
    tags: ['cuisine-bbq', 'taste-mild-spicy', 'taste-fragrant', 'taste-chewy', 'type-snack', 'price-budget', 'time-fast', 'period-snack', 'period-midnight', 'temp-hot', 'season-all'],
    stats: { pickCount: 0, rejectCount: 0 },
    createdAt: FIXED_TIMESTAMP,
  },
  {
    id: 'demo-bq21',
    name: '烤冷面',
    tags: ['cuisine-bbq', 'taste-sour-sweet', 'taste-mild-spicy', 'taste-chewy', 'type-snack', 'price-budget', 'time-fast', 'period-snack', 'period-midnight', 'temp-hot', 'season-all'],
    stats: { pickCount: 0, rejectCount: 0 },
    createdAt: FIXED_TIMESTAMP,
  },
  {
    id: 'demo-bq22',
    name: '烤生蚝',
    tags: ['cuisine-bbq', 'taste-umami', 'taste-fragrant', 'taste-fresh', 'type-snack', 'price-moderate', 'time-normal', 'period-dinner', 'period-midnight', 'temp-hot', 'season-summer'],
    stats: { pickCount: 0, rejectCount: 0 },
    createdAt: FIXED_TIMESTAMP,
  },
  {
    id: 'demo-bq23',
    name: '烤扇贝',
    tags: ['cuisine-bbq', 'taste-umami', 'taste-fragrant', 'taste-fresh', 'type-snack', 'price-moderate', 'time-normal', 'period-dinner', 'period-midnight', 'temp-hot', 'season-summer'],
    stats: { pickCount: 0, rejectCount: 0 },
    createdAt: FIXED_TIMESTAMP,
  },
  {
    id: 'demo-bq24',
    name: '羊腿',
    tags: ['cuisine-bbq', 'taste-salty', 'taste-fragrant', 'taste-heavy', 'type-hot', 'price-premium', 'time-slow', 'period-dinner', 'temp-hot', 'season-autumn'],
    stats: { pickCount: 0, rejectCount: 0 },
    createdAt: FIXED_TIMESTAMP,
  },
  {
    id: 'demo-bq25',
    name: '烤乳鸽',
    tags: ['cuisine-bbq', 'taste-crispy', 'taste-fragrant', 'taste-umami', 'type-hot', 'price-premium', 'time-slow', 'period-dinner', 'temp-hot', 'season-all'],
    stats: { pickCount: 0, rejectCount: 0 },
    createdAt: FIXED_TIMESTAMP,
  },
]
