import { Dish } from '@/types'

const FIXED_TIMESTAMP = 1700000000000

export const CANTONESE_DISHES: Dish[] = [
  {
    id: 'demo-c1',
    name: '清蒸鲈鱼',
    tags: ['cuisine-cantonese', 'taste-light', 'taste-umami', 'taste-fresh', 'type-hot', 'price-premium', 'time-slow', 'period-dinner', 'temp-hot', 'season-all'],
    stats: { pickCount: 0, rejectCount: 0 },
    createdAt: FIXED_TIMESTAMP,
  },
  {
    id: 'demo-c2',
    name: '虾饺',
    tags: ['cuisine-cantonese', 'taste-light', 'taste-umami', 'taste-tender', 'type-dimsum', 'price-moderate', 'time-normal', 'period-breakfast', 'period-snack', 'temp-hot', 'season-all'],
    stats: { pickCount: 0, rejectCount: 0 },
    createdAt: FIXED_TIMESTAMP,
  },
  {
    id: 'demo-c3',
    name: '白切鸡',
    tags: ['cuisine-cantonese', 'taste-light', 'taste-umami', 'taste-tender', 'type-hot', 'price-moderate', 'time-normal', 'period-lunch', 'period-dinner', 'temp-hot', 'season-summer'],
    stats: { pickCount: 0, rejectCount: 0 },
    createdAt: FIXED_TIMESTAMP,
  },
  {
    id: 'demo-c4',
    name: '肠粉',
    tags: ['cuisine-cantonese', 'taste-light', 'taste-umami', 'taste-soft', 'type-dimsum', 'price-budget', 'time-fast', 'period-breakfast', 'temp-hot', 'season-all'],
    stats: { pickCount: 0, rejectCount: 0 },
    createdAt: FIXED_TIMESTAMP,
  },
  {
    id: 'demo-c5',
    name: '叉烧',
    tags: ['cuisine-cantonese', 'taste-sweet', 'taste-fragrant', 'taste-tender', 'type-hot', 'price-moderate', 'time-normal', 'period-lunch', 'period-dinner', 'temp-hot', 'season-all'],
    stats: { pickCount: 0, rejectCount: 0 },
    createdAt: FIXED_TIMESTAMP,
  },
  {
    id: 'demo-c6',
    name: '烧鹅',
    tags: ['cuisine-cantonese', 'taste-salty', 'taste-crispy', 'taste-fragrant', 'type-hot', 'price-premium', 'time-slow', 'period-dinner', 'temp-hot', 'season-all'],
    stats: { pickCount: 0, rejectCount: 0 },
    createdAt: FIXED_TIMESTAMP,
  },
  {
    id: 'demo-c7',
    name: '煲仔饭',
    tags: ['cuisine-cantonese', 'taste-salty', 'taste-fragrant', 'taste-crispy', 'type-rice', 'price-moderate', 'time-slow', 'period-lunch', 'period-dinner', 'temp-hot', 'season-winter'],
    stats: { pickCount: 0, rejectCount: 0 },
    createdAt: FIXED_TIMESTAMP,
  },
  {
    id: 'demo-c8',
    name: '干炒牛河',
    tags: ['cuisine-cantonese', 'taste-salty', 'taste-fragrant', 'taste-chewy', 'type-noodles', 'price-moderate', 'time-normal', 'period-lunch', 'period-dinner', 'temp-hot', 'season-all'],
    stats: { pickCount: 0, rejectCount: 0 },
    createdAt: FIXED_TIMESTAMP,
  },
  {
    id: 'demo-c9',
    name: '艇仔粥',
    tags: ['cuisine-cantonese', 'taste-light', 'taste-umami', 'taste-fresh', 'type-soup', 'price-budget', 'time-fast', 'period-breakfast', 'period-snack', 'temp-hot', 'season-winter'],
    stats: { pickCount: 0, rejectCount: 0 },
    createdAt: FIXED_TIMESTAMP,
  },
  {
    id: 'demo-c10',
    name: '双皮奶',
    tags: ['cuisine-cantonese', 'taste-sweet', 'taste-soft', 'taste-fresh', 'type-dessert', 'price-budget', 'time-fast', 'period-snack', 'temp-cold', 'season-summer'],
    stats: { pickCount: 0, rejectCount: 0 },
    createdAt: FIXED_TIMESTAMP,
  },
  {
    id: 'demo-c11',
    name: '白灼虾',
    tags: ['cuisine-cantonese', 'taste-light', 'taste-umami', 'taste-fresh', 'type-hot', 'price-premium', 'time-fast', 'period-lunch', 'period-dinner', 'temp-hot', 'season-all'],
    stats: { pickCount: 0, rejectCount: 0 },
    createdAt: FIXED_TIMESTAMP,
  },
  {
    id: 'demo-c12',
    name: '糯米鸡',
    tags: ['cuisine-cantonese', 'taste-salty', 'taste-fragrant', 'taste-soft', 'type-dimsum', 'price-budget', 'time-normal', 'period-breakfast', 'period-snack', 'temp-hot', 'season-all'],
    stats: { pickCount: 0, rejectCount: 0 },
    createdAt: FIXED_TIMESTAMP,
  },
  {
    id: 'demo-c13',
    name: '萝卜牛腩',
    tags: ['cuisine-cantonese', 'taste-salty', 'taste-umami', 'taste-tender', 'type-hot', 'price-moderate', 'time-slow', 'period-lunch', 'period-dinner', 'temp-hot', 'season-winter'],
    stats: { pickCount: 0, rejectCount: 0 },
    createdAt: FIXED_TIMESTAMP,
  },
  {
    id: 'demo-c14',
    name: '老火靓汤',
    tags: ['cuisine-cantonese', 'taste-light', 'taste-umami', 'taste-fresh', 'type-soup', 'price-moderate', 'time-slow', 'period-lunch', 'period-dinner', 'temp-hot', 'season-all'],
    stats: { pickCount: 0, rejectCount: 0 },
    createdAt: FIXED_TIMESTAMP,
  },
  {
    id: 'demo-c15',
    name: '蛋挞',
    tags: ['cuisine-cantonese', 'taste-sweet', 'taste-crispy', 'taste-soft', 'type-dimsum', 'price-budget', 'time-fast', 'period-breakfast', 'period-snack', 'temp-hot', 'season-all'],
    stats: { pickCount: 0, rejectCount: 0 },
    createdAt: FIXED_TIMESTAMP,
  },
  {
    id: 'demo-c16',
    name: '豉汁蒸排骨',
    tags: ['cuisine-cantonese', 'taste-salty', 'taste-umami', 'taste-tender', 'type-dimsum', 'price-moderate', 'time-normal', 'period-breakfast', 'period-lunch', 'temp-hot', 'season-all'],
    stats: { pickCount: 0, rejectCount: 0 },
    createdAt: FIXED_TIMESTAMP,
  },
  {
    id: 'demo-c17',
    name: '凤爪',
    tags: ['cuisine-cantonese', 'taste-salty', 'taste-umami', 'taste-soft', 'type-dimsum', 'price-budget', 'time-normal', 'period-breakfast', 'period-snack', 'temp-hot', 'season-all'],
    stats: { pickCount: 0, rejectCount: 0 },
    createdAt: FIXED_TIMESTAMP,
  },
  {
    id: 'demo-c18',
    name: '蒸凤爪',
    tags: ['cuisine-cantonese', 'taste-salty', 'taste-umami', 'taste-soft', 'type-dimsum', 'price-budget', 'time-normal', 'period-breakfast', 'period-snack', 'temp-hot', 'season-all'],
    stats: { pickCount: 0, rejectCount: 0 },
    createdAt: FIXED_TIMESTAMP,
  },
  {
    id: 'demo-c19',
    name: '菠萝咕噜肉',
    tags: ['cuisine-cantonese', 'taste-sour-sweet', 'taste-crispy', 'taste-tender', 'type-hot', 'price-moderate', 'time-normal', 'period-lunch', 'period-dinner', 'temp-hot', 'season-all'],
    stats: { pickCount: 0, rejectCount: 0 },
    createdAt: FIXED_TIMESTAMP,
  },
  {
    id: 'demo-c20',
    name: '腊味煲仔饭',
    tags: ['cuisine-cantonese', 'taste-salty', 'taste-fragrant', 'taste-crispy', 'type-rice', 'price-moderate', 'time-slow', 'period-lunch', 'period-dinner', 'temp-hot', 'season-winter'],
    stats: { pickCount: 0, rejectCount: 0 },
    createdAt: FIXED_TIMESTAMP,
  },
  {
    id: 'demo-c21',
    name: '竹升面',
    tags: ['cuisine-cantonese', 'taste-light', 'taste-chewy', 'taste-umami', 'type-noodles', 'price-budget', 'time-fast', 'period-lunch', 'period-dinner', 'temp-hot', 'season-all'],
    stats: { pickCount: 0, rejectCount: 0 },
    createdAt: FIXED_TIMESTAMP,
  },
  {
    id: 'demo-c22',
    name: '云吞面',
    tags: ['cuisine-cantonese', 'taste-light', 'taste-umami', 'taste-slurpy', 'type-noodles', 'price-budget', 'time-fast', 'period-lunch', 'period-dinner', 'temp-hot', 'season-all'],
    stats: { pickCount: 0, rejectCount: 0 },
    createdAt: FIXED_TIMESTAMP,
  },
  {
    id: 'demo-c23',
    name: '鲜虾云吞',
    tags: ['cuisine-cantonese', 'taste-light', 'taste-umami', 'taste-fresh', 'type-dimsum', 'price-moderate', 'time-normal', 'period-lunch', 'period-dinner', 'temp-hot', 'season-all'],
    stats: { pickCount: 0, rejectCount: 0 },
    createdAt: FIXED_TIMESTAMP,
  },
  {
    id: 'demo-c24',
    name: '蜜汁叉烧',
    tags: ['cuisine-cantonese', 'taste-sweet', 'taste-fragrant', 'taste-tender', 'type-hot', 'price-premium', 'time-slow', 'period-dinner', 'temp-hot', 'season-all'],
    stats: { pickCount: 0, rejectCount: 0 },
    createdAt: FIXED_TIMESTAMP,
  },
  {
    id: 'demo-c25',
    name: '脆皮烧肉',
    tags: ['cuisine-cantonese', 'taste-salty', 'taste-crispy', 'taste-fragrant', 'type-hot', 'price-premium', 'time-slow', 'period-lunch', 'period-dinner', 'temp-hot', 'season-all'],
    stats: { pickCount: 0, rejectCount: 0 },
    createdAt: FIXED_TIMESTAMP,
  },
  {
    id: 'demo-c26',
    name: '梅菜扣肉',
    tags: ['cuisine-cantonese', 'taste-salty', 'taste-tender', 'taste-heavy', 'type-hot', 'price-moderate', 'time-slow', 'period-lunch', 'period-dinner', 'temp-hot', 'season-winter'],
    stats: { pickCount: 0, rejectCount: 0 },
    createdAt: FIXED_TIMESTAMP,
  },
  {
    id: 'demo-c27',
    name: '盐焗鸡',
    tags: ['cuisine-cantonese', 'taste-salty', 'taste-fragrant', 'taste-tender', 'type-hot', 'price-moderate', 'time-slow', 'period-lunch', 'period-dinner', 'temp-hot', 'season-all'],
    stats: { pickCount: 0, rejectCount: 0 },
    createdAt: FIXED_TIMESTAMP,
  },
  {
    id: 'demo-c28',
    name: '清汤牛腩',
    tags: ['cuisine-cantonese', 'taste-light', 'taste-umami', 'taste-tender', 'type-soup', 'price-moderate', 'time-slow', 'period-lunch', 'period-dinner', 'temp-hot', 'season-winter'],
    stats: { pickCount: 0, rejectCount: 0 },
    createdAt: FIXED_TIMESTAMP,
  },
  {
    id: 'demo-c29',
    name: '沙姜鸡',
    tags: ['cuisine-cantonese', 'taste-fragrant', 'taste-light', 'taste-tender', 'type-hot', 'price-moderate', 'time-normal', 'period-lunch', 'period-dinner', 'temp-hot', 'season-all'],
    stats: { pickCount: 0, rejectCount: 0 },
    createdAt: FIXED_TIMESTAMP,
  },
  {
    id: 'demo-c30',
    name: '豉汁炒蛤',
    tags: ['cuisine-cantonese', 'taste-salty', 'taste-umami', 'taste-fresh', 'type-hot', 'price-moderate', 'time-fast', 'period-dinner', 'period-midnight', 'temp-hot', 'season-summer'],
    stats: { pickCount: 0, rejectCount: 0 },
    createdAt: FIXED_TIMESTAMP,
  },
  {
    id: 'demo-c31',
    name: '椰汁马蹄糕',
    tags: ['cuisine-cantonese', 'taste-sweet', 'taste-soft', 'taste-fresh', 'type-dessert', 'price-budget', 'time-normal', 'period-snack', 'temp-cold', 'season-summer'],
    stats: { pickCount: 0, rejectCount: 0 },
    createdAt: FIXED_TIMESTAMP,
  },
  {
    id: 'demo-c32',
    name: '流沙包',
    tags: ['cuisine-cantonese', 'taste-sweet', 'taste-soft', 'taste-fragrant', 'type-dimsum', 'price-budget', 'time-normal', 'period-breakfast', 'period-snack', 'temp-hot', 'season-all'],
    stats: { pickCount: 0, rejectCount: 0 },
    createdAt: FIXED_TIMESTAMP,
  },
  {
    id: 'demo-c33',
    name: '榴莲酥',
    tags: ['cuisine-cantonese', 'taste-sweet', 'taste-crispy', 'taste-fragrant', 'type-dimsum', 'price-moderate', 'time-normal', 'period-snack', 'temp-hot', 'season-all'],
    stats: { pickCount: 0, rejectCount: 0 },
    createdAt: FIXED_TIMESTAMP,
  },
  {
    id: 'demo-c34',
    name: '莲蓉包',
    tags: ['cuisine-cantonese', 'taste-sweet', 'taste-soft', 'taste-fragrant', 'type-dimsum', 'price-budget', 'time-normal', 'period-breakfast', 'period-snack', 'temp-hot', 'season-all'],
    stats: { pickCount: 0, rejectCount: 0 },
    createdAt: FIXED_TIMESTAMP,
  },
  {
    id: 'demo-c35',
    name: '烧卖',
    tags: ['cuisine-cantonese', 'taste-salty', 'taste-umami', 'taste-tender', 'type-dimsum', 'price-budget', 'time-normal', 'period-breakfast', 'period-snack', 'temp-hot', 'season-all'],
    stats: { pickCount: 0, rejectCount: 0 },
    createdAt: FIXED_TIMESTAMP,
  },
  {
    id: 'demo-c36',
    name: '叉烧包',
    tags: ['cuisine-cantonese', 'taste-sweet', 'taste-salty', 'taste-soft', 'type-dimsum', 'price-budget', 'time-normal', 'period-breakfast', 'period-snack', 'temp-hot', 'season-all'],
    stats: { pickCount: 0, rejectCount: 0 },
    createdAt: FIXED_TIMESTAMP,
  },
  {
    id: 'demo-c37',
    name: '粉果',
    tags: ['cuisine-cantonese', 'taste-light', 'taste-umami', 'taste-chewy', 'type-dimsum', 'price-budget', 'time-normal', 'period-breakfast', 'period-snack', 'temp-hot', 'season-all'],
    stats: { pickCount: 0, rejectCount: 0 },
    createdAt: FIXED_TIMESTAMP,
  },
  {
    id: 'demo-c38',
    name: '姜撞奶',
    tags: ['cuisine-cantonese', 'taste-sweet', 'taste-soft', 'taste-fragrant', 'type-dessert', 'price-budget', 'time-fast', 'period-snack', 'temp-hot', 'season-winter'],
    stats: { pickCount: 0, rejectCount: 0 },
    createdAt: FIXED_TIMESTAMP,
  },
  {
    id: 'demo-c39',
    name: '龟苓膏',
    tags: ['cuisine-cantonese', 'taste-light', 'taste-sweet', 'taste-soft', 'type-dessert', 'price-budget', 'time-fast', 'period-snack', 'temp-cold', 'season-summer'],
    stats: { pickCount: 0, rejectCount: 0 },
    createdAt: FIXED_TIMESTAMP,
  },
  {
    id: 'demo-c40',
    name: '煎堆',
    tags: ['cuisine-cantonese', 'taste-sweet', 'taste-crispy', 'taste-chewy', 'type-dimsum', 'price-budget', 'time-normal', 'period-snack', 'temp-hot', 'season-all'],
    stats: { pickCount: 0, rejectCount: 0 },
    createdAt: FIXED_TIMESTAMP,
  },
  {
    id: 'demo-c41',
    name: '牛肉球',
    tags: ['cuisine-cantonese', 'taste-salty', 'taste-umami', 'taste-chewy', 'type-dimsum', 'price-budget', 'time-normal', 'period-breakfast', 'period-snack', 'temp-hot', 'season-all'],
    stats: { pickCount: 0, rejectCount: 0 },
    createdAt: FIXED_TIMESTAMP,
  },
  {
    id: 'demo-c42',
    name: '蒸排骨',
    tags: ['cuisine-cantonese', 'taste-salty', 'taste-umami', 'taste-tender', 'type-dimsum', 'price-moderate', 'time-normal', 'period-breakfast', 'period-lunch', 'temp-hot', 'season-all'],
    stats: { pickCount: 0, rejectCount: 0 },
    createdAt: FIXED_TIMESTAMP,
  },
  {
    id: 'demo-c43',
    name: '白粥配油条',
    tags: ['cuisine-cantonese', 'taste-light', 'taste-crispy', 'taste-soft', 'type-staple', 'price-budget', 'time-fast', 'period-breakfast', 'temp-hot', 'season-all'],
    stats: { pickCount: 0, rejectCount: 0 },
    createdAt: FIXED_TIMESTAMP,
  },
  {
    id: 'demo-c44',
    name: '潮州粉粿',
    tags: ['cuisine-cantonese', 'taste-light', 'taste-umami', 'taste-chewy', 'type-dimsum', 'price-budget', 'time-normal', 'period-breakfast', 'period-snack', 'temp-hot', 'season-all'],
    stats: { pickCount: 0, rejectCount: 0 },
    createdAt: FIXED_TIMESTAMP,
  },
  {
    id: 'demo-c45',
    name: '广式月饼',
    tags: ['cuisine-cantonese', 'taste-sweet', 'taste-soft', 'taste-fragrant', 'type-dessert', 'price-moderate', 'time-normal', 'period-snack', 'temp-room', 'season-autumn'],
    stats: { pickCount: 0, rejectCount: 0 },
    createdAt: FIXED_TIMESTAMP,
  },
]
