import { Dish } from '@/types'

const FIXED_TIMESTAMP = 1700000000000

export const CHINESE_DISHES: Dish[] = [
  {
    id: 'demo-ch1',
    name: '糖醋里脊',
    tags: ['cuisine-chinese', 'taste-sour-sweet', 'taste-crispy', 'taste-tender', 'type-hot', 'price-moderate', 'time-normal', 'period-lunch', 'period-dinner', 'temp-hot', 'season-all'],
    stats: { pickCount: 0, rejectCount: 0 },
    createdAt: FIXED_TIMESTAMP,
  },
  {
    id: 'demo-ch2',
    name: '黄焖鸡米饭',
    tags: ['cuisine-chinese', 'taste-salty', 'taste-tender', 'taste-heavy', 'type-rice', 'price-moderate', 'time-normal', 'period-lunch', 'period-dinner', 'temp-hot', 'season-all'],
    stats: { pickCount: 0, rejectCount: 0 },
    createdAt: FIXED_TIMESTAMP,
  },
  {
    id: 'demo-ch3',
    name: '红烧肉',
    tags: ['cuisine-chinese', 'taste-salty', 'taste-sweet', 'taste-tender', 'taste-heavy', 'type-hot', 'price-moderate', 'time-slow', 'period-dinner', 'temp-hot', 'season-winter'],
    stats: { pickCount: 0, rejectCount: 0 },
    createdAt: FIXED_TIMESTAMP,
  },
  {
    id: 'demo-ch4',
    name: '番茄炒蛋',
    tags: ['cuisine-chinese', 'taste-sour-sweet', 'taste-light', 'taste-soft', 'type-hot', 'price-budget', 'time-fast', 'period-lunch', 'period-dinner', 'temp-hot', 'season-all'],
    stats: { pickCount: 0, rejectCount: 0 },
    createdAt: FIXED_TIMESTAMP,
  },
  {
    id: 'demo-ch5',
    name: '青椒肉丝',
    tags: ['cuisine-chinese', 'taste-light', 'taste-fresh', 'taste-tender', 'type-hot', 'price-budget', 'time-fast', 'period-lunch', 'period-dinner', 'temp-hot', 'season-all'],
    stats: { pickCount: 0, rejectCount: 0 },
    createdAt: FIXED_TIMESTAMP,
  },
  {
    id: 'demo-ch6',
    name: '土豆丝',
    tags: ['cuisine-chinese', 'taste-light', 'taste-crispy', 'type-hot', 'price-budget', 'time-fast', 'period-lunch', 'period-dinner', 'temp-hot', 'season-all'],
    stats: { pickCount: 0, rejectCount: 0 },
    createdAt: FIXED_TIMESTAMP,
  },
  {
    id: 'demo-ch7',
    name: '地三鲜',
    tags: ['cuisine-chinese', 'taste-salty', 'taste-soft', 'taste-fragrant', 'type-hot', 'price-budget', 'time-normal', 'period-lunch', 'period-dinner', 'temp-hot', 'season-all'],
    stats: { pickCount: 0, rejectCount: 0 },
    createdAt: FIXED_TIMESTAMP,
  },
  {
    id: 'demo-ch8',
    name: '木须肉',
    tags: ['cuisine-chinese', 'taste-light', 'taste-umami', 'taste-tender', 'type-hot', 'price-budget', 'time-fast', 'period-lunch', 'period-dinner', 'temp-hot', 'season-all'],
    stats: { pickCount: 0, rejectCount: 0 },
    createdAt: FIXED_TIMESTAMP,
  },
  {
    id: 'demo-ch9',
    name: '酸菜鱼',
    tags: ['cuisine-chinese', 'taste-sour', 'taste-mild-spicy', 'taste-tender', 'type-hot', 'price-moderate', 'time-normal', 'period-lunch', 'period-dinner', 'temp-hot', 'season-winter'],
    stats: { pickCount: 0, rejectCount: 0 },
    createdAt: FIXED_TIMESTAMP,
  },
  {
    id: 'demo-ch10',
    name: '京酱肉丝',
    tags: ['cuisine-chinese', 'taste-salty', 'taste-sweet', 'taste-tender', 'type-hot', 'price-moderate', 'time-normal', 'period-lunch', 'period-dinner', 'temp-hot', 'season-all'],
    stats: { pickCount: 0, rejectCount: 0 },
    createdAt: FIXED_TIMESTAMP,
  },
  {
    id: 'demo-ch11',
    name: '可乐鸡翅',
    tags: ['cuisine-chinese', 'taste-sweet', 'taste-salty', 'taste-tender', 'type-hot', 'price-moderate', 'time-normal', 'period-lunch', 'period-dinner', 'temp-hot', 'season-all'],
    stats: { pickCount: 0, rejectCount: 0 },
    createdAt: FIXED_TIMESTAMP,
  },
  {
    id: 'demo-ch12',
    name: '蚂蚁上树',
    tags: ['cuisine-chinese', 'taste-mild-spicy', 'taste-salty', 'taste-slurpy', 'type-hot', 'price-budget', 'time-fast', 'period-lunch', 'period-dinner', 'temp-hot', 'season-all'],
    stats: { pickCount: 0, rejectCount: 0 },
    createdAt: FIXED_TIMESTAMP,
  },
  {
    id: 'demo-ch13',
    name: '蒜蓉粉丝蒸虾',
    tags: ['cuisine-chinese', 'taste-light', 'taste-umami', 'taste-fragrant', 'type-hot', 'price-premium', 'time-normal', 'period-dinner', 'temp-hot', 'season-all'],
    stats: { pickCount: 0, rejectCount: 0 },
    createdAt: FIXED_TIMESTAMP,
  },
  {
    id: 'demo-ch14',
    name: '红烧排骨',
    tags: ['cuisine-chinese', 'taste-salty', 'taste-sweet', 'taste-tender', 'taste-heavy', 'type-hot', 'price-moderate', 'time-slow', 'period-dinner', 'temp-hot', 'season-all'],
    stats: { pickCount: 0, rejectCount: 0 },
    createdAt: FIXED_TIMESTAMP,
  },
  {
    id: 'demo-ch15',
    name: '糖醋排骨',
    tags: ['cuisine-chinese', 'taste-sour-sweet', 'taste-crispy', 'taste-tender', 'type-hot', 'price-moderate', 'time-slow', 'period-dinner', 'temp-hot', 'season-all'],
    stats: { pickCount: 0, rejectCount: 0 },
    createdAt: FIXED_TIMESTAMP,
  },
  {
    id: 'demo-ch16',
    name: '水煮白菜',
    tags: ['cuisine-chinese', 'taste-light', 'taste-fresh', 'type-hot', 'price-budget', 'time-fast', 'period-lunch', 'period-dinner', 'temp-hot', 'season-all'],
    stats: { pickCount: 0, rejectCount: 0 },
    createdAt: FIXED_TIMESTAMP,
  },
  {
    id: 'demo-ch17',
    name: '干煸豆角',
    tags: ['cuisine-chinese', 'taste-salty', 'taste-fragrant', 'taste-crispy', 'type-hot', 'price-budget', 'time-normal', 'period-lunch', 'period-dinner', 'temp-hot', 'season-all'],
    stats: { pickCount: 0, rejectCount: 0 },
    createdAt: FIXED_TIMESTAMP,
  },
  {
    id: 'demo-ch18',
    name: '蒜苗回锅肉',
    tags: ['cuisine-chinese', 'taste-medium-spicy', 'taste-salty', 'taste-fragrant', 'type-hot', 'price-moderate', 'time-normal', 'period-lunch', 'period-dinner', 'temp-hot', 'season-all'],
    stats: { pickCount: 0, rejectCount: 0 },
    createdAt: FIXED_TIMESTAMP,
  },
  {
    id: 'demo-ch19',
    name: '家常豆腐',
    tags: ['cuisine-chinese', 'taste-salty', 'taste-soft', 'taste-umami', 'type-hot', 'price-budget', 'time-fast', 'period-lunch', 'period-dinner', 'temp-hot', 'season-all'],
    stats: { pickCount: 0, rejectCount: 0 },
    createdAt: FIXED_TIMESTAMP,
  },
  {
    id: 'demo-ch20',
    name: '宫保虾仁',
    tags: ['cuisine-chinese', 'taste-mild-spicy', 'taste-sour-sweet', 'taste-crispy', 'type-hot', 'price-moderate', 'time-normal', 'period-lunch', 'period-dinner', 'temp-hot', 'season-all'],
    stats: { pickCount: 0, rejectCount: 0 },
    createdAt: FIXED_TIMESTAMP,
  },
  {
    id: 'demo-ch21',
    name: '红烧茄子',
    tags: ['cuisine-chinese', 'taste-salty', 'taste-sweet', 'taste-soft', 'type-hot', 'price-budget', 'time-normal', 'period-lunch', 'period-dinner', 'temp-hot', 'season-summer'],
    stats: { pickCount: 0, rejectCount: 0 },
    createdAt: FIXED_TIMESTAMP,
  },
  {
    id: 'demo-ch22',
    name: '炒合菜',
    tags: ['cuisine-chinese', 'taste-light', 'taste-fresh', 'taste-umami', 'type-hot', 'price-budget', 'time-fast', 'period-lunch', 'period-dinner', 'temp-hot', 'season-all'],
    stats: { pickCount: 0, rejectCount: 0 },
    createdAt: FIXED_TIMESTAMP,
  },
  {
    id: 'demo-ch23',
    name: '肉末粉条',
    tags: ['cuisine-chinese', 'taste-salty', 'taste-slurpy', 'taste-heavy', 'type-hot', 'price-budget', 'time-fast', 'period-lunch', 'period-dinner', 'temp-hot', 'season-all'],
    stats: { pickCount: 0, rejectCount: 0 },
    createdAt: FIXED_TIMESTAMP,
  },
  {
    id: 'demo-ch24',
    name: '炒年糕',
    tags: ['cuisine-chinese', 'taste-salty', 'taste-chewy', 'taste-sweet', 'type-snack', 'price-budget', 'time-fast', 'period-lunch', 'period-snack', 'temp-hot', 'season-all'],
    stats: { pickCount: 0, rejectCount: 0 },
    createdAt: FIXED_TIMESTAMP,
  },
  {
    id: 'demo-ch25',
    name: '扬州炒饭',
    tags: ['cuisine-chinese', 'taste-salty', 'taste-fragrant', 'taste-umami', 'type-rice', 'price-budget', 'time-fast', 'period-lunch', 'period-dinner', 'temp-hot', 'season-all'],
    stats: { pickCount: 0, rejectCount: 0 },
    createdAt: FIXED_TIMESTAMP,
  },
  {
    id: 'demo-ch26',
    name: '蛋炒饭',
    tags: ['cuisine-chinese', 'taste-salty', 'taste-fragrant', 'type-rice', 'price-budget', 'time-fast', 'period-lunch', 'period-dinner', 'temp-hot', 'season-all'],
    stats: { pickCount: 0, rejectCount: 0 },
    createdAt: FIXED_TIMESTAMP,
  },
  {
    id: 'demo-ch27',
    name: '葱油拌面',
    tags: ['cuisine-chinese', 'taste-fragrant', 'taste-salty', 'taste-slurpy', 'type-noodles', 'price-budget', 'time-fast', 'period-lunch', 'period-dinner', 'temp-hot', 'season-all'],
    stats: { pickCount: 0, rejectCount: 0 },
    createdAt: FIXED_TIMESTAMP,
  },
  {
    id: 'demo-ch28',
    name: '炸酱面',
    tags: ['cuisine-chinese', 'taste-salty', 'taste-heavy', 'taste-chewy', 'type-noodles', 'price-budget', 'time-fast', 'period-lunch', 'period-dinner', 'temp-hot', 'season-all'],
    stats: { pickCount: 0, rejectCount: 0 },
    createdAt: FIXED_TIMESTAMP,
  },
  {
    id: 'demo-ch29',
    name: '韭菜盒子',
    tags: ['cuisine-chinese', 'taste-fragrant', 'taste-crispy', 'taste-salty', 'type-dimsum', 'price-budget', 'time-fast', 'period-breakfast', 'period-snack', 'temp-hot', 'season-all'],
    stats: { pickCount: 0, rejectCount: 0 },
    createdAt: FIXED_TIMESTAMP,
  },
  {
    id: 'demo-ch30',
    name: '葱花饼',
    tags: ['cuisine-chinese', 'taste-fragrant', 'taste-crispy', 'taste-salty', 'type-dimsum', 'price-budget', 'time-fast', 'period-breakfast', 'period-snack', 'temp-hot', 'season-all'],
    stats: { pickCount: 0, rejectCount: 0 },
    createdAt: FIXED_TIMESTAMP,
  },
  {
    id: 'demo-ch31',
    name: '鸡蛋羹',
    tags: ['cuisine-chinese', 'taste-light', 'taste-tender', 'taste-umami', 'type-hot', 'price-budget', 'time-fast', 'period-breakfast', 'period-lunch', 'temp-hot', 'season-all'],
    stats: { pickCount: 0, rejectCount: 0 },
    createdAt: FIXED_TIMESTAMP,
  },
  {
    id: 'demo-ch32',
    name: '紫菜蛋花汤',
    tags: ['cuisine-chinese', 'taste-light', 'taste-umami', 'taste-fresh', 'type-soup', 'price-budget', 'time-fast', 'period-lunch', 'period-dinner', 'temp-hot', 'season-all'],
    stats: { pickCount: 0, rejectCount: 0 },
    createdAt: FIXED_TIMESTAMP,
  },
  {
    id: 'demo-ch33',
    name: '西红柿鸡蛋面',
    tags: ['cuisine-chinese', 'taste-sour-sweet', 'taste-light', 'taste-slurpy', 'type-noodles', 'price-budget', 'time-fast', 'period-lunch', 'period-dinner', 'temp-hot', 'season-all'],
    stats: { pickCount: 0, rejectCount: 0 },
    createdAt: FIXED_TIMESTAMP,
  },
  {
    id: 'demo-ch34',
    name: '红烧鱼块',
    tags: ['cuisine-chinese', 'taste-salty', 'taste-sweet', 'taste-tender', 'taste-umami', 'type-hot', 'price-moderate', 'time-normal', 'period-lunch', 'period-dinner', 'temp-hot', 'season-all'],
    stats: { pickCount: 0, rejectCount: 0 },
    createdAt: FIXED_TIMESTAMP,
  },
  {
    id: 'demo-ch35',
    name: '清炒时蔬',
    tags: ['cuisine-chinese', 'taste-light', 'taste-fresh', 'type-hot', 'price-budget', 'time-fast', 'period-lunch', 'period-dinner', 'temp-hot', 'season-all'],
    stats: { pickCount: 0, rejectCount: 0 },
    createdAt: FIXED_TIMESTAMP,
  },
  {
    id: 'demo-ch36',
    name: '炝炒土豆丝',
    tags: ['cuisine-chinese', 'taste-mild-spicy', 'taste-crispy', 'taste-sour', 'type-hot', 'price-budget', 'time-fast', 'period-lunch', 'period-dinner', 'temp-hot', 'season-all'],
    stats: { pickCount: 0, rejectCount: 0 },
    createdAt: FIXED_TIMESTAMP,
  },
  {
    id: 'demo-ch37',
    name: '凉拌黄瓜',
    tags: ['cuisine-chinese', 'taste-light', 'taste-fresh', 'taste-cold-dish', 'type-cold', 'price-budget', 'time-fast', 'period-lunch', 'period-dinner', 'temp-cold', 'season-summer'],
    stats: { pickCount: 0, rejectCount: 0 },
    createdAt: FIXED_TIMESTAMP,
  },
  {
    id: 'demo-ch38',
    name: '凉拌木耳',
    tags: ['cuisine-chinese', 'taste-light', 'taste-fresh', 'taste-cold-dish', 'type-cold', 'price-budget', 'time-fast', 'period-lunch', 'period-dinner', 'temp-cold', 'season-summer'],
    stats: { pickCount: 0, rejectCount: 0 },
    createdAt: FIXED_TIMESTAMP,
  },
  {
    id: 'demo-ch39',
    name: '拍黄瓜',
    tags: ['cuisine-chinese', 'taste-light', 'taste-fresh', 'taste-cold-dish', 'type-cold', 'price-budget', 'time-fast', 'period-lunch', 'period-dinner', 'temp-cold', 'season-summer'],
    stats: { pickCount: 0, rejectCount: 0 },
    createdAt: FIXED_TIMESTAMP,
  },
  {
    id: 'demo-ch40',
    name: '皮蛋豆腐',
    tags: ['cuisine-chinese', 'taste-light', 'taste-cold-dish', 'taste-soft', 'type-cold', 'price-budget', 'time-fast', 'period-lunch', 'period-dinner', 'temp-cold', 'season-summer'],
    stats: { pickCount: 0, rejectCount: 0 },
    createdAt: FIXED_TIMESTAMP,
  },
  {
    id: 'demo-ch41',
    name: '麻酱凉面',
    tags: ['cuisine-chinese', 'taste-fragrant', 'taste-salty', 'taste-slurpy', 'type-noodles', 'price-budget', 'time-fast', 'period-lunch', 'temp-cold', 'season-summer'],
    stats: { pickCount: 0, rejectCount: 0 },
    createdAt: FIXED_TIMESTAMP,
  },
  {
    id: 'demo-ch42',
    name: '白菜炖豆腐',
    tags: ['cuisine-chinese', 'taste-light', 'taste-umami', 'taste-soft', 'type-hot', 'price-budget', 'time-normal', 'period-lunch', 'period-dinner', 'temp-hot', 'season-winter'],
    stats: { pickCount: 0, rejectCount: 0 },
    createdAt: FIXED_TIMESTAMP,
  },
  {
    id: 'demo-ch43',
    name: '猪肉炖粉条',
    tags: ['cuisine-chinese', 'taste-salty', 'taste-heavy', 'taste-slurpy', 'type-hot', 'price-moderate', 'time-slow', 'period-dinner', 'temp-hot', 'season-winter'],
    stats: { pickCount: 0, rejectCount: 0 },
    createdAt: FIXED_TIMESTAMP,
  },
  {
    id: 'demo-ch44',
    name: '小鸡炖蘑菇',
    tags: ['cuisine-chinese', 'taste-umami', 'taste-tender', 'taste-heavy', 'type-hot', 'price-moderate', 'time-slow', 'period-dinner', 'temp-hot', 'season-winter'],
    stats: { pickCount: 0, rejectCount: 0 },
    createdAt: FIXED_TIMESTAMP,
  },
  {
    id: 'demo-ch45',
    name: '铁锅炖大鹅',
    tags: ['cuisine-chinese', 'taste-salty', 'taste-heavy', 'taste-tender', 'type-hot', 'price-premium', 'time-slow', 'period-dinner', 'temp-hot', 'season-winter'],
    stats: { pickCount: 0, rejectCount: 0 },
    createdAt: FIXED_TIMESTAMP,
  },
  {
    id: 'demo-ch46',
    name: '蒸饺',
    tags: ['cuisine-chinese', 'taste-umami', 'taste-tender', 'taste-fragrant', 'type-dimsum', 'price-budget', 'time-normal', 'period-lunch', 'period-dinner', 'temp-hot', 'season-all'],
    stats: { pickCount: 0, rejectCount: 0 },
    createdAt: FIXED_TIMESTAMP,
  },
  {
    id: 'demo-ch47',
    name: '馄饨',
    tags: ['cuisine-chinese', 'taste-light', 'taste-umami', 'taste-slurpy', 'type-dimsum', 'price-budget', 'time-fast', 'period-breakfast', 'period-lunch', 'temp-hot', 'season-all'],
    stats: { pickCount: 0, rejectCount: 0 },
    createdAt: FIXED_TIMESTAMP,
  },
  {
    id: 'demo-ch48',
    name: '小米粥',
    tags: ['cuisine-chinese', 'taste-light', 'taste-soft', 'type-soup', 'price-budget', 'time-normal', 'period-breakfast', 'temp-hot', 'season-all'],
    stats: { pickCount: 0, rejectCount: 0 },
    createdAt: FIXED_TIMESTAMP,
  },
  {
    id: 'demo-ch49',
    name: '八宝粥',
    tags: ['cuisine-chinese', 'taste-sweet', 'taste-soft', 'type-soup', 'price-budget', 'time-slow', 'period-breakfast', 'period-snack', 'temp-hot', 'season-winter'],
    stats: { pickCount: 0, rejectCount: 0 },
    createdAt: FIXED_TIMESTAMP,
  },
  {
    id: 'demo-ch50',
    name: '葱油饼',
    tags: ['cuisine-chinese', 'taste-fragrant', 'taste-crispy', 'taste-salty', 'type-dimsum', 'price-budget', 'time-fast', 'period-breakfast', 'period-snack', 'temp-hot', 'season-all'],
    stats: { pickCount: 0, rejectCount: 0 },
    createdAt: FIXED_TIMESTAMP,
  },
]
