import { Dish } from '@/types'

const FIXED_TIMESTAMP = 1700000000000

export const FASTFOOD_DISHES: Dish[] = [
  {
    id: 'demo-ff1',
    name: '汉堡套餐',
    tags: ['cuisine-fastfood', 'taste-salty', 'taste-fragrant', 'type-staple', 'price-moderate', 'time-fast', 'period-lunch', 'period-dinner', 'temp-hot', 'season-all'],
    stats: { pickCount: 0, rejectCount: 0 },
    createdAt: FIXED_TIMESTAMP,
  },
  {
    id: 'demo-ff2',
    name: '麻辣烫',
    tags: ['cuisine-fastfood', 'taste-mala', 'taste-heavy', 'type-soup', 'price-budget', 'time-fast', 'period-lunch', 'period-dinner', 'period-midnight', 'temp-hot', 'season-winter'],
    stats: { pickCount: 0, rejectCount: 0 },
    createdAt: FIXED_TIMESTAMP,
  },
  {
    id: 'demo-ff3',
    name: '盖浇饭',
    tags: ['cuisine-fastfood', 'taste-salty', 'taste-fragrant', 'type-rice', 'price-budget', 'time-fast', 'period-lunch', 'period-dinner', 'temp-hot', 'season-all'],
    stats: { pickCount: 0, rejectCount: 0 },
    createdAt: FIXED_TIMESTAMP,
  },
  {
    id: 'demo-ff4',
    name: '炸鸡排',
    tags: ['cuisine-fastfood', 'taste-crispy', 'taste-salty', 'taste-fragrant', 'type-snack', 'price-budget', 'time-fast', 'period-lunch', 'period-snack', 'temp-hot', 'season-all'],
    stats: { pickCount: 0, rejectCount: 0 },
    createdAt: FIXED_TIMESTAMP,
  },
  {
    id: 'demo-ff5',
    name: '煎饼果子',
    tags: ['cuisine-fastfood', 'taste-crispy', 'taste-salty', 'taste-fragrant', 'type-snack', 'price-budget', 'time-fast', 'period-breakfast', 'temp-hot', 'season-all'],
    stats: { pickCount: 0, rejectCount: 0 },
    createdAt: FIXED_TIMESTAMP,
  },
  {
    id: 'demo-ff6',
    name: '肉夹馍',
    tags: ['cuisine-fastfood', 'taste-salty', 'taste-fragrant', 'taste-crispy', 'type-snack', 'price-budget', 'time-fast', 'period-lunch', 'period-breakfast', 'temp-hot', 'season-all'],
    stats: { pickCount: 0, rejectCount: 0 },
    createdAt: FIXED_TIMESTAMP,
  },
  {
    id: 'demo-ff7',
    name: '凉皮',
    tags: ['cuisine-fastfood', 'taste-sour', 'taste-mild-spicy', 'taste-chewy', 'type-snack', 'price-budget', 'time-fast', 'period-lunch', 'temp-cold', 'season-summer'],
    stats: { pickCount: 0, rejectCount: 0 },
    createdAt: FIXED_TIMESTAMP,
  },
  {
    id: 'demo-ff8',
    name: '螺蛳粉',
    tags: ['cuisine-fastfood', 'taste-medium-spicy', 'taste-sour', 'taste-heavy', 'type-noodles', 'price-budget', 'time-fast', 'period-lunch', 'period-dinner', 'period-midnight', 'temp-hot', 'season-all'],
    stats: { pickCount: 0, rejectCount: 0 },
    createdAt: FIXED_TIMESTAMP,
  },
  {
    id: 'demo-ff9',
    name: '卤肉饭',
    tags: ['cuisine-fastfood', 'taste-salty', 'taste-fragrant', 'taste-umami', 'type-rice', 'price-budget', 'time-fast', 'period-lunch', 'period-dinner', 'temp-hot', 'season-all'],
    stats: { pickCount: 0, rejectCount: 0 },
    createdAt: FIXED_TIMESTAMP,
  },
  {
    id: 'demo-ff10',
    name: '鸡蛋灌饼',
    tags: ['cuisine-fastfood', 'taste-crispy', 'taste-salty', 'taste-fragrant', 'type-snack', 'price-budget', 'time-fast', 'period-breakfast', 'temp-hot', 'season-all'],
    stats: { pickCount: 0, rejectCount: 0 },
    createdAt: FIXED_TIMESTAMP,
  },
  {
    id: 'demo-ff11',
    name: '手抓饼',
    tags: ['cuisine-fastfood', 'taste-crispy', 'taste-salty', 'taste-fragrant', 'type-snack', 'price-budget', 'time-fast', 'period-breakfast', 'period-snack', 'temp-hot', 'season-all'],
    stats: { pickCount: 0, rejectCount: 0 },
    createdAt: FIXED_TIMESTAMP,
  },
  {
    id: 'demo-ff12',
    name: '烧饼夹肉',
    tags: ['cuisine-fastfood', 'taste-crispy', 'taste-salty', 'taste-fragrant', 'type-snack', 'price-budget', 'time-fast', 'period-breakfast', 'period-lunch', 'temp-hot', 'season-all'],
    stats: { pickCount: 0, rejectCount: 0 },
    createdAt: FIXED_TIMESTAMP,
  },
  {
    id: 'demo-ff13',
    name: '兰州牛肉面',
    tags: ['cuisine-fastfood', 'taste-umami', 'taste-salty', 'taste-slurpy', 'type-noodles', 'price-budget', 'time-fast', 'period-lunch', 'period-dinner', 'temp-hot', 'season-all'],
    stats: { pickCount: 0, rejectCount: 0 },
    createdAt: FIXED_TIMESTAMP,
  },
  {
    id: 'demo-ff14',
    name: '重庆小面',
    tags: ['cuisine-fastfood', 'taste-mala', 'taste-heavy', 'taste-slurpy', 'type-noodles', 'price-budget', 'time-fast', 'period-lunch', 'period-breakfast', 'temp-hot', 'season-all'],
    stats: { pickCount: 0, rejectCount: 0 },
    createdAt: FIXED_TIMESTAMP,
  },
  {
    id: 'demo-ff15',
    name: '武汉热干面',
    tags: ['cuisine-fastfood', 'taste-fragrant', 'taste-salty', 'taste-chewy', 'type-noodles', 'price-budget', 'time-fast', 'period-breakfast', 'period-lunch', 'temp-hot', 'season-all'],
    stats: { pickCount: 0, rejectCount: 0 },
    createdAt: FIXED_TIMESTAMP,
  },
  {
    id: 'demo-ff16',
    name: '刀削面',
    tags: ['cuisine-fastfood', 'taste-salty', 'taste-chewy', 'taste-umami', 'type-noodles', 'price-budget', 'time-fast', 'period-lunch', 'period-dinner', 'temp-hot', 'season-all'],
    stats: { pickCount: 0, rejectCount: 0 },
    createdAt: FIXED_TIMESTAMP,
  },
  {
    id: 'demo-ff17',
    name: '油泼面',
    tags: ['cuisine-fastfood', 'taste-mild-spicy', 'taste-fragrant', 'taste-chewy', 'type-noodles', 'price-budget', 'time-fast', 'period-lunch', 'period-dinner', 'temp-hot', 'season-all'],
    stats: { pickCount: 0, rejectCount: 0 },
    createdAt: FIXED_TIMESTAMP,
  },
  {
    id: 'demo-ff18',
    name: '炒饭套餐',
    tags: ['cuisine-fastfood', 'taste-salty', 'taste-fragrant', 'type-rice', 'price-budget', 'time-fast', 'period-lunch', 'period-dinner', 'temp-hot', 'season-all'],
    stats: { pickCount: 0, rejectCount: 0 },
    createdAt: FIXED_TIMESTAMP,
  },
  {
    id: 'demo-ff19',
    name: '关东煮',
    tags: ['cuisine-fastfood', 'taste-light', 'taste-umami', 'taste-fresh', 'type-soup', 'price-budget', 'time-fast', 'period-snack', 'period-midnight', 'temp-hot', 'season-winter'],
    stats: { pickCount: 0, rejectCount: 0 },
    createdAt: FIXED_TIMESTAMP,
  },
  {
    id: 'demo-ff20',
    name: '烤冷面',
    tags: ['cuisine-fastfood', 'taste-sour-sweet', 'taste-mild-spicy', 'taste-chewy', 'type-snack', 'price-budget', 'time-fast', 'period-snack', 'period-midnight', 'temp-hot', 'season-all'],
    stats: { pickCount: 0, rejectCount: 0 },
    createdAt: FIXED_TIMESTAMP,
  },
  {
    id: 'demo-ff21',
    name: '鸡公煲',
    tags: ['cuisine-fastfood', 'taste-medium-spicy', 'taste-heavy', 'taste-fragrant', 'type-hot', 'price-moderate', 'time-normal', 'period-lunch', 'period-dinner', 'temp-hot', 'season-winter'],
    stats: { pickCount: 0, rejectCount: 0 },
    createdAt: FIXED_TIMESTAMP,
  },
  {
    id: 'demo-ff22',
    name: '冒烤鸭',
    tags: ['cuisine-fastfood', 'taste-mala', 'taste-fragrant', 'taste-heavy', 'type-hot', 'price-moderate', 'time-fast', 'period-lunch', 'period-dinner', 'temp-hot', 'season-all'],
    stats: { pickCount: 0, rejectCount: 0 },
    createdAt: FIXED_TIMESTAMP,
  },
  {
    id: 'demo-ff23',
    name: '鸭血粉丝',
    tags: ['cuisine-fastfood', 'taste-mild-spicy', 'taste-umami', 'taste-slurpy', 'type-soup', 'price-budget', 'time-fast', 'period-lunch', 'period-dinner', 'temp-hot', 'season-all'],
    stats: { pickCount: 0, rejectCount: 0 },
    createdAt: FIXED_TIMESTAMP,
  },
  {
    id: 'demo-ff24',
    name: '牛肉粉',
    tags: ['cuisine-fastfood', 'taste-umami', 'taste-salty', 'taste-slurpy', 'type-noodles', 'price-budget', 'time-fast', 'period-lunch', 'period-breakfast', 'temp-hot', 'season-all'],
    stats: { pickCount: 0, rejectCount: 0 },
    createdAt: FIXED_TIMESTAMP,
  },
  {
    id: 'demo-ff25',
    name: '羊肉泡馍',
    tags: ['cuisine-fastfood', 'taste-umami', 'taste-salty', 'taste-heavy', 'type-soup', 'price-moderate', 'time-normal', 'period-lunch', 'period-dinner', 'temp-hot', 'season-winter'],
    stats: { pickCount: 0, rejectCount: 0 },
    createdAt: FIXED_TIMESTAMP,
  },
  {
    id: 'demo-ff26',
    name: '炒河粉',
    tags: ['cuisine-fastfood', 'taste-salty', 'taste-fragrant', 'taste-chewy', 'type-noodles', 'price-budget', 'time-fast', 'period-lunch', 'period-dinner', 'temp-hot', 'season-all'],
    stats: { pickCount: 0, rejectCount: 0 },
    createdAt: FIXED_TIMESTAMP,
  },
  {
    id: 'demo-ff27',
    name: '生煎包',
    tags: ['cuisine-fastfood', 'taste-crispy', 'taste-umami', 'taste-fragrant', 'type-dimsum', 'price-budget', 'time-fast', 'period-breakfast', 'period-lunch', 'temp-hot', 'season-all'],
    stats: { pickCount: 0, rejectCount: 0 },
    createdAt: FIXED_TIMESTAMP,
  },
  {
    id: 'demo-ff28',
    name: '小笼包',
    tags: ['cuisine-fastfood', 'taste-umami', 'taste-fresh', 'taste-tender', 'type-dimsum', 'price-budget', 'time-fast', 'period-breakfast', 'period-lunch', 'temp-hot', 'season-all'],
    stats: { pickCount: 0, rejectCount: 0 },
    createdAt: FIXED_TIMESTAMP,
  },
  {
    id: 'demo-ff29',
    name: '锅贴',
    tags: ['cuisine-fastfood', 'taste-crispy', 'taste-fragrant', 'taste-salty', 'type-dimsum', 'price-budget', 'time-fast', 'period-breakfast', 'period-lunch', 'temp-hot', 'season-all'],
    stats: { pickCount: 0, rejectCount: 0 },
    createdAt: FIXED_TIMESTAMP,
  },
  {
    id: 'demo-ff30',
    name: '拉条子',
    tags: ['cuisine-fastfood', 'taste-salty', 'taste-chewy', 'taste-fragrant', 'type-noodles', 'price-budget', 'time-fast', 'period-lunch', 'period-dinner', 'temp-hot', 'season-all'],
    stats: { pickCount: 0, rejectCount: 0 },
    createdAt: FIXED_TIMESTAMP,
  },
  {
    id: 'demo-ff31',
    name: '炒面',
    tags: ['cuisine-fastfood', 'taste-salty', 'taste-fragrant', 'taste-chewy', 'type-noodles', 'price-budget', 'time-fast', 'period-lunch', 'period-dinner', 'temp-hot', 'season-all'],
    stats: { pickCount: 0, rejectCount: 0 },
    createdAt: FIXED_TIMESTAMP,
  },
  {
    id: 'demo-ff32',
    name: '混沌',
    tags: ['cuisine-fastfood', 'taste-umami', 'taste-fresh', 'taste-slurpy', 'type-soup', 'price-budget', 'time-fast', 'period-breakfast', 'period-lunch', 'temp-hot', 'season-all'],
    stats: { pickCount: 0, rejectCount: 0 },
    createdAt: FIXED_TIMESTAMP,
  },
  {
    id: 'demo-ff33',
    name: '酸辣粉',
    tags: ['cuisine-fastfood', 'taste-sour', 'taste-mild-spicy', 'taste-slurpy', 'type-noodles', 'price-budget', 'time-fast', 'period-lunch', 'period-snack', 'temp-hot', 'season-all'],
    stats: { pickCount: 0, rejectCount: 0 },
    createdAt: FIXED_TIMESTAMP,
  },
  {
    id: 'demo-ff34',
    name: '牛杂面',
    tags: ['cuisine-fastfood', 'taste-umami', 'taste-salty', 'taste-heavy', 'type-noodles', 'price-budget', 'time-fast', 'period-lunch', 'period-dinner', 'temp-hot', 'season-all'],
    stats: { pickCount: 0, rejectCount: 0 },
    createdAt: FIXED_TIMESTAMP,
  },
  {
    id: 'demo-ff35',
    name: '卤煮',
    tags: ['cuisine-fastfood', 'taste-salty', 'taste-heavy', 'taste-umami', 'type-soup', 'price-budget', 'time-fast', 'period-lunch', 'period-dinner', 'temp-hot', 'season-winter'],
    stats: { pickCount: 0, rejectCount: 0 },
    createdAt: FIXED_TIMESTAMP,
  },
  {
    id: 'demo-ff36',
    name: '豆腐脑',
    tags: ['cuisine-fastfood', 'taste-light', 'taste-umami', 'taste-soft', 'type-snack', 'price-budget', 'time-fast', 'period-breakfast', 'temp-hot', 'season-all'],
    stats: { pickCount: 0, rejectCount: 0 },
    createdAt: FIXED_TIMESTAMP,
  },
  {
    id: 'demo-ff37',
    name: '胡辣汤',
    tags: ['cuisine-fastfood', 'taste-mild-spicy', 'taste-salty', 'taste-umami', 'type-soup', 'price-budget', 'time-fast', 'period-breakfast', 'temp-hot', 'season-winter'],
    stats: { pickCount: 0, rejectCount: 0 },
    createdAt: FIXED_TIMESTAMP,
  },
  {
    id: 'demo-ff38',
    name: '甑糕',
    tags: ['cuisine-fastfood', 'taste-sweet', 'taste-soft', 'type-dessert', 'price-budget', 'time-fast', 'period-breakfast', 'period-snack', 'temp-room', 'season-all'],
    stats: { pickCount: 0, rejectCount: 0 },
    createdAt: FIXED_TIMESTAMP,
  },
  {
    id: 'demo-ff39',
    name: '灌汤包',
    tags: ['cuisine-fastfood', 'taste-umami', 'taste-fresh', 'taste-tender', 'type-dimsum', 'price-budget', 'time-fast', 'period-breakfast', 'period-lunch', 'temp-hot', 'season-all'],
    stats: { pickCount: 0, rejectCount: 0 },
    createdAt: FIXED_TIMESTAMP,
  },
  {
    id: 'demo-ff40',
    name: '米线',
    tags: ['cuisine-fastfood', 'taste-mild-spicy', 'taste-umami', 'taste-slurpy', 'type-noodles', 'price-budget', 'time-fast', 'period-lunch', 'period-dinner', 'temp-hot', 'season-all'],
    stats: { pickCount: 0, rejectCount: 0 },
    createdAt: FIXED_TIMESTAMP,
  },
]
