import { Dish } from '@/types'

const FIXED_TIMESTAMP = 1700000000000

export const HOTPOT_DISHES: Dish[] = [
  {
    id: 'demo-hp1',
    name: '重庆火锅',
    tags: ['cuisine-hotpot', 'taste-mala', 'taste-extra-spicy', 'taste-heavy', 'type-hot', 'price-premium', 'time-slow', 'period-dinner', 'period-midnight', 'temp-hot', 'season-winter'],
    stats: { pickCount: 0, rejectCount: 0 },
    createdAt: FIXED_TIMESTAMP,
  },
  {
    id: 'demo-hp2',
    name: '潮汕牛肉火锅',
    tags: ['cuisine-hotpot', 'taste-light', 'taste-umami', 'taste-fresh', 'type-hot', 'price-premium', 'time-slow', 'period-dinner', 'temp-hot', 'season-winter'],
    stats: { pickCount: 0, rejectCount: 0 },
    createdAt: FIXED_TIMESTAMP,
  },
  {
    id: 'demo-hp3',
    name: '鸳鸯锅',
    tags: ['cuisine-hotpot', 'taste-mala', 'taste-light', 'type-hot', 'price-premium', 'time-slow', 'period-dinner', 'temp-hot', 'season-winter'],
    stats: { pickCount: 0, rejectCount: 0 },
    createdAt: FIXED_TIMESTAMP,
  },
  {
    id: 'demo-hp4',
    name: '菌菇火锅',
    tags: ['cuisine-hotpot', 'taste-umami', 'taste-light', 'taste-fresh', 'type-hot', 'price-moderate', 'time-slow', 'period-dinner', 'temp-hot', 'season-autumn'],
    stats: { pickCount: 0, rejectCount: 0 },
    createdAt: FIXED_TIMESTAMP,
  },
  {
    id: 'demo-hp5',
    name: '椰子鸡',
    tags: ['cuisine-hotpot', 'taste-sweet', 'taste-light', 'taste-fresh', 'type-soup', 'price-premium', 'time-slow', 'period-dinner', 'temp-hot', 'season-all'],
    stats: { pickCount: 0, rejectCount: 0 },
    createdAt: FIXED_TIMESTAMP,
  },
  {
    id: 'demo-hp6',
    name: '羊蝎子',
    tags: ['cuisine-hotpot', 'taste-umami', 'taste-salty', 'taste-heavy', 'type-hot', 'price-premium', 'time-slow', 'period-dinner', 'temp-hot', 'season-winter'],
    stats: { pickCount: 0, rejectCount: 0 },
    createdAt: FIXED_TIMESTAMP,
  },
  {
    id: 'demo-hp7',
    name: '酸汤鱼火锅',
    tags: ['cuisine-hotpot', 'taste-sour', 'taste-mild-spicy', 'taste-umami', 'type-hot', 'price-moderate', 'time-slow', 'period-dinner', 'temp-hot', 'season-all'],
    stats: { pickCount: 0, rejectCount: 0 },
    createdAt: FIXED_TIMESTAMP,
  },
  {
    id: 'demo-hp8',
    name: '铜锅涮肉',
    tags: ['cuisine-hotpot', 'taste-light', 'taste-umami', 'taste-tender', 'type-hot', 'price-premium', 'time-slow', 'period-dinner', 'temp-hot', 'season-winter'],
    stats: { pickCount: 0, rejectCount: 0 },
    createdAt: FIXED_TIMESTAMP,
  },
  {
    id: 'demo-hp9',
    name: '番茄火锅',
    tags: ['cuisine-hotpot', 'taste-sour-sweet', 'taste-light', 'taste-umami', 'type-hot', 'price-moderate', 'time-slow', 'period-dinner', 'temp-hot', 'season-all'],
    stats: { pickCount: 0, rejectCount: 0 },
    createdAt: FIXED_TIMESTAMP,
  },
  {
    id: 'demo-hp10',
    name: '毛肚火锅',
    tags: ['cuisine-hotpot', 'taste-mala', 'taste-heavy', 'taste-chewy', 'type-hot', 'price-premium', 'time-slow', 'period-dinner', 'temp-hot', 'season-winter'],
    stats: { pickCount: 0, rejectCount: 0 },
    createdAt: FIXED_TIMESTAMP,
  },
  {
    id: 'demo-hp11',
    name: '清汤火锅',
    tags: ['cuisine-hotpot', 'taste-light', 'taste-umami', 'taste-fresh', 'type-hot', 'price-moderate', 'time-slow', 'period-dinner', 'temp-hot', 'season-all'],
    stats: { pickCount: 0, rejectCount: 0 },
    createdAt: FIXED_TIMESTAMP,
  },
  {
    id: 'demo-hp12',
    name: '牛油火锅',
    tags: ['cuisine-hotpot', 'taste-mala', 'taste-heavy', 'taste-fragrant', 'type-hot', 'price-premium', 'time-slow', 'period-dinner', 'period-midnight', 'temp-hot', 'season-winter'],
    stats: { pickCount: 0, rejectCount: 0 },
    createdAt: FIXED_TIMESTAMP,
  },
  {
    id: 'demo-hp13',
    name: '猪肚鸡',
    tags: ['cuisine-hotpot', 'taste-light', 'taste-umami', 'taste-tender', 'type-soup', 'price-premium', 'time-slow', 'period-dinner', 'temp-hot', 'season-winter'],
    stats: { pickCount: 0, rejectCount: 0 },
    createdAt: FIXED_TIMESTAMP,
  },
  {
    id: 'demo-hp14',
    name: '鱼头火锅',
    tags: ['cuisine-hotpot', 'taste-umami', 'taste-mild-spicy', 'taste-fresh', 'type-hot', 'price-moderate', 'time-slow', 'period-dinner', 'temp-hot', 'season-all'],
    stats: { pickCount: 0, rejectCount: 0 },
    createdAt: FIXED_TIMESTAMP,
  },
  {
    id: 'demo-hp15',
    name: '麻辣火锅',
    tags: ['cuisine-hotpot', 'taste-mala', 'taste-extra-spicy', 'taste-heavy', 'type-hot', 'price-moderate', 'time-slow', 'period-dinner', 'period-midnight', 'temp-hot', 'season-winter'],
    stats: { pickCount: 0, rejectCount: 0 },
    createdAt: FIXED_TIMESTAMP,
  },
  {
    id: 'demo-hp16',
    name: '打边炉',
    tags: ['cuisine-hotpot', 'taste-light', 'taste-umami', 'taste-fresh', 'type-hot', 'price-moderate', 'time-slow', 'period-dinner', 'temp-hot', 'season-winter'],
    stats: { pickCount: 0, rejectCount: 0 },
    createdAt: FIXED_TIMESTAMP,
  },
  {
    id: 'demo-hp17',
    name: '泰式冬阴功火锅',
    tags: ['cuisine-hotpot', 'taste-sour', 'taste-medium-spicy', 'taste-umami', 'type-hot', 'price-premium', 'time-slow', 'period-dinner', 'temp-hot', 'season-all'],
    stats: { pickCount: 0, rejectCount: 0 },
    createdAt: FIXED_TIMESTAMP,
  },
  {
    id: 'demo-hp18',
    name: '豆捞火锅',
    tags: ['cuisine-hotpot', 'taste-light', 'taste-umami', 'taste-fresh', 'type-hot', 'price-premium', 'time-slow', 'period-dinner', 'temp-hot', 'season-all'],
    stats: { pickCount: 0, rejectCount: 0 },
    createdAt: FIXED_TIMESTAMP,
  },
  {
    id: 'demo-hp19',
    name: '自助小火锅',
    tags: ['cuisine-hotpot', 'taste-mild-spicy', 'taste-umami', 'type-hot', 'price-budget', 'time-normal', 'period-lunch', 'period-dinner', 'temp-hot', 'season-all'],
    stats: { pickCount: 0, rejectCount: 0 },
    createdAt: FIXED_TIMESTAMP,
  },
  {
    id: 'demo-hp20',
    name: '涮羊肉',
    tags: ['cuisine-hotpot', 'taste-light', 'taste-umami', 'taste-tender', 'type-hot', 'price-premium', 'time-slow', 'period-dinner', 'temp-hot', 'season-winter'],
    stats: { pickCount: 0, rejectCount: 0 },
    createdAt: FIXED_TIMESTAMP,
  },
]
