import { Dish } from '@/types'

const FIXED_TIMESTAMP = 1700000000000

export const HUNAN_DISHES: Dish[] = [
  {
    id: 'demo-hn1',
    name: '剁椒鱼头',
    tags: ['cuisine-hunan', 'taste-extra-spicy', 'taste-umami', 'taste-tender', 'type-hot', 'price-premium', 'time-slow', 'period-dinner', 'temp-hot', 'season-all'],
    stats: { pickCount: 0, rejectCount: 0 },
    createdAt: FIXED_TIMESTAMP,
  },
  {
    id: 'demo-hn2',
    name: '小炒肉',
    tags: ['cuisine-hunan', 'taste-medium-spicy', 'taste-salty', 'taste-fragrant', 'type-hot', 'price-moderate', 'time-normal', 'period-lunch', 'period-dinner', 'temp-hot', 'season-all'],
    stats: { pickCount: 0, rejectCount: 0 },
    createdAt: FIXED_TIMESTAMP,
  },
  {
    id: 'demo-hn3',
    name: '口味虾',
    tags: ['cuisine-hunan', 'taste-extra-spicy', 'taste-heavy', 'taste-fragrant', 'type-hot', 'price-premium', 'time-slow', 'period-dinner', 'period-midnight', 'temp-hot', 'season-summer'],
    stats: { pickCount: 0, rejectCount: 0 },
    createdAt: FIXED_TIMESTAMP,
  },
  {
    id: 'demo-hn4',
    name: '农家小炒',
    tags: ['cuisine-hunan', 'taste-medium-spicy', 'taste-fresh', 'taste-fragrant', 'type-hot', 'price-budget', 'time-fast', 'period-lunch', 'period-dinner', 'temp-hot', 'season-all'],
    stats: { pickCount: 0, rejectCount: 0 },
    createdAt: FIXED_TIMESTAMP,
  },
  {
    id: 'demo-hn5',
    name: '辣椒炒肉',
    tags: ['cuisine-hunan', 'taste-medium-spicy', 'taste-salty', 'taste-fragrant', 'type-hot', 'price-moderate', 'time-normal', 'period-lunch', 'period-dinner', 'temp-hot', 'season-all'],
    stats: { pickCount: 0, rejectCount: 0 },
    createdAt: FIXED_TIMESTAMP,
  },
  {
    id: 'demo-hn6',
    name: '酱板鸭',
    tags: ['cuisine-hunan', 'taste-extra-spicy', 'taste-salty', 'taste-chewy', 'type-cold', 'price-moderate', 'time-fast', 'period-dinner', 'period-midnight', 'temp-room', 'season-all'],
    stats: { pickCount: 0, rejectCount: 0 },
    createdAt: FIXED_TIMESTAMP,
  },
  {
    id: 'demo-hn7',
    name: '长沙臭豆腐',
    tags: ['cuisine-hunan', 'taste-medium-spicy', 'taste-crispy', 'taste-heavy', 'type-snack', 'price-budget', 'time-fast', 'period-snack', 'period-midnight', 'temp-hot', 'season-all'],
    stats: { pickCount: 0, rejectCount: 0 },
    createdAt: FIXED_TIMESTAMP,
  },
  {
    id: 'demo-hn8',
    name: '血鸭',
    tags: ['cuisine-hunan', 'taste-extra-spicy', 'taste-heavy', 'taste-fragrant', 'type-hot', 'price-premium', 'time-slow', 'period-dinner', 'temp-hot', 'season-autumn'],
    stats: { pickCount: 0, rejectCount: 0 },
    createdAt: FIXED_TIMESTAMP,
  },
  {
    id: 'demo-hn9',
    name: '东安鸡',
    tags: ['cuisine-hunan', 'taste-sour', 'taste-medium-spicy', 'taste-tender', 'type-hot', 'price-moderate', 'time-normal', 'period-lunch', 'period-dinner', 'temp-hot', 'season-all'],
    stats: { pickCount: 0, rejectCount: 0 },
    createdAt: FIXED_TIMESTAMP,
  },
  {
    id: 'demo-hn10',
    name: '腊肉炒笋',
    tags: ['cuisine-hunan', 'taste-salty', 'taste-fragrant', 'taste-crispy', 'type-hot', 'price-moderate', 'time-normal', 'period-lunch', 'period-dinner', 'temp-hot', 'season-spring'],
    stats: { pickCount: 0, rejectCount: 0 },
    createdAt: FIXED_TIMESTAMP,
  },
  {
    id: 'demo-hn11',
    name: '外婆菜',
    tags: ['cuisine-hunan', 'taste-medium-spicy', 'taste-salty', 'taste-fragrant', 'type-hot', 'price-budget', 'time-fast', 'period-lunch', 'period-dinner', 'temp-hot', 'season-all'],
    stats: { pickCount: 0, rejectCount: 0 },
    createdAt: FIXED_TIMESTAMP,
  },
  {
    id: 'demo-hn12',
    name: '浏阳蒸菜',
    tags: ['cuisine-hunan', 'taste-mild-spicy', 'taste-fresh', 'taste-tender', 'type-hot', 'price-budget', 'time-fast', 'period-lunch', 'temp-hot', 'season-all'],
    stats: { pickCount: 0, rejectCount: 0 },
    createdAt: FIXED_TIMESTAMP,
  },
  {
    id: 'demo-hn13',
    name: '糖油粑粑',
    tags: ['cuisine-hunan', 'taste-sweet', 'taste-soft', 'taste-crispy', 'type-snack', 'price-budget', 'time-fast', 'period-snack', 'period-breakfast', 'temp-hot', 'season-all'],
    stats: { pickCount: 0, rejectCount: 0 },
    createdAt: FIXED_TIMESTAMP,
  },
  {
    id: 'demo-hn14',
    name: '剁椒蒸蛋',
    tags: ['cuisine-hunan', 'taste-medium-spicy', 'taste-tender', 'taste-umami', 'type-hot', 'price-budget', 'time-fast', 'period-lunch', 'period-dinner', 'temp-hot', 'season-all'],
    stats: { pickCount: 0, rejectCount: 0 },
    createdAt: FIXED_TIMESTAMP,
  },
  {
    id: 'demo-hn15',
    name: '干锅牛肚',
    tags: ['cuisine-hunan', 'taste-extra-spicy', 'taste-chewy', 'taste-fragrant', 'type-hot', 'price-premium', 'time-normal', 'period-dinner', 'temp-hot', 'season-all'],
    stats: { pickCount: 0, rejectCount: 0 },
    createdAt: FIXED_TIMESTAMP,
  },
  {
    id: 'demo-hn16',
    name: '坛子肉',
    tags: ['cuisine-hunan', 'taste-salty', 'taste-tender', 'taste-heavy', 'type-hot', 'price-moderate', 'time-slow', 'period-dinner', 'temp-hot', 'season-winter'],
    stats: { pickCount: 0, rejectCount: 0 },
    createdAt: FIXED_TIMESTAMP,
  },
  {
    id: 'demo-hn17',
    name: '荷叶粉蒸肉',
    tags: ['cuisine-hunan', 'taste-salty', 'taste-soft', 'taste-fragrant', 'type-hot', 'price-moderate', 'time-slow', 'period-dinner', 'temp-hot', 'season-summer'],
    stats: { pickCount: 0, rejectCount: 0 },
    createdAt: FIXED_TIMESTAMP,
  },
  {
    id: 'demo-hn18',
    name: '湘西腊肉',
    tags: ['cuisine-hunan', 'taste-salty', 'taste-fragrant', 'taste-chewy', 'type-hot', 'price-moderate', 'time-normal', 'period-lunch', 'period-dinner', 'temp-hot', 'season-winter'],
    stats: { pickCount: 0, rejectCount: 0 },
    createdAt: FIXED_TIMESTAMP,
  },
  {
    id: 'demo-hn19',
    name: '攸县豆腐',
    tags: ['cuisine-hunan', 'taste-mild-spicy', 'taste-tender', 'taste-umami', 'type-hot', 'price-budget', 'time-normal', 'period-lunch', 'period-dinner', 'temp-hot', 'season-all'],
    stats: { pickCount: 0, rejectCount: 0 },
    createdAt: FIXED_TIMESTAMP,
  },
  {
    id: 'demo-hn20',
    name: '平江酱干',
    tags: ['cuisine-hunan', 'taste-medium-spicy', 'taste-salty', 'taste-chewy', 'type-snack', 'price-budget', 'time-fast', 'period-snack', 'temp-room', 'season-all'],
    stats: { pickCount: 0, rejectCount: 0 },
    createdAt: FIXED_TIMESTAMP,
  },
  {
    id: 'demo-hn21',
    name: '永州血鸭',
    tags: ['cuisine-hunan', 'taste-extra-spicy', 'taste-heavy', 'taste-fragrant', 'type-hot', 'price-premium', 'time-slow', 'period-dinner', 'temp-hot', 'season-autumn'],
    stats: { pickCount: 0, rejectCount: 0 },
    createdAt: FIXED_TIMESTAMP,
  },
  {
    id: 'demo-hn22',
    name: '祁东黄花菜',
    tags: ['cuisine-hunan', 'taste-light', 'taste-fresh', 'taste-umami', 'type-hot', 'price-budget', 'time-fast', 'period-lunch', 'period-dinner', 'temp-hot', 'season-summer'],
    stats: { pickCount: 0, rejectCount: 0 },
    createdAt: FIXED_TIMESTAMP,
  },
  {
    id: 'demo-hn23',
    name: '猪脚粉',
    tags: ['cuisine-hunan', 'taste-salty', 'taste-heavy', 'taste-soft', 'type-noodles', 'price-budget', 'time-fast', 'period-breakfast', 'period-lunch', 'temp-hot', 'season-all'],
    stats: { pickCount: 0, rejectCount: 0 },
    createdAt: FIXED_TIMESTAMP,
  },
  {
    id: 'demo-hn24',
    name: '红烧甲鱼',
    tags: ['cuisine-hunan', 'taste-salty', 'taste-umami', 'taste-tender', 'type-hot', 'price-luxury', 'time-slow', 'period-dinner', 'temp-hot', 'season-all'],
    stats: { pickCount: 0, rejectCount: 0 },
    createdAt: FIXED_TIMESTAMP,
  },
  {
    id: 'demo-hn25',
    name: '干锅鸡',
    tags: ['cuisine-hunan', 'taste-extra-spicy', 'taste-fragrant', 'taste-crispy', 'type-hot', 'price-moderate', 'time-normal', 'period-dinner', 'temp-hot', 'season-all'],
    stats: { pickCount: 0, rejectCount: 0 },
    createdAt: FIXED_TIMESTAMP,
  },
]
