import { Dish } from '@/types'

const FIXED_TIMESTAMP = 1700000000000

export const JAPANESE_DISHES: Dish[] = [
  {
    id: 'demo-jp1',
    name: '寿司拼盘',
    tags: ['cuisine-japanese', 'taste-light', 'taste-umami', 'taste-fresh', 'type-cold', 'price-premium', 'time-normal', 'period-lunch', 'period-dinner', 'temp-cold', 'season-all'],
    stats: { pickCount: 0, rejectCount: 0 },
    createdAt: FIXED_TIMESTAMP,
  },
  {
    id: 'demo-jp2',
    name: '拉面',
    tags: ['cuisine-japanese', 'taste-umami', 'taste-salty', 'taste-slurpy', 'type-noodles', 'price-moderate', 'time-normal', 'period-lunch', 'period-dinner', 'temp-hot', 'season-all'],
    stats: { pickCount: 0, rejectCount: 0 },
    createdAt: FIXED_TIMESTAMP,
  },
  {
    id: 'demo-jp3',
    name: '鳗鱼饭',
    tags: ['cuisine-japanese', 'taste-sweet', 'taste-umami', 'taste-tender', 'type-rice', 'price-premium', 'time-slow', 'period-lunch', 'period-dinner', 'temp-hot', 'season-all'],
    stats: { pickCount: 0, rejectCount: 0 },
    createdAt: FIXED_TIMESTAMP,
  },
  {
    id: 'demo-jp4',
    name: '天妇罗',
    tags: ['cuisine-japanese', 'taste-light', 'taste-crispy', 'type-hot', 'price-premium', 'time-normal', 'period-lunch', 'period-dinner', 'temp-hot', 'season-all'],
    stats: { pickCount: 0, rejectCount: 0 },
    createdAt: FIXED_TIMESTAMP,
  },
  {
    id: 'demo-jp5',
    name: '刺身',
    tags: ['cuisine-japanese', 'taste-light', 'taste-umami', 'taste-fresh', 'type-cold', 'price-premium', 'time-fast', 'period-lunch', 'period-dinner', 'temp-cold', 'season-all'],
    stats: { pickCount: 0, rejectCount: 0 },
    createdAt: FIXED_TIMESTAMP,
  },
  {
    id: 'demo-jp6',
    name: '味噌汤',
    tags: ['cuisine-japanese', 'taste-light', 'taste-umami', 'type-soup', 'price-budget', 'time-fast', 'period-breakfast', 'period-lunch', 'temp-hot', 'season-all'],
    stats: { pickCount: 0, rejectCount: 0 },
    createdAt: FIXED_TIMESTAMP,
  },
  {
    id: 'demo-jp7',
    name: '猪排饭',
    tags: ['cuisine-japanese', 'taste-salty', 'taste-crispy', 'taste-tender', 'type-rice', 'price-moderate', 'time-normal', 'period-lunch', 'period-dinner', 'temp-hot', 'season-all'],
    stats: { pickCount: 0, rejectCount: 0 },
    createdAt: FIXED_TIMESTAMP,
  },
  {
    id: 'demo-jp8',
    name: '乌冬面',
    tags: ['cuisine-japanese', 'taste-light', 'taste-umami', 'taste-chewy', 'type-noodles', 'price-moderate', 'time-normal', 'period-lunch', 'period-dinner', 'temp-hot', 'season-all'],
    stats: { pickCount: 0, rejectCount: 0 },
    createdAt: FIXED_TIMESTAMP,
  },
  {
    id: 'demo-jp9',
    name: '章鱼小丸子',
    tags: ['cuisine-japanese', 'taste-salty', 'taste-crispy', 'taste-soft', 'type-snack', 'price-budget', 'time-fast', 'period-snack', 'temp-hot', 'season-all'],
    stats: { pickCount: 0, rejectCount: 0 },
    createdAt: FIXED_TIMESTAMP,
  },
  {
    id: 'demo-jp10',
    name: '日式咖喱饭',
    tags: ['cuisine-japanese', 'taste-mild-spicy', 'taste-sweet', 'taste-heavy', 'type-rice', 'price-moderate', 'time-normal', 'period-lunch', 'period-dinner', 'temp-hot', 'season-all'],
    stats: { pickCount: 0, rejectCount: 0 },
    createdAt: FIXED_TIMESTAMP,
  },
  {
    id: 'demo-jp11',
    name: '牛丼',
    tags: ['cuisine-japanese', 'taste-salty', 'taste-sweet', 'taste-tender', 'type-rice', 'price-moderate', 'time-fast', 'period-lunch', 'period-dinner', 'temp-hot', 'season-all'],
    stats: { pickCount: 0, rejectCount: 0 },
    createdAt: FIXED_TIMESTAMP,
  },
  {
    id: 'demo-jp12',
    name: '亲子丼',
    tags: ['cuisine-japanese', 'taste-light', 'taste-umami', 'taste-tender', 'type-rice', 'price-moderate', 'time-fast', 'period-lunch', 'period-dinner', 'temp-hot', 'season-all'],
    stats: { pickCount: 0, rejectCount: 0 },
    createdAt: FIXED_TIMESTAMP,
  },
  {
    id: 'demo-jp13',
    name: '抹茶蛋糕',
    tags: ['cuisine-japanese', 'taste-sweet', 'taste-soft', 'type-dessert', 'price-moderate', 'time-fast', 'period-snack', 'temp-room', 'season-all'],
    stats: { pickCount: 0, rejectCount: 0 },
    createdAt: FIXED_TIMESTAMP,
  },
  {
    id: 'demo-jp14',
    name: '铜锣烧',
    tags: ['cuisine-japanese', 'taste-sweet', 'taste-soft', 'type-dessert', 'price-budget', 'time-fast', 'period-snack', 'temp-room', 'season-all'],
    stats: { pickCount: 0, rejectCount: 0 },
    createdAt: FIXED_TIMESTAMP,
  },
  {
    id: 'demo-jp15',
    name: '日式烤肉',
    tags: ['cuisine-japanese', 'taste-salty', 'taste-fragrant', 'taste-tender', 'type-hot', 'price-premium', 'time-slow', 'period-dinner', 'temp-hot', 'season-all'],
    stats: { pickCount: 0, rejectCount: 0 },
    createdAt: FIXED_TIMESTAMP,
  },
  {
    id: 'demo-jp16',
    name: '寿喜锅',
    tags: ['cuisine-japanese', 'taste-sweet', 'taste-salty', 'taste-umami', 'type-hot', 'price-premium', 'time-slow', 'period-dinner', 'temp-hot', 'season-winter'],
    stats: { pickCount: 0, rejectCount: 0 },
    createdAt: FIXED_TIMESTAMP,
  },
  {
    id: 'demo-jp17',
    name: '日式煎饺',
    tags: ['cuisine-japanese', 'taste-salty', 'taste-crispy', 'taste-umami', 'type-dimsum', 'price-budget', 'time-fast', 'period-lunch', 'period-dinner', 'temp-hot', 'season-all'],
    stats: { pickCount: 0, rejectCount: 0 },
    createdAt: FIXED_TIMESTAMP,
  },
  {
    id: 'demo-jp18',
    name: '三文鱼刺身',
    tags: ['cuisine-japanese', 'taste-light', 'taste-umami', 'taste-fresh', 'type-cold', 'price-premium', 'time-fast', 'period-lunch', 'period-dinner', 'temp-cold', 'season-all'],
    stats: { pickCount: 0, rejectCount: 0 },
    createdAt: FIXED_TIMESTAMP,
  },
  {
    id: 'demo-jp19',
    name: '金枪鱼寿司',
    tags: ['cuisine-japanese', 'taste-light', 'taste-umami', 'taste-fresh', 'type-cold', 'price-premium', 'time-fast', 'period-lunch', 'period-dinner', 'temp-cold', 'season-all'],
    stats: { pickCount: 0, rejectCount: 0 },
    createdAt: FIXED_TIMESTAMP,
  },
  {
    id: 'demo-jp20',
    name: '手卷',
    tags: ['cuisine-japanese', 'taste-light', 'taste-umami', 'taste-fresh', 'type-snack', 'price-moderate', 'time-fast', 'period-lunch', 'period-snack', 'temp-cold', 'season-all'],
    stats: { pickCount: 0, rejectCount: 0 },
    createdAt: FIXED_TIMESTAMP,
  },
  {
    id: 'demo-jp21',
    name: '茶碗蒸',
    tags: ['cuisine-japanese', 'taste-light', 'taste-umami', 'taste-tender', 'type-hot', 'price-moderate', 'time-normal', 'period-lunch', 'period-dinner', 'temp-hot', 'season-all'],
    stats: { pickCount: 0, rejectCount: 0 },
    createdAt: FIXED_TIMESTAMP,
  },
  {
    id: 'demo-jp22',
    name: '日式冷面',
    tags: ['cuisine-japanese', 'taste-light', 'taste-fresh', 'taste-slurpy', 'type-noodles', 'price-moderate', 'time-fast', 'period-lunch', 'temp-cold', 'season-summer'],
    stats: { pickCount: 0, rejectCount: 0 },
    createdAt: FIXED_TIMESTAMP,
  },
  {
    id: 'demo-jp23',
    name: '梅子饭团',
    tags: ['cuisine-japanese', 'taste-sour', 'taste-salty', 'taste-soft', 'type-rice', 'price-budget', 'time-fast', 'period-breakfast', 'period-snack', 'temp-room', 'season-all'],
    stats: { pickCount: 0, rejectCount: 0 },
    createdAt: FIXED_TIMESTAMP,
  },
  {
    id: 'demo-jp24',
    name: '纳豆',
    tags: ['cuisine-japanese', 'taste-umami', 'taste-light', 'type-cold', 'price-budget', 'time-fast', 'period-breakfast', 'temp-room', 'season-all'],
    stats: { pickCount: 0, rejectCount: 0 },
    createdAt: FIXED_TIMESTAMP,
  },
  {
    id: 'demo-jp25',
    name: '关东煮',
    tags: ['cuisine-japanese', 'taste-light', 'taste-umami', 'taste-soft', 'type-hot', 'price-budget', 'time-normal', 'period-dinner', 'period-midnight', 'temp-hot', 'season-winter'],
    stats: { pickCount: 0, rejectCount: 0 },
    createdAt: FIXED_TIMESTAMP,
  },
  {
    id: 'demo-jp26',
    name: '炸猪排',
    tags: ['cuisine-japanese', 'taste-salty', 'taste-crispy', 'taste-tender', 'type-hot', 'price-moderate', 'time-normal', 'period-lunch', 'period-dinner', 'temp-hot', 'season-all'],
    stats: { pickCount: 0, rejectCount: 0 },
    createdAt: FIXED_TIMESTAMP,
  },
  {
    id: 'demo-jp27',
    name: '日式炒面',
    tags: ['cuisine-japanese', 'taste-salty', 'taste-fragrant', 'taste-chewy', 'type-noodles', 'price-budget', 'time-fast', 'period-lunch', 'period-dinner', 'temp-hot', 'season-all'],
    stats: { pickCount: 0, rejectCount: 0 },
    createdAt: FIXED_TIMESTAMP,
  },
  {
    id: 'demo-jp28',
    name: '饭团',
    tags: ['cuisine-japanese', 'taste-light', 'taste-salty', 'taste-soft', 'type-rice', 'price-budget', 'time-fast', 'period-breakfast', 'period-snack', 'temp-room', 'season-all'],
    stats: { pickCount: 0, rejectCount: 0 },
    createdAt: FIXED_TIMESTAMP,
  },
  {
    id: 'demo-jp29',
    name: '味增拉面',
    tags: ['cuisine-japanese', 'taste-salty', 'taste-umami', 'taste-slurpy', 'type-noodles', 'price-moderate', 'time-normal', 'period-lunch', 'period-dinner', 'temp-hot', 'season-winter'],
    stats: { pickCount: 0, rejectCount: 0 },
    createdAt: FIXED_TIMESTAMP,
  },
  {
    id: 'demo-jp30',
    name: '豚骨拉面',
    tags: ['cuisine-japanese', 'taste-heavy', 'taste-umami', 'taste-slurpy', 'type-noodles', 'price-moderate', 'time-normal', 'period-lunch', 'period-dinner', 'temp-hot', 'season-all'],
    stats: { pickCount: 0, rejectCount: 0 },
    createdAt: FIXED_TIMESTAMP,
  },
  {
    id: 'demo-jp31',
    name: '日式烧鸟',
    tags: ['cuisine-japanese', 'taste-salty', 'taste-fragrant', 'taste-tender', 'type-snack', 'price-moderate', 'time-normal', 'period-dinner', 'period-midnight', 'temp-hot', 'season-all'],
    stats: { pickCount: 0, rejectCount: 0 },
    createdAt: FIXED_TIMESTAMP,
  },
  {
    id: 'demo-jp32',
    name: '日式炸鸡',
    tags: ['cuisine-japanese', 'taste-salty', 'taste-crispy', 'taste-tender', 'type-snack', 'price-budget', 'time-fast', 'period-lunch', 'period-snack', 'temp-hot', 'season-all'],
    stats: { pickCount: 0, rejectCount: 0 },
    createdAt: FIXED_TIMESTAMP,
  },
  {
    id: 'demo-jp33',
    name: '冷豆腐',
    tags: ['cuisine-japanese', 'taste-light', 'taste-fresh', 'taste-soft', 'type-cold', 'price-budget', 'time-fast', 'period-lunch', 'period-dinner', 'temp-cold', 'season-summer'],
    stats: { pickCount: 0, rejectCount: 0 },
    createdAt: FIXED_TIMESTAMP,
  },
  {
    id: 'demo-jp34',
    name: '日式蛋包饭',
    tags: ['cuisine-japanese', 'taste-salty', 'taste-sweet', 'taste-tender', 'type-rice', 'price-moderate', 'time-normal', 'period-lunch', 'period-dinner', 'temp-hot', 'season-all'],
    stats: { pickCount: 0, rejectCount: 0 },
    createdAt: FIXED_TIMESTAMP,
  },
  {
    id: 'demo-jp35',
    name: '抹茶冰淇淋',
    tags: ['cuisine-japanese', 'taste-sweet', 'taste-soft', 'type-dessert', 'price-budget', 'time-fast', 'period-snack', 'temp-cold', 'season-summer'],
    stats: { pickCount: 0, rejectCount: 0 },
    createdAt: FIXED_TIMESTAMP,
  },
]
