import { Dish } from '@/types'

const FIXED_TIMESTAMP = 1700000000000

export const KOREAN_DISHES: Dish[] = [
  {
    id: 'demo-kr1',
    name: '石锅拌饭',
    tags: ['cuisine-korean', 'taste-medium-spicy', 'taste-umami', 'taste-crispy', 'type-rice', 'price-moderate', 'time-normal', 'period-lunch', 'period-dinner', 'temp-hot', 'season-all'],
    stats: { pickCount: 0, rejectCount: 0 },
    createdAt: FIXED_TIMESTAMP,
  },
  {
    id: 'demo-kr2',
    name: '部队锅',
    tags: ['cuisine-korean', 'taste-medium-spicy', 'taste-heavy', 'taste-umami', 'type-hot', 'price-premium', 'time-slow', 'period-dinner', 'temp-hot', 'season-winter'],
    stats: { pickCount: 0, rejectCount: 0 },
    createdAt: FIXED_TIMESTAMP,
  },
  {
    id: 'demo-kr3',
    name: '炸鸡',
    tags: ['cuisine-korean', 'taste-crispy', 'taste-salty', 'type-snack', 'price-moderate', 'time-normal', 'period-dinner', 'period-snack', 'temp-hot', 'season-all'],
    stats: { pickCount: 0, rejectCount: 0 },
    createdAt: FIXED_TIMESTAMP,
  },
  {
    id: 'demo-kr4',
    name: '泡菜汤',
    tags: ['cuisine-korean', 'taste-medium-spicy', 'taste-sour', 'taste-umami', 'type-soup', 'price-moderate', 'time-normal', 'period-lunch', 'period-dinner', 'temp-hot', 'season-winter'],
    stats: { pickCount: 0, rejectCount: 0 },
    createdAt: FIXED_TIMESTAMP,
  },
  {
    id: 'demo-kr5',
    name: '冷面',
    tags: ['cuisine-korean', 'taste-sour', 'taste-light', 'taste-slurpy', 'type-noodles', 'price-moderate', 'time-fast', 'period-lunch', 'temp-cold', 'season-summer'],
    stats: { pickCount: 0, rejectCount: 0 },
    createdAt: FIXED_TIMESTAMP,
  },
  {
    id: 'demo-kr6',
    name: '烤肉',
    tags: ['cuisine-korean', 'taste-salty', 'taste-fragrant', 'taste-tender', 'type-hot', 'price-premium', 'time-slow', 'period-dinner', 'temp-hot', 'season-all'],
    stats: { pickCount: 0, rejectCount: 0 },
    createdAt: FIXED_TIMESTAMP,
  },
  {
    id: 'demo-kr7',
    name: '年糕',
    tags: ['cuisine-korean', 'taste-medium-spicy', 'taste-chewy', 'taste-sweet', 'type-snack', 'price-budget', 'time-fast', 'period-snack', 'temp-hot', 'season-all'],
    stats: { pickCount: 0, rejectCount: 0 },
    createdAt: FIXED_TIMESTAMP,
  },
  {
    id: 'demo-kr8',
    name: '参鸡汤',
    tags: ['cuisine-korean', 'taste-light', 'taste-umami', 'taste-tender', 'type-soup', 'price-premium', 'time-slow', 'period-lunch', 'period-dinner', 'temp-hot', 'season-winter'],
    stats: { pickCount: 0, rejectCount: 0 },
    createdAt: FIXED_TIMESTAMP,
  },
  {
    id: 'demo-kr9',
    name: '海鲜煎饼',
    tags: ['cuisine-korean', 'taste-crispy', 'taste-umami', 'taste-salty', 'type-snack', 'price-moderate', 'time-normal', 'period-lunch', 'period-snack', 'temp-hot', 'season-all'],
    stats: { pickCount: 0, rejectCount: 0 },
    createdAt: FIXED_TIMESTAMP,
  },
  {
    id: 'demo-kr10',
    name: '辣炒年糕',
    tags: ['cuisine-korean', 'taste-medium-spicy', 'taste-sweet', 'taste-chewy', 'type-snack', 'price-budget', 'time-fast', 'period-snack', 'period-lunch', 'temp-hot', 'season-all'],
    stats: { pickCount: 0, rejectCount: 0 },
    createdAt: FIXED_TIMESTAMP,
  },
  {
    id: 'demo-kr11',
    name: '大酱汤',
    tags: ['cuisine-korean', 'taste-salty', 'taste-umami', 'taste-light', 'type-soup', 'price-budget', 'time-normal', 'period-lunch', 'period-dinner', 'temp-hot', 'season-all'],
    stats: { pickCount: 0, rejectCount: 0 },
    createdAt: FIXED_TIMESTAMP,
  },
  {
    id: 'demo-kr12',
    name: '紫菜包饭',
    tags: ['cuisine-korean', 'taste-light', 'taste-fresh', 'taste-umami', 'type-staple', 'price-budget', 'time-fast', 'period-lunch', 'period-snack', 'temp-room', 'season-all'],
    stats: { pickCount: 0, rejectCount: 0 },
    createdAt: FIXED_TIMESTAMP,
  },
  {
    id: 'demo-kr13',
    name: '辣炒猪肉',
    tags: ['cuisine-korean', 'taste-medium-spicy', 'taste-salty', 'taste-tender', 'type-hot', 'price-moderate', 'time-normal', 'period-lunch', 'period-dinner', 'temp-hot', 'season-all'],
    stats: { pickCount: 0, rejectCount: 0 },
    createdAt: FIXED_TIMESTAMP,
  },
  {
    id: 'demo-kr14',
    name: '芝士玉米',
    tags: ['cuisine-korean', 'taste-sweet', 'taste-soft', 'taste-umami', 'type-snack', 'price-budget', 'time-fast', 'period-snack', 'temp-hot', 'season-all'],
    stats: { pickCount: 0, rejectCount: 0 },
    createdAt: FIXED_TIMESTAMP,
  },
  {
    id: 'demo-kr15',
    name: '韩式炸酱面',
    tags: ['cuisine-korean', 'taste-salty', 'taste-heavy', 'taste-chewy', 'type-noodles', 'price-moderate', 'time-normal', 'period-lunch', 'period-dinner', 'temp-hot', 'season-all'],
    stats: { pickCount: 0, rejectCount: 0 },
    createdAt: FIXED_TIMESTAMP,
  },
  {
    id: 'demo-kr16',
    name: '烤五花肉',
    tags: ['cuisine-korean', 'taste-salty', 'taste-fragrant', 'taste-crispy', 'type-hot', 'price-premium', 'time-slow', 'period-dinner', 'temp-hot', 'season-all'],
    stats: { pickCount: 0, rejectCount: 0 },
    createdAt: FIXED_TIMESTAMP,
  },
  {
    id: 'demo-kr17',
    name: '拌冷面',
    tags: ['cuisine-korean', 'taste-medium-spicy', 'taste-sour', 'taste-chewy', 'type-noodles', 'price-moderate', 'time-fast', 'period-lunch', 'temp-cold', 'season-summer'],
    stats: { pickCount: 0, rejectCount: 0 },
    createdAt: FIXED_TIMESTAMP,
  },
  {
    id: 'demo-kr18',
    name: '韩式烤鸡',
    tags: ['cuisine-korean', 'taste-sweet', 'taste-medium-spicy', 'taste-crispy', 'type-hot', 'price-moderate', 'time-normal', 'period-dinner', 'temp-hot', 'season-all'],
    stats: { pickCount: 0, rejectCount: 0 },
    createdAt: FIXED_TIMESTAMP,
  },
  {
    id: 'demo-kr19',
    name: '辣白菜炒饭',
    tags: ['cuisine-korean', 'taste-medium-spicy', 'taste-sour', 'taste-fragrant', 'type-rice', 'price-budget', 'time-fast', 'period-lunch', 'period-dinner', 'temp-hot', 'season-all'],
    stats: { pickCount: 0, rejectCount: 0 },
    createdAt: FIXED_TIMESTAMP,
  },
  {
    id: 'demo-kr20',
    name: '雪浓汤',
    tags: ['cuisine-korean', 'taste-light', 'taste-umami', 'taste-tender', 'type-soup', 'price-moderate', 'time-slow', 'period-lunch', 'period-dinner', 'temp-hot', 'season-winter'],
    stats: { pickCount: 0, rejectCount: 0 },
    createdAt: FIXED_TIMESTAMP,
  },
  {
    id: 'demo-kr21',
    name: '安东炖鸡',
    tags: ['cuisine-korean', 'taste-medium-spicy', 'taste-salty', 'taste-tender', 'type-hot', 'price-premium', 'time-slow', 'period-dinner', 'temp-hot', 'season-winter'],
    stats: { pickCount: 0, rejectCount: 0 },
    createdAt: FIXED_TIMESTAMP,
  },
  {
    id: 'demo-kr22',
    name: '猪蹄',
    tags: ['cuisine-korean', 'taste-salty', 'taste-tender', 'taste-chewy', 'type-hot', 'price-premium', 'time-slow', 'period-dinner', 'period-midnight', 'temp-hot', 'season-all'],
    stats: { pickCount: 0, rejectCount: 0 },
    createdAt: FIXED_TIMESTAMP,
  },
  {
    id: 'demo-kr23',
    name: '鱼饼汤',
    tags: ['cuisine-korean', 'taste-light', 'taste-umami', 'taste-chewy', 'type-soup', 'price-budget', 'time-fast', 'period-lunch', 'period-snack', 'temp-hot', 'season-winter'],
    stats: { pickCount: 0, rejectCount: 0 },
    createdAt: FIXED_TIMESTAMP,
  },
  {
    id: 'demo-kr24',
    name: '韩式拌饭',
    tags: ['cuisine-korean', 'taste-medium-spicy', 'taste-fresh', 'taste-umami', 'type-rice', 'price-moderate', 'time-normal', 'period-lunch', 'period-dinner', 'temp-hot', 'season-all'],
    stats: { pickCount: 0, rejectCount: 0 },
    createdAt: FIXED_TIMESTAMP,
  },
  {
    id: 'demo-kr25',
    name: '辣鸡爪',
    tags: ['cuisine-korean', 'taste-extra-spicy', 'taste-chewy', 'taste-heavy', 'type-snack', 'price-moderate', 'time-normal', 'period-midnight', 'period-snack', 'temp-hot', 'season-all'],
    stats: { pickCount: 0, rejectCount: 0 },
    createdAt: FIXED_TIMESTAMP,
  },
  {
    id: 'demo-kr26',
    name: '芝士排骨',
    tags: ['cuisine-korean', 'taste-salty', 'taste-heavy', 'taste-tender', 'type-hot', 'price-premium', 'time-slow', 'period-dinner', 'temp-hot', 'season-all'],
    stats: { pickCount: 0, rejectCount: 0 },
    createdAt: FIXED_TIMESTAMP,
  },
  {
    id: 'demo-kr27',
    name: '生菜包肉',
    tags: ['cuisine-korean', 'taste-fresh', 'taste-salty', 'taste-tender', 'type-hot', 'price-premium', 'time-normal', 'period-dinner', 'temp-hot', 'season-all'],
    stats: { pickCount: 0, rejectCount: 0 },
    createdAt: FIXED_TIMESTAMP,
  },
  {
    id: 'demo-kr28',
    name: '辣牛肉汤',
    tags: ['cuisine-korean', 'taste-medium-spicy', 'taste-umami', 'taste-heavy', 'type-soup', 'price-moderate', 'time-normal', 'period-lunch', 'period-dinner', 'temp-hot', 'season-winter'],
    stats: { pickCount: 0, rejectCount: 0 },
    createdAt: FIXED_TIMESTAMP,
  },
  {
    id: 'demo-kr29',
    name: '海鲜豆腐汤',
    tags: ['cuisine-korean', 'taste-medium-spicy', 'taste-umami', 'taste-soft', 'type-soup', 'price-moderate', 'time-normal', 'period-lunch', 'period-dinner', 'temp-hot', 'season-all'],
    stats: { pickCount: 0, rejectCount: 0 },
    createdAt: FIXED_TIMESTAMP,
  },
  {
    id: 'demo-kr30',
    name: '韩式炸鸡翅',
    tags: ['cuisine-korean', 'taste-sweet', 'taste-medium-spicy', 'taste-crispy', 'type-snack', 'price-moderate', 'time-normal', 'period-dinner', 'period-midnight', 'temp-hot', 'season-all'],
    stats: { pickCount: 0, rejectCount: 0 },
    createdAt: FIXED_TIMESTAMP,
  },
]
