import { Dish } from '@/types'

const FIXED_TIMESTAMP = 1700000000000

export const OTHER_DISHES: Dish[] = [
  // 小龙虾 cuisine-crayfish
  {
    id: 'demo-cf1',
    name: '麻辣小龙虾',
    tags: ['cuisine-crayfish', 'taste-mala', 'taste-extra-spicy', 'taste-heavy', 'type-hot', 'price-premium', 'time-slow', 'period-dinner', 'period-midnight', 'temp-hot', 'season-summer'],
    stats: { pickCount: 0, rejectCount: 0 },
    createdAt: FIXED_TIMESTAMP,
  },
  {
    id: 'demo-cf2',
    name: '蒜蓉小龙虾',
    tags: ['cuisine-crayfish', 'taste-fragrant', 'taste-heavy', 'taste-umami', 'type-hot', 'price-premium', 'time-slow', 'period-dinner', 'period-midnight', 'temp-hot', 'season-summer'],
    stats: { pickCount: 0, rejectCount: 0 },
    createdAt: FIXED_TIMESTAMP,
  },
  {
    id: 'demo-cf3',
    name: '十三香小龙虾',
    tags: ['cuisine-crayfish', 'taste-fragrant', 'taste-medium-spicy', 'taste-heavy', 'type-hot', 'price-premium', 'time-slow', 'period-dinner', 'period-midnight', 'temp-hot', 'season-summer'],
    stats: { pickCount: 0, rejectCount: 0 },
    createdAt: FIXED_TIMESTAMP,
  },
  {
    id: 'demo-cf4',
    name: '冰镇小龙虾',
    tags: ['cuisine-crayfish', 'taste-fresh', 'taste-light', 'taste-cold-dish', 'type-cold', 'price-premium', 'time-slow', 'period-dinner', 'period-midnight', 'temp-cold', 'season-summer'],
    stats: { pickCount: 0, rejectCount: 0 },
    createdAt: FIXED_TIMESTAMP,
  },
  {
    id: 'demo-cf5',
    name: '油焖小龙虾',
    tags: ['cuisine-crayfish', 'taste-sweet', 'taste-salty', 'taste-heavy', 'type-hot', 'price-premium', 'time-slow', 'period-dinner', 'period-midnight', 'temp-hot', 'season-summer'],
    stats: { pickCount: 0, rejectCount: 0 },
    createdAt: FIXED_TIMESTAMP,
  },
  {
    id: 'demo-cf6',
    name: '清蒸小龙虾',
    tags: ['cuisine-crayfish', 'taste-light', 'taste-umami', 'taste-fresh', 'type-hot', 'price-premium', 'time-normal', 'period-dinner', 'temp-hot', 'season-summer'],
    stats: { pickCount: 0, rejectCount: 0 },
    createdAt: FIXED_TIMESTAMP,
  },
  {
    id: 'demo-cf7',
    name: '咖喱小龙虾',
    tags: ['cuisine-crayfish', 'taste-medium-spicy', 'taste-fragrant', 'taste-heavy', 'type-hot', 'price-premium', 'time-slow', 'period-dinner', 'temp-hot', 'season-summer'],
    stats: { pickCount: 0, rejectCount: 0 },
    createdAt: FIXED_TIMESTAMP,
  },
  {
    id: 'demo-cf8',
    name: '泡椒小龙虾',
    tags: ['cuisine-crayfish', 'taste-medium-spicy', 'taste-sour', 'taste-heavy', 'type-hot', 'price-premium', 'time-slow', 'period-dinner', 'period-midnight', 'temp-hot', 'season-summer'],
    stats: { pickCount: 0, rejectCount: 0 },
    createdAt: FIXED_TIMESTAMP,
  },
  {
    id: 'demo-cf9',
    name: '芝士焗龙虾',
    tags: ['cuisine-crayfish', 'taste-heavy', 'taste-umami', 'taste-crispy', 'type-hot', 'price-luxury', 'time-slow', 'period-dinner', 'temp-hot', 'season-all'],
    stats: { pickCount: 0, rejectCount: 0 },
    createdAt: FIXED_TIMESTAMP,
  },
  {
    id: 'demo-cf10',
    name: '黑胡椒小龙虾',
    tags: ['cuisine-crayfish', 'taste-mild-spicy', 'taste-fragrant', 'taste-heavy', 'type-hot', 'price-premium', 'time-slow', 'period-dinner', 'period-midnight', 'temp-hot', 'season-summer'],
    stats: { pickCount: 0, rejectCount: 0 },
    createdAt: FIXED_TIMESTAMP,
  },

  // 甜品饮品 cuisine-dessert
  {
    id: 'demo-ds1',
    name: '珍珠奶茶',
    tags: ['cuisine-dessert', 'taste-sweet', 'taste-chewy', 'type-drink', 'price-budget', 'time-fast', 'period-snack', 'temp-cold', 'season-summer'],
    stats: { pickCount: 0, rejectCount: 0 },
    createdAt: FIXED_TIMESTAMP,
  },
  {
    id: 'demo-ds2',
    name: '杨枝甘露',
    tags: ['cuisine-dessert', 'taste-sweet', 'taste-fresh', 'type-dessert', 'price-moderate', 'time-fast', 'period-snack', 'temp-cold', 'season-summer'],
    stats: { pickCount: 0, rejectCount: 0 },
    createdAt: FIXED_TIMESTAMP,
  },
  {
    id: 'demo-ds3',
    name: '冰粉',
    tags: ['cuisine-dessert', 'taste-sweet', 'taste-fresh', 'taste-soft', 'type-dessert', 'price-budget', 'time-fast', 'period-snack', 'temp-cold', 'season-summer'],
    stats: { pickCount: 0, rejectCount: 0 },
    createdAt: FIXED_TIMESTAMP,
  },
  {
    id: 'demo-ds4',
    name: '红豆汤',
    tags: ['cuisine-dessert', 'taste-sweet', 'taste-soft', 'type-dessert', 'price-budget', 'time-normal', 'period-snack', 'temp-hot', 'season-winter'],
    stats: { pickCount: 0, rejectCount: 0 },
    createdAt: FIXED_TIMESTAMP,
  },
  {
    id: 'demo-ds5',
    name: '绿豆汤',
    tags: ['cuisine-dessert', 'taste-sweet', 'taste-light', 'taste-fresh', 'type-dessert', 'price-budget', 'time-normal', 'period-snack', 'temp-cold', 'season-summer'],
    stats: { pickCount: 0, rejectCount: 0 },
    createdAt: FIXED_TIMESTAMP,
  },
  {
    id: 'demo-ds6',
    name: '椰汁西米露',
    tags: ['cuisine-dessert', 'taste-sweet', 'taste-soft', 'taste-fragrant', 'type-dessert', 'price-budget', 'time-fast', 'period-snack', 'temp-cold', 'season-summer'],
    stats: { pickCount: 0, rejectCount: 0 },
    createdAt: FIXED_TIMESTAMP,
  },
  {
    id: 'demo-ds7',
    name: '芒果班戟',
    tags: ['cuisine-dessert', 'taste-sweet', 'taste-fresh', 'taste-soft', 'type-dessert', 'price-moderate', 'time-fast', 'period-snack', 'temp-cold', 'season-summer'],
    stats: { pickCount: 0, rejectCount: 0 },
    createdAt: FIXED_TIMESTAMP,
  },
  {
    id: 'demo-ds8',
    name: '草莓蛋糕',
    tags: ['cuisine-dessert', 'taste-sweet', 'taste-fresh', 'taste-soft', 'type-dessert', 'price-moderate', 'time-fast', 'period-snack', 'temp-cold', 'season-all'],
    stats: { pickCount: 0, rejectCount: 0 },
    createdAt: FIXED_TIMESTAMP,
  },
  {
    id: 'demo-ds9',
    name: '冰淇淋',
    tags: ['cuisine-dessert', 'taste-sweet', 'taste-soft', 'type-dessert', 'price-budget', 'time-fast', 'period-snack', 'temp-cold', 'season-summer'],
    stats: { pickCount: 0, rejectCount: 0 },
    createdAt: FIXED_TIMESTAMP,
  },
  {
    id: 'demo-ds10',
    name: '酸奶',
    tags: ['cuisine-dessert', 'taste-sour', 'taste-fresh', 'taste-light', 'type-drink', 'price-budget', 'time-fast', 'period-breakfast', 'period-snack', 'temp-cold', 'season-all'],
    stats: { pickCount: 0, rejectCount: 0 },
    createdAt: FIXED_TIMESTAMP,
  },
  {
    id: 'demo-ds11',
    name: '水果捞',
    tags: ['cuisine-dessert', 'taste-sweet', 'taste-fresh', 'type-dessert', 'price-moderate', 'time-fast', 'period-snack', 'temp-cold', 'season-summer'],
    stats: { pickCount: 0, rejectCount: 0 },
    createdAt: FIXED_TIMESTAMP,
  },
  {
    id: 'demo-ds12',
    name: '豆花',
    tags: ['cuisine-dessert', 'taste-sweet', 'taste-soft', 'taste-light', 'type-dessert', 'price-budget', 'time-fast', 'period-breakfast', 'period-snack', 'temp-hot', 'season-all'],
    stats: { pickCount: 0, rejectCount: 0 },
    createdAt: FIXED_TIMESTAMP,
  },
  {
    id: 'demo-ds13',
    name: '烧仙草',
    tags: ['cuisine-dessert', 'taste-sweet', 'taste-soft', 'taste-fresh', 'type-dessert', 'price-budget', 'time-fast', 'period-snack', 'temp-cold', 'season-summer'],
    stats: { pickCount: 0, rejectCount: 0 },
    createdAt: FIXED_TIMESTAMP,
  },
  {
    id: 'demo-ds14',
    name: '芋圆',
    tags: ['cuisine-dessert', 'taste-sweet', 'taste-chewy', 'taste-soft', 'type-dessert', 'price-budget', 'time-fast', 'period-snack', 'temp-hot', 'season-all'],
    stats: { pickCount: 0, rejectCount: 0 },
    createdAt: FIXED_TIMESTAMP,
  },
  {
    id: 'demo-ds15',
    name: '奶盖茶',
    tags: ['cuisine-dessert', 'taste-sweet', 'taste-light', 'type-drink', 'price-moderate', 'time-fast', 'period-snack', 'temp-cold', 'season-all'],
    stats: { pickCount: 0, rejectCount: 0 },
    createdAt: FIXED_TIMESTAMP,
  },
  {
    id: 'demo-ds16',
    name: '鲜榨果汁',
    tags: ['cuisine-dessert', 'taste-sweet', 'taste-fresh', 'taste-sour', 'type-drink', 'price-moderate', 'time-fast', 'period-snack', 'period-breakfast', 'temp-cold', 'season-summer'],
    stats: { pickCount: 0, rejectCount: 0 },
    createdAt: FIXED_TIMESTAMP,
  },
  {
    id: 'demo-ds17',
    name: '酸梅汤',
    tags: ['cuisine-dessert', 'taste-sour-sweet', 'taste-fresh', 'type-drink', 'price-budget', 'time-fast', 'period-snack', 'period-lunch', 'temp-cold', 'season-summer'],
    stats: { pickCount: 0, rejectCount: 0 },
    createdAt: FIXED_TIMESTAMP,
  },
  {
    id: 'demo-ds18',
    name: '桃胶银耳汤',
    tags: ['cuisine-dessert', 'taste-sweet', 'taste-soft', 'taste-light', 'type-dessert', 'price-moderate', 'time-slow', 'period-snack', 'temp-hot', 'season-autumn'],
    stats: { pickCount: 0, rejectCount: 0 },
    createdAt: FIXED_TIMESTAMP,
  },
  {
    id: 'demo-ds19',
    name: '红枣银耳汤',
    tags: ['cuisine-dessert', 'taste-sweet', 'taste-soft', 'taste-light', 'type-dessert', 'price-budget', 'time-slow', 'period-snack', 'temp-hot', 'season-winter'],
    stats: { pickCount: 0, rejectCount: 0 },
    createdAt: FIXED_TIMESTAMP,
  },
  {
    id: 'demo-ds20',
    name: '蜂蜜柚子茶',
    tags: ['cuisine-dessert', 'taste-sweet', 'taste-sour', 'taste-fresh', 'type-drink', 'price-budget', 'time-fast', 'period-snack', 'temp-hot', 'season-winter'],
    stats: { pickCount: 0, rejectCount: 0 },
    createdAt: FIXED_TIMESTAMP,
  },
]
