import { Dish } from '@/types'

const FIXED_TIMESTAMP = 1700000000000

export const REGIONAL_DISHES: Dish[] = [
  // ===== 鲁菜 (Shandong) =====
  {
    id: 'demo-sd1',
    name: '糖醋鲤鱼',
    tags: ['cuisine-shandong', 'taste-sour-sweet', 'taste-crispy', 'taste-tender', 'type-hot', 'price-premium', 'time-slow', 'period-dinner', 'temp-hot', 'season-all'],
    stats: { pickCount: 0, rejectCount: 0 },
    createdAt: FIXED_TIMESTAMP,
  },
  {
    id: 'demo-sd2',
    name: '九转大肠',
    tags: ['cuisine-shandong', 'taste-salty', 'taste-sweet', 'taste-chewy', 'type-hot', 'price-premium', 'time-slow', 'period-dinner', 'temp-hot', 'season-all'],
    stats: { pickCount: 0, rejectCount: 0 },
    createdAt: FIXED_TIMESTAMP,
  },
  {
    id: 'demo-sd3',
    name: '葱烧海参',
    tags: ['cuisine-shandong', 'taste-light', 'taste-umami', 'taste-soft', 'type-hot', 'price-luxury', 'time-slow', 'period-dinner', 'temp-hot', 'season-all'],
    stats: { pickCount: 0, rejectCount: 0 },
    createdAt: FIXED_TIMESTAMP,
  },
  {
    id: 'demo-sd4',
    name: '拔丝地瓜',
    tags: ['cuisine-shandong', 'taste-sweet', 'taste-crispy', 'type-dessert', 'price-budget', 'time-normal', 'period-lunch', 'period-dinner', 'temp-hot', 'season-all'],
    stats: { pickCount: 0, rejectCount: 0 },
    createdAt: FIXED_TIMESTAMP,
  },
  {
    id: 'demo-sd5',
    name: '锅塌豆腐',
    tags: ['cuisine-shandong', 'taste-salty', 'taste-umami', 'taste-tender', 'type-hot', 'price-budget', 'time-normal', 'period-lunch', 'period-dinner', 'temp-hot', 'season-all'],
    stats: { pickCount: 0, rejectCount: 0 },
    createdAt: FIXED_TIMESTAMP,
  },
  {
    id: 'demo-sd6',
    name: '奶汤蒲菜',
    tags: ['cuisine-shandong', 'taste-light', 'taste-umami', 'taste-fresh', 'type-soup', 'price-moderate', 'time-normal', 'period-dinner', 'temp-hot', 'season-spring'],
    stats: { pickCount: 0, rejectCount: 0 },
    createdAt: FIXED_TIMESTAMP,
  },
  {
    id: 'demo-sd7',
    name: '油焖大虾',
    tags: ['cuisine-shandong', 'taste-salty', 'taste-sweet', 'taste-umami', 'type-hot', 'price-premium', 'time-normal', 'period-dinner', 'temp-hot', 'season-all'],
    stats: { pickCount: 0, rejectCount: 0 },
    createdAt: FIXED_TIMESTAMP,
  },
  {
    id: 'demo-sd8',
    name: '德州扒鸡',
    tags: ['cuisine-shandong', 'taste-salty', 'taste-fragrant', 'taste-tender', 'type-hot', 'price-moderate', 'time-slow', 'period-lunch', 'period-dinner', 'temp-hot', 'season-all'],
    stats: { pickCount: 0, rejectCount: 0 },
    createdAt: FIXED_TIMESTAMP,
  },
  {
    id: 'demo-sd9',
    name: '四喜丸子',
    tags: ['cuisine-shandong', 'taste-salty', 'taste-tender', 'taste-umami', 'type-hot', 'price-moderate', 'time-slow', 'period-dinner', 'temp-hot', 'season-winter'],
    stats: { pickCount: 0, rejectCount: 0 },
    createdAt: FIXED_TIMESTAMP,
  },
  {
    id: 'demo-sd10',
    name: '爆炒腰花',
    tags: ['cuisine-shandong', 'taste-salty', 'taste-fragrant', 'taste-crispy', 'type-hot', 'price-moderate', 'time-fast', 'period-dinner', 'temp-hot', 'season-all'],
    stats: { pickCount: 0, rejectCount: 0 },
    createdAt: FIXED_TIMESTAMP,
  },
  {
    id: 'demo-sd11',
    name: '蒜蓉粉丝蒸扇贝',
    tags: ['cuisine-shandong', 'taste-light', 'taste-umami', 'taste-fresh', 'type-hot', 'price-moderate', 'time-normal', 'period-dinner', 'temp-hot', 'season-all'],
    stats: { pickCount: 0, rejectCount: 0 },
    createdAt: FIXED_TIMESTAMP,
  },
  {
    id: 'demo-sd12',
    name: '红烧黄河鲤',
    tags: ['cuisine-shandong', 'taste-salty', 'taste-umami', 'taste-tender', 'type-hot', 'price-premium', 'time-slow', 'period-dinner', 'temp-hot', 'season-all'],
    stats: { pickCount: 0, rejectCount: 0 },
    createdAt: FIXED_TIMESTAMP,
  },
  {
    id: 'demo-sd13',
    name: '孔府豆腐',
    tags: ['cuisine-shandong', 'taste-light', 'taste-umami', 'taste-tender', 'type-hot', 'price-moderate', 'time-normal', 'period-lunch', 'period-dinner', 'temp-hot', 'season-all'],
    stats: { pickCount: 0, rejectCount: 0 },
    createdAt: FIXED_TIMESTAMP,
  },
  {
    id: 'demo-sd14',
    name: '三丝鱼翅',
    tags: ['cuisine-shandong', 'taste-light', 'taste-umami', 'taste-fresh', 'type-soup', 'price-luxury', 'time-slow', 'period-dinner', 'temp-hot', 'season-all'],
    stats: { pickCount: 0, rejectCount: 0 },
    createdAt: FIXED_TIMESTAMP,
  },
  {
    id: 'demo-sd15',
    name: '芙蓉鸡片',
    tags: ['cuisine-shandong', 'taste-light', 'taste-tender', 'taste-umami', 'type-hot', 'price-moderate', 'time-normal', 'period-lunch', 'period-dinner', 'temp-hot', 'season-all'],
    stats: { pickCount: 0, rejectCount: 0 },
    createdAt: FIXED_TIMESTAMP,
  },
  {
    id: 'demo-sd16',
    name: '烩乌鱼蛋',
    tags: ['cuisine-shandong', 'taste-sour', 'taste-umami', 'taste-slurpy', 'type-soup', 'price-premium', 'time-normal', 'period-dinner', 'temp-hot', 'season-all'],
    stats: { pickCount: 0, rejectCount: 0 },
    createdAt: FIXED_TIMESTAMP,
  },
  {
    id: 'demo-sd17',
    name: '红烧肘子',
    tags: ['cuisine-shandong', 'taste-salty', 'taste-heavy', 'taste-soft', 'type-hot', 'price-premium', 'time-slow', 'period-dinner', 'temp-hot', 'season-winter'],
    stats: { pickCount: 0, rejectCount: 0 },
    createdAt: FIXED_TIMESTAMP,
  },
  {
    id: 'demo-sd18',
    name: '糖醋排骨',
    tags: ['cuisine-shandong', 'taste-sour-sweet', 'taste-crispy', 'taste-tender', 'type-hot', 'price-moderate', 'time-normal', 'period-lunch', 'period-dinner', 'temp-hot', 'season-all'],
    stats: { pickCount: 0, rejectCount: 0 },
    createdAt: FIXED_TIMESTAMP,
  },
  {
    id: 'demo-sd19',
    name: '扒鸡',
    tags: ['cuisine-shandong', 'taste-salty', 'taste-fragrant', 'taste-tender', 'type-hot', 'price-moderate', 'time-slow', 'period-lunch', 'period-dinner', 'temp-hot', 'season-all'],
    stats: { pickCount: 0, rejectCount: 0 },
    createdAt: FIXED_TIMESTAMP,
  },
  {
    id: 'demo-sd20',
    name: '辣炒蛤蜊',
    tags: ['cuisine-shandong', 'taste-mild-spicy', 'taste-umami', 'taste-fresh', 'type-hot', 'price-moderate', 'time-fast', 'period-dinner', 'period-midnight', 'temp-hot', 'season-summer'],
    stats: { pickCount: 0, rejectCount: 0 },
    createdAt: FIXED_TIMESTAMP,
  },

  // ===== 苏菜 (Jiangsu) =====
  {
    id: 'demo-js1',
    name: '松鼠鳜鱼',
    tags: ['cuisine-jiangsu', 'taste-sour-sweet', 'taste-crispy', 'taste-tender', 'type-hot', 'price-luxury', 'time-slow', 'period-dinner', 'temp-hot', 'season-all'],
    stats: { pickCount: 0, rejectCount: 0 },
    createdAt: FIXED_TIMESTAMP,
  },
  {
    id: 'demo-js2',
    name: '红烧狮子头',
    tags: ['cuisine-jiangsu', 'taste-salty', 'taste-tender', 'taste-heavy', 'type-hot', 'price-premium', 'time-slow', 'period-dinner', 'temp-hot', 'season-winter'],
    stats: { pickCount: 0, rejectCount: 0 },
    createdAt: FIXED_TIMESTAMP,
  },
  {
    id: 'demo-js3',
    name: '大煮干丝',
    tags: ['cuisine-jiangsu', 'taste-light', 'taste-umami', 'taste-soft', 'type-hot', 'price-moderate', 'time-normal', 'period-lunch', 'temp-hot', 'season-all'],
    stats: { pickCount: 0, rejectCount: 0 },
    createdAt: FIXED_TIMESTAMP,
  },
  {
    id: 'demo-js4',
    name: '盐水鸭',
    tags: ['cuisine-jiangsu', 'taste-salty', 'taste-light', 'taste-tender', 'type-cold', 'price-moderate', 'time-fast', 'period-lunch', 'period-dinner', 'temp-cold', 'season-all'],
    stats: { pickCount: 0, rejectCount: 0 },
    createdAt: FIXED_TIMESTAMP,
  },
  {
    id: 'demo-js5',
    name: '文思豆腐',
    tags: ['cuisine-jiangsu', 'taste-light', 'taste-umami', 'taste-tender', 'type-soup', 'price-premium', 'time-slow', 'period-dinner', 'temp-hot', 'season-all'],
    stats: { pickCount: 0, rejectCount: 0 },
    createdAt: FIXED_TIMESTAMP,
  },
  {
    id: 'demo-js6',
    name: '蟹粉豆腐',
    tags: ['cuisine-jiangsu', 'taste-umami', 'taste-tender', 'taste-fresh', 'type-hot', 'price-premium', 'time-normal', 'period-dinner', 'temp-hot', 'season-autumn'],
    stats: { pickCount: 0, rejectCount: 0 },
    createdAt: FIXED_TIMESTAMP,
  },
  {
    id: 'demo-js7',
    name: '无锡排骨',
    tags: ['cuisine-jiangsu', 'taste-sweet', 'taste-salty', 'taste-tender', 'type-hot', 'price-moderate', 'time-slow', 'period-lunch', 'period-dinner', 'temp-hot', 'season-all'],
    stats: { pickCount: 0, rejectCount: 0 },
    createdAt: FIXED_TIMESTAMP,
  },
  {
    id: 'demo-js8',
    name: '清炖蟹粉狮子头',
    tags: ['cuisine-jiangsu', 'taste-light', 'taste-umami', 'taste-tender', 'type-soup', 'price-luxury', 'time-slow', 'period-dinner', 'temp-hot', 'season-autumn'],
    stats: { pickCount: 0, rejectCount: 0 },
    createdAt: FIXED_TIMESTAMP,
  },
  {
    id: 'demo-js9',
    name: '水晶肴肉',
    tags: ['cuisine-jiangsu', 'taste-salty', 'taste-light', 'taste-cold-dish', 'type-cold', 'price-moderate', 'time-fast', 'period-lunch', 'period-dinner', 'temp-cold', 'season-summer'],
    stats: { pickCount: 0, rejectCount: 0 },
    createdAt: FIXED_TIMESTAMP,
  },
  {
    id: 'demo-js10',
    name: '如意响铃',
    tags: ['cuisine-jiangsu', 'taste-crispy', 'taste-light', 'taste-fragrant', 'type-hot', 'price-moderate', 'time-normal', 'period-dinner', 'temp-hot', 'season-all'],
    stats: { pickCount: 0, rejectCount: 0 },
    createdAt: FIXED_TIMESTAMP,
  },
  {
    id: 'demo-js11',
    name: '三套鸭',
    tags: ['cuisine-jiangsu', 'taste-light', 'taste-umami', 'taste-tender', 'type-hot', 'price-luxury', 'time-slow', 'period-dinner', 'temp-hot', 'season-winter'],
    stats: { pickCount: 0, rejectCount: 0 },
    createdAt: FIXED_TIMESTAMP,
  },
  {
    id: 'demo-js12',
    name: '拆烩鲢鱼头',
    tags: ['cuisine-jiangsu', 'taste-light', 'taste-umami', 'taste-tender', 'type-soup', 'price-premium', 'time-slow', 'period-dinner', 'temp-hot', 'season-winter'],
    stats: { pickCount: 0, rejectCount: 0 },
    createdAt: FIXED_TIMESTAMP,
  },
  {
    id: 'demo-js13',
    name: '糖醋桂鱼',
    tags: ['cuisine-jiangsu', 'taste-sour-sweet', 'taste-crispy', 'taste-tender', 'type-hot', 'price-premium', 'time-slow', 'period-dinner', 'temp-hot', 'season-all'],
    stats: { pickCount: 0, rejectCount: 0 },
    createdAt: FIXED_TIMESTAMP,
  },
  {
    id: 'demo-js14',
    name: '蟹黄汤包',
    tags: ['cuisine-jiangsu', 'taste-umami', 'taste-fresh', 'taste-tender', 'type-dimsum', 'price-premium', 'time-normal', 'period-breakfast', 'period-lunch', 'temp-hot', 'season-autumn'],
    stats: { pickCount: 0, rejectCount: 0 },
    createdAt: FIXED_TIMESTAMP,
  },
  {
    id: 'demo-js15',
    name: '鸭血粉丝汤',
    tags: ['cuisine-jiangsu', 'taste-light', 'taste-umami', 'taste-slurpy', 'type-noodles', 'price-budget', 'time-fast', 'period-lunch', 'period-snack', 'temp-hot', 'season-all'],
    stats: { pickCount: 0, rejectCount: 0 },
    createdAt: FIXED_TIMESTAMP,
  },
  {
    id: 'demo-js16',
    name: '桂花糖芋苗',
    tags: ['cuisine-jiangsu', 'taste-sweet', 'taste-soft', 'taste-fragrant', 'type-dessert', 'price-budget', 'time-fast', 'period-snack', 'temp-hot', 'season-autumn'],
    stats: { pickCount: 0, rejectCount: 0 },
    createdAt: FIXED_TIMESTAMP,
  },
  {
    id: 'demo-js17',
    name: '扬州炒饭',
    tags: ['cuisine-jiangsu', 'taste-salty', 'taste-fragrant', 'taste-umami', 'type-rice', 'price-budget', 'time-fast', 'period-lunch', 'period-dinner', 'temp-hot', 'season-all'],
    stats: { pickCount: 0, rejectCount: 0 },
    createdAt: FIXED_TIMESTAMP,
  },
  {
    id: 'demo-js18',
    name: '金陵盐水鸭',
    tags: ['cuisine-jiangsu', 'taste-salty', 'taste-light', 'taste-tender', 'type-cold', 'price-moderate', 'time-fast', 'period-lunch', 'period-dinner', 'temp-cold', 'season-all'],
    stats: { pickCount: 0, rejectCount: 0 },
    createdAt: FIXED_TIMESTAMP,
  },

  // ===== 浙菜 (Zhejiang) =====
  {
    id: 'demo-zj1',
    name: '东坡肉',
    tags: ['cuisine-zhejiang', 'taste-sweet', 'taste-salty', 'taste-tender', 'taste-heavy', 'type-hot', 'price-premium', 'time-slow', 'period-dinner', 'temp-hot', 'season-all'],
    stats: { pickCount: 0, rejectCount: 0 },
    createdAt: FIXED_TIMESTAMP,
  },
  {
    id: 'demo-zj2',
    name: '西湖醋鱼',
    tags: ['cuisine-zhejiang', 'taste-sour-sweet', 'taste-tender', 'taste-umami', 'taste-fresh', 'type-hot', 'price-premium', 'time-slow', 'period-dinner', 'temp-hot', 'season-all'],
    stats: { pickCount: 0, rejectCount: 0 },
    createdAt: FIXED_TIMESTAMP,
  },
  {
    id: 'demo-zj3',
    name: '龙井虾仁',
    tags: ['cuisine-zhejiang', 'taste-light', 'taste-umami', 'taste-fresh', 'type-hot', 'price-premium', 'time-normal', 'period-dinner', 'temp-hot', 'season-spring'],
    stats: { pickCount: 0, rejectCount: 0 },
    createdAt: FIXED_TIMESTAMP,
  },
  {
    id: 'demo-zj4',
    name: '叫花鸡',
    tags: ['cuisine-zhejiang', 'taste-salty', 'taste-fragrant', 'taste-tender', 'type-hot', 'price-premium', 'time-slow', 'period-dinner', 'temp-hot', 'season-all'],
    stats: { pickCount: 0, rejectCount: 0 },
    createdAt: FIXED_TIMESTAMP,
  },
  {
    id: 'demo-zj5',
    name: '宋嫂鱼羹',
    tags: ['cuisine-zhejiang', 'taste-sour', 'taste-umami', 'taste-slurpy', 'type-soup', 'price-moderate', 'time-normal', 'period-lunch', 'period-dinner', 'temp-hot', 'season-all'],
    stats: { pickCount: 0, rejectCount: 0 },
    createdAt: FIXED_TIMESTAMP,
  },
  {
    id: 'demo-zj6',
    name: '油焖笋',
    tags: ['cuisine-zhejiang', 'taste-salty', 'taste-sweet', 'taste-fresh', 'type-hot', 'price-moderate', 'time-normal', 'period-lunch', 'period-dinner', 'temp-hot', 'season-spring'],
    stats: { pickCount: 0, rejectCount: 0 },
    createdAt: FIXED_TIMESTAMP,
  },
  {
    id: 'demo-zj7',
    name: '干炸响铃',
    tags: ['cuisine-zhejiang', 'taste-crispy', 'taste-fragrant', 'taste-light', 'type-snack', 'price-moderate', 'time-fast', 'period-lunch', 'period-dinner', 'temp-hot', 'season-all'],
    stats: { pickCount: 0, rejectCount: 0 },
    createdAt: FIXED_TIMESTAMP,
  },
  {
    id: 'demo-zj8',
    name: '荷叶粉蒸鸡',
    tags: ['cuisine-zhejiang', 'taste-light', 'taste-fragrant', 'taste-tender', 'type-hot', 'price-moderate', 'time-slow', 'period-dinner', 'temp-hot', 'season-summer'],
    stats: { pickCount: 0, rejectCount: 0 },
    createdAt: FIXED_TIMESTAMP,
  },
  {
    id: 'demo-zj9',
    name: '绍兴醉鸡',
    tags: ['cuisine-zhejiang', 'taste-light', 'taste-fragrant', 'taste-cold-dish', 'type-cold', 'price-moderate', 'time-normal', 'period-lunch', 'period-dinner', 'temp-cold', 'season-summer'],
    stats: { pickCount: 0, rejectCount: 0 },
    createdAt: FIXED_TIMESTAMP,
  },
  {
    id: 'demo-zj10',
    name: '片儿川',
    tags: ['cuisine-zhejiang', 'taste-salty', 'taste-umami', 'taste-slurpy', 'type-noodles', 'price-budget', 'time-fast', 'period-breakfast', 'period-lunch', 'temp-hot', 'season-all'],
    stats: { pickCount: 0, rejectCount: 0 },
    createdAt: FIXED_TIMESTAMP,
  },
  {
    id: 'demo-zj11',
    name: '虾爆鳝面',
    tags: ['cuisine-zhejiang', 'taste-salty', 'taste-umami', 'taste-chewy', 'type-noodles', 'price-moderate', 'time-normal', 'period-lunch', 'temp-hot', 'season-all'],
    stats: { pickCount: 0, rejectCount: 0 },
    createdAt: FIXED_TIMESTAMP,
  },
  {
    id: 'demo-zj12',
    name: '西湖牛肉羹',
    tags: ['cuisine-zhejiang', 'taste-light', 'taste-umami', 'taste-slurpy', 'type-soup', 'price-moderate', 'time-normal', 'period-lunch', 'period-dinner', 'temp-hot', 'season-all'],
    stats: { pickCount: 0, rejectCount: 0 },
    createdAt: FIXED_TIMESTAMP,
  },
  {
    id: 'demo-zj13',
    name: '杭州小笼',
    tags: ['cuisine-zhejiang', 'taste-light', 'taste-umami', 'taste-tender', 'type-dimsum', 'price-budget', 'time-fast', 'period-breakfast', 'period-lunch', 'temp-hot', 'season-all'],
    stats: { pickCount: 0, rejectCount: 0 },
    createdAt: FIXED_TIMESTAMP,
  },
  {
    id: 'demo-zj14',
    name: '知味小笼',
    tags: ['cuisine-zhejiang', 'taste-sweet', 'taste-umami', 'taste-tender', 'type-dimsum', 'price-budget', 'time-fast', 'period-breakfast', 'period-lunch', 'temp-hot', 'season-all'],
    stats: { pickCount: 0, rejectCount: 0 },
    createdAt: FIXED_TIMESTAMP,
  },
  {
    id: 'demo-zj15',
    name: '油条',
    tags: ['cuisine-zhejiang', 'taste-crispy', 'taste-light', 'type-snack', 'price-budget', 'time-fast', 'period-breakfast', 'temp-hot', 'season-all'],
    stats: { pickCount: 0, rejectCount: 0 },
    createdAt: FIXED_TIMESTAMP,
  },
  {
    id: 'demo-zj16',
    name: '定胜糕',
    tags: ['cuisine-zhejiang', 'taste-sweet', 'taste-soft', 'type-dimsum', 'price-budget', 'time-fast', 'period-snack', 'temp-room', 'season-all'],
    stats: { pickCount: 0, rejectCount: 0 },
    createdAt: FIXED_TIMESTAMP,
  },
  {
    id: 'demo-zj17',
    name: '梅干菜扣肉',
    tags: ['cuisine-zhejiang', 'taste-salty', 'taste-heavy', 'taste-tender', 'type-hot', 'price-moderate', 'time-slow', 'period-lunch', 'period-dinner', 'temp-hot', 'season-all'],
    stats: { pickCount: 0, rejectCount: 0 },
    createdAt: FIXED_TIMESTAMP,
  },
  {
    id: 'demo-zj18',
    name: '红烧肉',
    tags: ['cuisine-zhejiang', 'taste-salty', 'taste-sweet', 'taste-tender', 'taste-heavy', 'type-hot', 'price-moderate', 'time-slow', 'period-dinner', 'temp-hot', 'season-winter'],
    stats: { pickCount: 0, rejectCount: 0 },
    createdAt: FIXED_TIMESTAMP,
  },

  // ===== 闽菜 (Fujian) =====
  {
    id: 'demo-fj1',
    name: '佛跳墙',
    tags: ['cuisine-fujian', 'taste-umami', 'taste-light', 'taste-fresh', 'type-soup', 'price-luxury', 'time-slow', 'period-dinner', 'temp-hot', 'season-winter'],
    stats: { pickCount: 0, rejectCount: 0 },
    createdAt: FIXED_TIMESTAMP,
  },
  {
    id: 'demo-fj2',
    name: '荔枝肉',
    tags: ['cuisine-fujian', 'taste-sour-sweet', 'taste-crispy', 'taste-tender', 'type-hot', 'price-moderate', 'time-normal', 'period-lunch', 'period-dinner', 'temp-hot', 'season-all'],
    stats: { pickCount: 0, rejectCount: 0 },
    createdAt: FIXED_TIMESTAMP,
  },
  {
    id: 'demo-fj3',
    name: '醉排骨',
    tags: ['cuisine-fujian', 'taste-sour-sweet', 'taste-crispy', 'taste-fragrant', 'type-hot', 'price-moderate', 'time-normal', 'period-lunch', 'period-dinner', 'temp-hot', 'season-all'],
    stats: { pickCount: 0, rejectCount: 0 },
    createdAt: FIXED_TIMESTAMP,
  },
  {
    id: 'demo-fj4',
    name: '沙县拌面',
    tags: ['cuisine-fujian', 'taste-salty', 'taste-fragrant', 'taste-chewy', 'type-noodles', 'price-budget', 'time-fast', 'period-breakfast', 'period-lunch', 'temp-hot', 'season-all'],
    stats: { pickCount: 0, rejectCount: 0 },
    createdAt: FIXED_TIMESTAMP,
  },
  {
    id: 'demo-fj5',
    name: '沙县扁肉',
    tags: ['cuisine-fujian', 'taste-light', 'taste-umami', 'taste-tender', 'type-soup', 'price-budget', 'time-fast', 'period-breakfast', 'period-lunch', 'temp-hot', 'season-all'],
    stats: { pickCount: 0, rejectCount: 0 },
    createdAt: FIXED_TIMESTAMP,
  },
  {
    id: 'demo-fj6',
    name: '海蛎煎',
    tags: ['cuisine-fujian', 'taste-umami', 'taste-crispy', 'taste-fresh', 'type-snack', 'price-budget', 'time-fast', 'period-lunch', 'period-midnight', 'temp-hot', 'season-all'],
    stats: { pickCount: 0, rejectCount: 0 },
    createdAt: FIXED_TIMESTAMP,
  },

  // ===== 徽菜 (Anhui) =====
  {
    id: 'demo-ah1',
    name: '臭鳜鱼',
    tags: ['cuisine-anhui', 'taste-salty', 'taste-umami', 'taste-tender', 'type-hot', 'price-premium', 'time-slow', 'period-dinner', 'temp-hot', 'season-all'],
    stats: { pickCount: 0, rejectCount: 0 },
    createdAt: FIXED_TIMESTAMP,
  },
  {
    id: 'demo-ah2',
    name: '毛豆腐',
    tags: ['cuisine-anhui', 'taste-salty', 'taste-soft', 'taste-fragrant', 'type-hot', 'price-moderate', 'time-normal', 'period-snack', 'period-dinner', 'temp-hot', 'season-all'],
    stats: { pickCount: 0, rejectCount: 0 },
    createdAt: FIXED_TIMESTAMP,
  },
  {
    id: 'demo-ah3',
    name: '符离集烧鸡',
    tags: ['cuisine-anhui', 'taste-salty', 'taste-fragrant', 'taste-tender', 'type-hot', 'price-moderate', 'time-slow', 'period-lunch', 'period-dinner', 'temp-hot', 'season-all'],
    stats: { pickCount: 0, rejectCount: 0 },
    createdAt: FIXED_TIMESTAMP,
  },
  {
    id: 'demo-ah4',
    name: '笋干烧肉',
    tags: ['cuisine-anhui', 'taste-salty', 'taste-umami', 'taste-tender', 'type-hot', 'price-moderate', 'time-slow', 'period-lunch', 'period-dinner', 'temp-hot', 'season-spring'],
    stats: { pickCount: 0, rejectCount: 0 },
    createdAt: FIXED_TIMESTAMP,
  },
  {
    id: 'demo-ah5',
    name: '火腿炖甲鱼',
    tags: ['cuisine-anhui', 'taste-umami', 'taste-light', 'taste-tender', 'type-soup', 'price-luxury', 'time-slow', 'period-dinner', 'temp-hot', 'season-winter'],
    stats: { pickCount: 0, rejectCount: 0 },
    createdAt: FIXED_TIMESTAMP,
  },
  {
    id: 'demo-ah6',
    name: '问政山笋',
    tags: ['cuisine-anhui', 'taste-light', 'taste-fresh', 'taste-umami', 'type-hot', 'price-moderate', 'time-normal', 'period-lunch', 'period-dinner', 'temp-hot', 'season-spring'],
    stats: { pickCount: 0, rejectCount: 0 },
    createdAt: FIXED_TIMESTAMP,
  },
]
