import { Dish } from '@/types'

const FIXED_TIMESTAMP = 1700000000000

export const SICHUAN_DISHES: Dish[] = [
  {
    id: 'demo-s1',
    name: '宫保鸡丁',
    tags: ['cuisine-sichuan', 'taste-medium-spicy', 'taste-sour-sweet', 'taste-crispy', 'type-hot', 'price-moderate', 'time-normal', 'period-lunch', 'period-dinner', 'temp-hot', 'season-all'],
    stats: { pickCount: 0, rejectCount: 0 },
    createdAt: FIXED_TIMESTAMP,
  },
  {
    id: 'demo-s2',
    name: '麻婆豆腐',
    tags: ['cuisine-sichuan', 'taste-mala', 'taste-medium-spicy', 'taste-umami', 'type-hot', 'price-budget', 'time-fast', 'period-lunch', 'period-dinner', 'temp-hot', 'season-all'],
    stats: { pickCount: 0, rejectCount: 0 },
    createdAt: FIXED_TIMESTAMP,
  },
  {
    id: 'demo-s3',
    name: '酸辣粉',
    tags: ['cuisine-sichuan', 'taste-medium-spicy', 'taste-sour', 'taste-slurpy', 'type-snack', 'type-noodles', 'price-budget', 'time-fast', 'period-lunch', 'period-dinner', 'period-midnight', 'temp-hot', 'season-all'],
    stats: { pickCount: 0, rejectCount: 0 },
    createdAt: FIXED_TIMESTAMP,
  },
  {
    id: 'demo-s4',
    name: '麻辣香锅',
    tags: ['cuisine-sichuan', 'taste-mala', 'taste-extra-spicy', 'taste-fragrant', 'taste-heavy', 'type-hot', 'price-moderate', 'time-normal', 'period-lunch', 'period-dinner', 'period-midnight', 'temp-hot', 'season-all'],
    stats: { pickCount: 0, rejectCount: 0 },
    createdAt: FIXED_TIMESTAMP,
  },
  {
    id: 'demo-s5',
    name: '水煮鱼',
    tags: ['cuisine-sichuan', 'taste-extra-spicy', 'taste-mala', 'taste-fresh', 'type-hot', 'price-moderate', 'time-normal', 'period-lunch', 'period-dinner', 'temp-hot', 'season-all'],
    stats: { pickCount: 0, rejectCount: 0 },
    createdAt: FIXED_TIMESTAMP,
  },
  {
    id: 'demo-s6',
    name: '回锅肉',
    tags: ['cuisine-sichuan', 'taste-medium-spicy', 'taste-salty', 'taste-fragrant', 'type-hot', 'price-moderate', 'time-normal', 'period-lunch', 'period-dinner', 'temp-hot', 'season-all'],
    stats: { pickCount: 0, rejectCount: 0 },
    createdAt: FIXED_TIMESTAMP,
  },
  {
    id: 'demo-s7',
    name: '鱼香肉丝',
    tags: ['cuisine-sichuan', 'taste-sour-sweet', 'taste-mild-spicy', 'taste-umami', 'type-hot', 'price-moderate', 'time-normal', 'period-lunch', 'period-dinner', 'temp-hot', 'season-all'],
    stats: { pickCount: 0, rejectCount: 0 },
    createdAt: FIXED_TIMESTAMP,
  },
  {
    id: 'demo-s8',
    name: '口水鸡',
    tags: ['cuisine-sichuan', 'taste-mala', 'taste-medium-spicy', 'taste-tender', 'taste-cold-dish', 'type-cold', 'price-moderate', 'time-normal', 'period-lunch', 'period-dinner', 'temp-cold', 'season-summer'],
    stats: { pickCount: 0, rejectCount: 0 },
    createdAt: FIXED_TIMESTAMP,
  },
  {
    id: 'demo-s9',
    name: '夫妻肺片',
    tags: ['cuisine-sichuan', 'taste-mala', 'taste-medium-spicy', 'taste-cold-dish', 'taste-chewy', 'type-cold', 'price-moderate', 'time-normal', 'period-lunch', 'period-dinner', 'temp-cold', 'season-summer'],
    stats: { pickCount: 0, rejectCount: 0 },
    createdAt: FIXED_TIMESTAMP,
  },
  {
    id: 'demo-s10',
    name: '担担面',
    tags: ['cuisine-sichuan', 'taste-mala', 'taste-medium-spicy', 'taste-umami', 'taste-slurpy', 'type-noodles', 'type-staple', 'price-budget', 'time-fast', 'period-lunch', 'period-dinner', 'period-midnight', 'temp-hot', 'season-all'],
    stats: { pickCount: 0, rejectCount: 0 },
    createdAt: FIXED_TIMESTAMP,
  },
  {
    id: 'demo-s11',
    name: '辣子鸡',
    tags: ['cuisine-sichuan', 'taste-extra-spicy', 'taste-crispy', 'taste-fragrant', 'type-hot', 'price-moderate', 'time-normal', 'period-lunch', 'period-dinner', 'temp-hot', 'season-all'],
    stats: { pickCount: 0, rejectCount: 0 },
    createdAt: FIXED_TIMESTAMP,
  },
  {
    id: 'demo-s12',
    name: '毛血旺',
    tags: ['cuisine-sichuan', 'taste-extra-spicy', 'taste-mala', 'taste-heavy', 'type-hot', 'price-moderate', 'time-normal', 'period-lunch', 'period-dinner', 'temp-hot', 'season-winter'],
    stats: { pickCount: 0, rejectCount: 0 },
    createdAt: FIXED_TIMESTAMP,
  },
  {
    id: 'demo-s13',
    name: '钟水饺',
    tags: ['cuisine-sichuan', 'taste-mild-spicy', 'taste-sweet', 'taste-tender', 'type-dimsum', 'type-snack', 'price-budget', 'time-fast', 'period-breakfast', 'period-lunch', 'period-snack', 'temp-hot', 'season-all'],
    stats: { pickCount: 0, rejectCount: 0 },
    createdAt: FIXED_TIMESTAMP,
  },
  {
    id: 'demo-s14',
    name: '龙抄手',
    tags: ['cuisine-sichuan', 'taste-light', 'taste-umami', 'taste-tender', 'type-dimsum', 'type-snack', 'price-budget', 'time-fast', 'period-breakfast', 'period-lunch', 'period-snack', 'temp-hot', 'season-all'],
    stats: { pickCount: 0, rejectCount: 0 },
    createdAt: FIXED_TIMESTAMP,
  },
  {
    id: 'demo-s15',
    name: '蒜泥白肉',
    tags: ['cuisine-sichuan', 'taste-medium-spicy', 'taste-salty', 'taste-fragrant', 'taste-cold-dish', 'type-cold', 'price-moderate', 'time-normal', 'period-lunch', 'period-dinner', 'temp-cold', 'season-summer'],
    stats: { pickCount: 0, rejectCount: 0 },
    createdAt: FIXED_TIMESTAMP,
  },
  {
    id: 'demo-s16',
    name: '冷吃兔',
    tags: ['cuisine-sichuan', 'taste-extra-spicy', 'taste-mala', 'taste-crispy', 'taste-cold-dish', 'type-cold', 'price-moderate', 'time-slow', 'period-lunch', 'period-dinner', 'period-snack', 'temp-room', 'season-all'],
    stats: { pickCount: 0, rejectCount: 0 },
    createdAt: FIXED_TIMESTAMP,
  },
  {
    id: 'demo-s17',
    name: '泡椒凤爪',
    tags: ['cuisine-sichuan', 'taste-medium-spicy', 'taste-sour', 'taste-chewy', 'taste-cold-dish', 'type-cold', 'type-snack', 'price-budget', 'time-fast', 'period-snack', 'period-midnight', 'temp-cold', 'season-summer'],
    stats: { pickCount: 0, rejectCount: 0 },
    createdAt: FIXED_TIMESTAMP,
  },
  {
    id: 'demo-s18',
    name: '串串香',
    tags: ['cuisine-sichuan', 'taste-mala', 'taste-medium-spicy', 'taste-heavy', 'type-hot', 'type-snack', 'price-moderate', 'time-normal', 'period-dinner', 'period-midnight', 'temp-hot', 'season-all'],
    stats: { pickCount: 0, rejectCount: 0 },
    createdAt: FIXED_TIMESTAMP,
  },
  {
    id: 'demo-s19',
    name: '冒菜',
    tags: ['cuisine-sichuan', 'taste-mala', 'taste-medium-spicy', 'taste-fresh', 'type-hot', 'type-soup', 'price-budget', 'time-fast', 'period-lunch', 'period-dinner', 'period-midnight', 'temp-hot', 'season-winter'],
    stats: { pickCount: 0, rejectCount: 0 },
    createdAt: FIXED_TIMESTAMP,
  },
  {
    id: 'demo-s20',
    name: '钵钵鸡',
    tags: ['cuisine-sichuan', 'taste-mala', 'taste-medium-spicy', 'taste-cold-dish', 'taste-fragrant', 'type-cold', 'type-snack', 'price-budget', 'time-fast', 'period-lunch', 'period-snack', 'temp-cold', 'season-summer'],
    stats: { pickCount: 0, rejectCount: 0 },
    createdAt: FIXED_TIMESTAMP,
  },
  {
    id: 'demo-s21',
    name: '红油抄手',
    tags: ['cuisine-sichuan', 'taste-medium-spicy', 'taste-umami', 'taste-slurpy', 'type-dimsum', 'type-snack', 'price-budget', 'time-fast', 'period-breakfast', 'period-lunch', 'period-snack', 'temp-hot', 'season-all'],
    stats: { pickCount: 0, rejectCount: 0 },
    createdAt: FIXED_TIMESTAMP,
  },
  {
    id: 'demo-s22',
    name: '川北凉粉',
    tags: ['cuisine-sichuan', 'taste-medium-spicy', 'taste-sour', 'taste-soft', 'taste-cold-dish', 'type-cold', 'type-snack', 'price-budget', 'time-fast', 'period-lunch', 'period-snack', 'temp-cold', 'season-summer'],
    stats: { pickCount: 0, rejectCount: 0 },
    createdAt: FIXED_TIMESTAMP,
  },
  {
    id: 'demo-s23',
    name: '棒棒鸡',
    tags: ['cuisine-sichuan', 'taste-mala', 'taste-medium-spicy', 'taste-tender', 'taste-cold-dish', 'type-cold', 'price-moderate', 'time-normal', 'period-lunch', 'period-dinner', 'temp-cold', 'season-summer'],
    stats: { pickCount: 0, rejectCount: 0 },
    createdAt: FIXED_TIMESTAMP,
  },
  {
    id: 'demo-s24',
    name: '蒜烧肉',
    tags: ['cuisine-sichuan', 'taste-salty', 'taste-fragrant', 'taste-umami', 'type-hot', 'price-moderate', 'time-normal', 'period-lunch', 'period-dinner', 'temp-hot', 'season-all'],
    stats: { pickCount: 0, rejectCount: 0 },
    createdAt: FIXED_TIMESTAMP,
  },
  {
    id: 'demo-s25',
    name: '水煮肉片',
    tags: ['cuisine-sichuan', 'taste-extra-spicy', 'taste-mala', 'taste-tender', 'type-hot', 'price-moderate', 'time-normal', 'period-lunch', 'period-dinner', 'temp-hot', 'season-all'],
    stats: { pickCount: 0, rejectCount: 0 },
    createdAt: FIXED_TIMESTAMP,
  },
  {
    id: 'demo-s26',
    name: '干烧鱼',
    tags: ['cuisine-sichuan', 'taste-medium-spicy', 'taste-sour-sweet', 'taste-umami', 'type-hot', 'price-moderate', 'time-slow', 'period-lunch', 'period-dinner', 'temp-hot', 'season-all'],
    stats: { pickCount: 0, rejectCount: 0 },
    createdAt: FIXED_TIMESTAMP,
  },
  {
    id: 'demo-s27',
    name: '豆花饭',
    tags: ['cuisine-sichuan', 'taste-mild-spicy', 'taste-soft', 'taste-light', 'type-staple', 'type-rice', 'price-budget', 'time-fast', 'period-lunch', 'period-dinner', 'temp-hot', 'season-all'],
    stats: { pickCount: 0, rejectCount: 0 },
    createdAt: FIXED_TIMESTAMP,
  },
  {
    id: 'demo-s28',
    name: '甜水面',
    tags: ['cuisine-sichuan', 'taste-sweet', 'taste-mild-spicy', 'taste-chewy', 'type-noodles', 'type-snack', 'price-budget', 'time-fast', 'period-breakfast', 'period-snack', 'temp-room', 'season-all'],
    stats: { pickCount: 0, rejectCount: 0 },
    createdAt: FIXED_TIMESTAMP,
  },
  {
    id: 'demo-s29',
    name: '酸辣豆花',
    tags: ['cuisine-sichuan', 'taste-sour', 'taste-mild-spicy', 'taste-soft', 'type-snack', 'price-budget', 'time-fast', 'period-breakfast', 'period-snack', 'temp-hot', 'season-all'],
    stats: { pickCount: 0, rejectCount: 0 },
    createdAt: FIXED_TIMESTAMP,
  },
  {
    id: 'demo-s30',
    name: '灯影牛肉',
    tags: ['cuisine-sichuan', 'taste-medium-spicy', 'taste-crispy', 'taste-fragrant', 'taste-cold-dish', 'type-cold', 'type-snack', 'price-premium', 'time-slow', 'period-snack', 'period-dinner', 'temp-room', 'season-all'],
    stats: { pickCount: 0, rejectCount: 0 },
    createdAt: FIXED_TIMESTAMP,
  },
  {
    id: 'demo-s31',
    name: '尖椒鸡',
    tags: ['cuisine-sichuan', 'taste-extra-spicy', 'taste-fragrant', 'taste-tender', 'type-hot', 'price-moderate', 'time-normal', 'period-lunch', 'period-dinner', 'temp-hot', 'season-all'],
    stats: { pickCount: 0, rejectCount: 0 },
    createdAt: FIXED_TIMESTAMP,
  },
  {
    id: 'demo-s32',
    name: '泡椒鱼',
    tags: ['cuisine-sichuan', 'taste-medium-spicy', 'taste-sour', 'taste-fresh', 'type-hot', 'price-moderate', 'time-normal', 'period-lunch', 'period-dinner', 'temp-hot', 'season-all'],
    stats: { pickCount: 0, rejectCount: 0 },
    createdAt: FIXED_TIMESTAMP,
  },
  {
    id: 'demo-s33',
    name: '椒麻鸡',
    tags: ['cuisine-sichuan', 'taste-mala', 'taste-medium-spicy', 'taste-tender', 'taste-cold-dish', 'type-cold', 'price-moderate', 'time-normal', 'period-lunch', 'period-dinner', 'temp-cold', 'season-summer'],
    stats: { pickCount: 0, rejectCount: 0 },
    createdAt: FIXED_TIMESTAMP,
  },
  {
    id: 'demo-s34',
    name: '豆瓣鱼',
    tags: ['cuisine-sichuan', 'taste-medium-spicy', 'taste-salty', 'taste-umami', 'taste-fresh', 'type-hot', 'price-moderate', 'time-normal', 'period-lunch', 'period-dinner', 'temp-hot', 'season-all'],
    stats: { pickCount: 0, rejectCount: 0 },
    createdAt: FIXED_TIMESTAMP,
  },
  {
    id: 'demo-s35',
    name: '蚂蚁上树',
    tags: ['cuisine-sichuan', 'taste-medium-spicy', 'taste-umami', 'taste-slurpy', 'type-hot', 'price-budget', 'time-fast', 'period-lunch', 'period-dinner', 'temp-hot', 'season-all'],
    stats: { pickCount: 0, rejectCount: 0 },
    createdAt: FIXED_TIMESTAMP,
  },
  {
    id: 'demo-s36',
    name: '干锅花菜',
    tags: ['cuisine-sichuan', 'taste-medium-spicy', 'taste-fragrant', 'taste-crispy', 'type-hot', 'price-budget', 'time-normal', 'period-lunch', 'period-dinner', 'temp-hot', 'season-all'],
    stats: { pickCount: 0, rejectCount: 0 },
    createdAt: FIXED_TIMESTAMP,
  },
  {
    id: 'demo-s37',
    name: '干锅土豆片',
    tags: ['cuisine-sichuan', 'taste-medium-spicy', 'taste-fragrant', 'taste-crispy', 'type-hot', 'price-budget', 'time-normal', 'period-lunch', 'period-dinner', 'temp-hot', 'season-all'],
    stats: { pickCount: 0, rejectCount: 0 },
    createdAt: FIXED_TIMESTAMP,
  },
  {
    id: 'demo-s38',
    name: '老妈蹄花',
    tags: ['cuisine-sichuan', 'taste-light', 'taste-soft', 'taste-umami', 'type-soup', 'price-moderate', 'time-slow', 'period-lunch', 'period-dinner', 'temp-hot', 'season-winter'],
    stats: { pickCount: 0, rejectCount: 0 },
    createdAt: FIXED_TIMESTAMP,
  },
  {
    id: 'demo-s39',
    name: '烧白',
    tags: ['cuisine-sichuan', 'taste-sweet', 'taste-soft', 'taste-umami', 'type-hot', 'price-moderate', 'time-slow', 'period-lunch', 'period-dinner', 'temp-hot', 'season-all'],
    stats: { pickCount: 0, rejectCount: 0 },
    createdAt: FIXED_TIMESTAMP,
  },
  {
    id: 'demo-s40',
    name: '粉蒸肉',
    tags: ['cuisine-sichuan', 'taste-mild-spicy', 'taste-soft', 'taste-umami', 'taste-fragrant', 'type-hot', 'price-moderate', 'time-slow', 'period-lunch', 'period-dinner', 'temp-hot', 'season-all'],
    stats: { pickCount: 0, rejectCount: 0 },
    createdAt: FIXED_TIMESTAMP,
  },
  {
    id: 'demo-s41',
    name: '酸菜肉丝面',
    tags: ['cuisine-sichuan', 'taste-sour', 'taste-mild-spicy', 'taste-slurpy', 'type-noodles', 'type-staple', 'price-budget', 'time-fast', 'period-lunch', 'period-dinner', 'temp-hot', 'season-all'],
    stats: { pickCount: 0, rejectCount: 0 },
    createdAt: FIXED_TIMESTAMP,
  },
  {
    id: 'demo-s42',
    name: '麻辣兔头',
    tags: ['cuisine-sichuan', 'taste-mala', 'taste-extra-spicy', 'taste-chewy', 'type-snack', 'price-budget', 'time-normal', 'period-snack', 'period-midnight', 'temp-room', 'season-all'],
    stats: { pickCount: 0, rejectCount: 0 },
    createdAt: FIXED_TIMESTAMP,
  },
  {
    id: 'demo-s43',
    name: '火爆腰花',
    tags: ['cuisine-sichuan', 'taste-medium-spicy', 'taste-crispy', 'taste-tender', 'type-hot', 'price-moderate', 'time-fast', 'period-lunch', 'period-dinner', 'temp-hot', 'season-all'],
    stats: { pickCount: 0, rejectCount: 0 },
    createdAt: FIXED_TIMESTAMP,
  },
  {
    id: 'demo-s44',
    name: '藤椒鸡',
    tags: ['cuisine-sichuan', 'taste-mala', 'taste-mild-spicy', 'taste-tender', 'taste-fragrant', 'type-cold', 'price-moderate', 'time-normal', 'period-lunch', 'period-dinner', 'temp-cold', 'season-summer'],
    stats: { pickCount: 0, rejectCount: 0 },
    createdAt: FIXED_TIMESTAMP,
  },
  {
    id: 'demo-s45',
    name: '干煸四季豆',
    tags: ['cuisine-sichuan', 'taste-mild-spicy', 'taste-fragrant', 'taste-crispy', 'type-hot', 'price-budget', 'time-fast', 'period-lunch', 'period-dinner', 'temp-hot', 'season-all'],
    stats: { pickCount: 0, rejectCount: 0 },
    createdAt: FIXED_TIMESTAMP,
  },
  {
    id: 'demo-s46',
    name: '樟茶鸭',
    tags: ['cuisine-sichuan', 'taste-fragrant', 'taste-crispy', 'taste-umami', 'type-hot', 'price-premium', 'time-slow', 'period-lunch', 'period-dinner', 'temp-hot', 'season-all'],
    stats: { pickCount: 0, rejectCount: 0 },
    createdAt: FIXED_TIMESTAMP,
  },
  {
    id: 'demo-s47',
    name: '锅巴肉片',
    tags: ['cuisine-sichuan', 'taste-sour-sweet', 'taste-crispy', 'taste-tender', 'type-hot', 'price-moderate', 'time-normal', 'period-lunch', 'period-dinner', 'temp-hot', 'season-all'],
    stats: { pickCount: 0, rejectCount: 0 },
    createdAt: FIXED_TIMESTAMP,
  },
  {
    id: 'demo-s48',
    name: '泡椒牛蛙',
    tags: ['cuisine-sichuan', 'taste-medium-spicy', 'taste-sour', 'taste-tender', 'type-hot', 'price-premium', 'time-normal', 'period-lunch', 'period-dinner', 'temp-hot', 'season-all'],
    stats: { pickCount: 0, rejectCount: 0 },
    createdAt: FIXED_TIMESTAMP,
  },
  {
    id: 'demo-s49',
    name: '酸辣蕨根粉',
    tags: ['cuisine-sichuan', 'taste-sour', 'taste-medium-spicy', 'taste-slurpy', 'taste-cold-dish', 'type-cold', 'type-snack', 'price-budget', 'time-fast', 'period-lunch', 'period-snack', 'temp-cold', 'season-summer'],
    stats: { pickCount: 0, rejectCount: 0 },
    createdAt: FIXED_TIMESTAMP,
  },
  {
    id: 'demo-s50',
    name: '钵钵鸡串',
    tags: ['cuisine-sichuan', 'taste-mala', 'taste-medium-spicy', 'taste-cold-dish', 'taste-fragrant', 'type-cold', 'type-snack', 'price-budget', 'time-fast', 'period-lunch', 'period-dinner', 'period-snack', 'temp-cold', 'season-summer'],
    stats: { pickCount: 0, rejectCount: 0 },
    createdAt: FIXED_TIMESTAMP,
  },
]
