import { Dish } from '@/types'

const FIXED_TIMESTAMP = 1700000000000

export const SOUTHEAST_DISHES: Dish[] = [
  {
    id: 'demo-se1',
    name: '冬阴功汤',
    tags: ['cuisine-southeast', 'taste-sour', 'taste-medium-spicy', 'taste-umami', 'type-soup', 'price-moderate', 'time-normal', 'period-lunch', 'period-dinner', 'temp-hot', 'season-all'],
    stats: { pickCount: 0, rejectCount: 0 },
    createdAt: FIXED_TIMESTAMP,
  },
  {
    id: 'demo-se2',
    name: '泰式炒饭',
    tags: ['cuisine-southeast', 'taste-medium-spicy', 'taste-umami', 'taste-fragrant', 'type-rice', 'price-moderate', 'time-normal', 'period-lunch', 'temp-hot', 'season-all'],
    stats: { pickCount: 0, rejectCount: 0 },
    createdAt: FIXED_TIMESTAMP,
  },
  {
    id: 'demo-se3',
    name: '咖喱鸡',
    tags: ['cuisine-southeast', 'taste-medium-spicy', 'taste-heavy', 'taste-umami', 'type-hot', 'price-moderate', 'time-normal', 'period-lunch', 'period-dinner', 'temp-hot', 'season-all'],
    stats: { pickCount: 0, rejectCount: 0 },
    createdAt: FIXED_TIMESTAMP,
  },
  {
    id: 'demo-se4',
    name: '越南粉',
    tags: ['cuisine-southeast', 'taste-light', 'taste-umami', 'taste-fresh', 'taste-slurpy', 'type-noodles', 'price-moderate', 'time-normal', 'period-lunch', 'temp-hot', 'season-all'],
    stats: { pickCount: 0, rejectCount: 0 },
    createdAt: FIXED_TIMESTAMP,
  },
  {
    id: 'demo-se5',
    name: '芒果糯米饭',
    tags: ['cuisine-southeast', 'taste-sweet', 'taste-soft', 'type-dessert', 'price-moderate', 'time-fast', 'period-snack', 'temp-room', 'season-summer'],
    stats: { pickCount: 0, rejectCount: 0 },
    createdAt: FIXED_TIMESTAMP,
  },
  {
    id: 'demo-se6',
    name: '叻沙',
    tags: ['cuisine-southeast', 'taste-medium-spicy', 'taste-heavy', 'taste-umami', 'type-noodles', 'price-moderate', 'time-normal', 'period-lunch', 'period-dinner', 'temp-hot', 'season-all'],
    stats: { pickCount: 0, rejectCount: 0 },
    createdAt: FIXED_TIMESTAMP,
  },
  {
    id: 'demo-se7',
    name: '海南鸡饭',
    tags: ['cuisine-southeast', 'taste-light', 'taste-umami', 'taste-tender', 'type-rice', 'price-moderate', 'time-normal', 'period-lunch', 'period-dinner', 'temp-hot', 'season-all'],
    stats: { pickCount: 0, rejectCount: 0 },
    createdAt: FIXED_TIMESTAMP,
  },
  {
    id: 'demo-se8',
    name: '沙嗲',
    tags: ['cuisine-southeast', 'taste-fragrant', 'taste-sweet', 'taste-mild-spicy', 'type-snack', 'price-moderate', 'time-normal', 'period-dinner', 'period-snack', 'temp-hot', 'season-all'],
    stats: { pickCount: 0, rejectCount: 0 },
    createdAt: FIXED_TIMESTAMP,
  },
  {
    id: 'demo-se9',
    name: '冬阴功面',
    tags: ['cuisine-southeast', 'taste-sour', 'taste-medium-spicy', 'taste-umami', 'taste-slurpy', 'type-noodles', 'price-moderate', 'time-normal', 'period-lunch', 'temp-hot', 'season-all'],
    stats: { pickCount: 0, rejectCount: 0 },
    createdAt: FIXED_TIMESTAMP,
  },
  {
    id: 'demo-se10',
    name: '泰式凉拌',
    tags: ['cuisine-southeast', 'taste-sour', 'taste-medium-spicy', 'taste-fresh', 'type-cold', 'price-budget', 'time-fast', 'period-lunch', 'period-dinner', 'temp-cold', 'season-summer'],
    stats: { pickCount: 0, rejectCount: 0 },
    createdAt: FIXED_TIMESTAMP,
  },
  {
    id: 'demo-se11',
    name: '椰浆饭',
    tags: ['cuisine-southeast', 'taste-fragrant', 'taste-mild-spicy', 'taste-umami', 'type-rice', 'price-budget', 'time-normal', 'period-breakfast', 'period-lunch', 'temp-hot', 'season-all'],
    stats: { pickCount: 0, rejectCount: 0 },
    createdAt: FIXED_TIMESTAMP,
  },
  {
    id: 'demo-se12',
    name: '印尼炒饭',
    tags: ['cuisine-southeast', 'taste-salty', 'taste-fragrant', 'taste-umami', 'type-rice', 'price-budget', 'time-fast', 'period-lunch', 'temp-hot', 'season-all'],
    stats: { pickCount: 0, rejectCount: 0 },
    createdAt: FIXED_TIMESTAMP,
  },
  {
    id: 'demo-se13',
    name: '肉骨茶',
    tags: ['cuisine-southeast', 'taste-light', 'taste-umami', 'taste-fragrant', 'type-soup', 'price-moderate', 'time-slow', 'period-lunch', 'period-dinner', 'temp-hot', 'season-winter'],
    stats: { pickCount: 0, rejectCount: 0 },
    createdAt: FIXED_TIMESTAMP,
  },
  {
    id: 'demo-se14',
    name: '咖喱蟹',
    tags: ['cuisine-southeast', 'taste-medium-spicy', 'taste-heavy', 'taste-umami', 'type-hot', 'price-premium', 'time-slow', 'period-dinner', 'temp-hot', 'season-all'],
    stats: { pickCount: 0, rejectCount: 0 },
    createdAt: FIXED_TIMESTAMP,
  },
  {
    id: 'demo-se15',
    name: '炸春卷',
    tags: ['cuisine-southeast', 'taste-crispy', 'taste-fragrant', 'taste-salty', 'type-snack', 'price-budget', 'time-fast', 'period-snack', 'period-lunch', 'temp-hot', 'season-all'],
    stats: { pickCount: 0, rejectCount: 0 },
    createdAt: FIXED_TIMESTAMP,
  },
  {
    id: 'demo-se16',
    name: '越南春卷',
    tags: ['cuisine-southeast', 'taste-fresh', 'taste-light', 'taste-sour', 'type-cold', 'price-budget', 'time-fast', 'period-snack', 'period-lunch', 'temp-cold', 'season-summer'],
    stats: { pickCount: 0, rejectCount: 0 },
    createdAt: FIXED_TIMESTAMP,
  },
  {
    id: 'demo-se17',
    name: '绿咖喱',
    tags: ['cuisine-southeast', 'taste-medium-spicy', 'taste-heavy', 'taste-fragrant', 'type-hot', 'price-moderate', 'time-normal', 'period-lunch', 'period-dinner', 'temp-hot', 'season-all'],
    stats: { pickCount: 0, rejectCount: 0 },
    createdAt: FIXED_TIMESTAMP,
  },
  {
    id: 'demo-se18',
    name: '红咖喱',
    tags: ['cuisine-southeast', 'taste-medium-spicy', 'taste-heavy', 'taste-umami', 'type-hot', 'price-moderate', 'time-normal', 'period-lunch', 'period-dinner', 'temp-hot', 'season-all'],
    stats: { pickCount: 0, rejectCount: 0 },
    createdAt: FIXED_TIMESTAMP,
  },
  {
    id: 'demo-se19',
    name: '泰式奶茶',
    tags: ['cuisine-southeast', 'taste-sweet', 'taste-fragrant', 'type-drink', 'price-budget', 'time-fast', 'period-snack', 'temp-cold', 'season-summer'],
    stats: { pickCount: 0, rejectCount: 0 },
    createdAt: FIXED_TIMESTAMP,
  },
  {
    id: 'demo-se20',
    name: '新加坡炒面',
    tags: ['cuisine-southeast', 'taste-mild-spicy', 'taste-fragrant', 'taste-chewy', 'type-noodles', 'price-moderate', 'time-normal', 'period-lunch', 'period-dinner', 'temp-hot', 'season-all'],
    stats: { pickCount: 0, rejectCount: 0 },
    createdAt: FIXED_TIMESTAMP,
  },
  {
    id: 'demo-se21',
    name: '马来沙嗲',
    tags: ['cuisine-southeast', 'taste-fragrant', 'taste-sweet', 'taste-mild-spicy', 'type-snack', 'price-moderate', 'time-normal', 'period-dinner', 'period-midnight', 'temp-hot', 'season-all'],
    stats: { pickCount: 0, rejectCount: 0 },
    createdAt: FIXED_TIMESTAMP,
  },
  {
    id: 'demo-se22',
    name: '泰式烤鱼',
    tags: ['cuisine-southeast', 'taste-medium-spicy', 'taste-sour', 'taste-fragrant', 'type-hot', 'price-premium', 'time-slow', 'period-dinner', 'temp-hot', 'season-all'],
    stats: { pickCount: 0, rejectCount: 0 },
    createdAt: FIXED_TIMESTAMP,
  },
  {
    id: 'demo-se23',
    name: '椰汁虾汤',
    tags: ['cuisine-southeast', 'taste-light', 'taste-umami', 'taste-sweet', 'type-soup', 'price-moderate', 'time-normal', 'period-lunch', 'period-dinner', 'temp-hot', 'season-all'],
    stats: { pickCount: 0, rejectCount: 0 },
    createdAt: FIXED_TIMESTAMP,
  },
  {
    id: 'demo-se24',
    name: '班兰蛋糕',
    tags: ['cuisine-southeast', 'taste-sweet', 'taste-soft', 'taste-fragrant', 'type-dessert', 'price-budget', 'time-fast', 'period-snack', 'temp-room', 'season-all'],
    stats: { pickCount: 0, rejectCount: 0 },
    createdAt: FIXED_TIMESTAMP,
  },
  {
    id: 'demo-se25',
    name: '摩摩喳喳',
    tags: ['cuisine-southeast', 'taste-sweet', 'taste-soft', 'taste-fresh', 'type-dessert', 'price-budget', 'time-fast', 'period-snack', 'temp-cold', 'season-summer'],
    stats: { pickCount: 0, rejectCount: 0 },
    createdAt: FIXED_TIMESTAMP,
  },
]
