import { Dish } from '@/types'

const FIXED_TIMESTAMP = 1700000000000

export const WESTERN_DISHES: Dish[] = [
  {
    id: 'demo-w1',
    name: '意大利面',
    tags: ['cuisine-western', 'taste-heavy', 'taste-umami', 'taste-chewy', 'type-staple', 'price-moderate', 'time-normal', 'period-lunch', 'period-dinner', 'temp-hot', 'season-all'],
    stats: { pickCount: 0, rejectCount: 0 },
    createdAt: FIXED_TIMESTAMP,
  },
  {
    id: 'demo-w2',
    name: '沙拉',
    tags: ['cuisine-western', 'taste-light', 'taste-fresh', 'type-cold', 'price-moderate', 'time-fast', 'period-lunch', 'temp-cold', 'season-summer'],
    stats: { pickCount: 0, rejectCount: 0 },
    createdAt: FIXED_TIMESTAMP,
  },
  {
    id: 'demo-w3',
    name: '牛排',
    tags: ['cuisine-western', 'taste-heavy', 'taste-umami', 'taste-tender', 'type-hot', 'price-luxury', 'time-slow', 'period-dinner', 'temp-hot', 'season-all'],
    stats: { pickCount: 0, rejectCount: 0 },
    createdAt: FIXED_TIMESTAMP,
  },
  {
    id: 'demo-w4',
    name: '三明治',
    tags: ['cuisine-western', 'taste-light', 'taste-fresh', 'type-snack', 'price-budget', 'time-fast', 'period-breakfast', 'period-lunch', 'temp-room', 'season-all'],
    stats: { pickCount: 0, rejectCount: 0 },
    createdAt: FIXED_TIMESTAMP,
  },
  {
    id: 'demo-w5',
    name: '披萨',
    tags: ['cuisine-western', 'taste-heavy', 'taste-crispy', 'taste-umami', 'type-staple', 'price-premium', 'time-slow', 'period-dinner', 'temp-hot', 'season-all'],
    stats: { pickCount: 0, rejectCount: 0 },
    createdAt: FIXED_TIMESTAMP,
  },
  {
    id: 'demo-w6',
    name: '汉堡',
    tags: ['cuisine-western', 'taste-heavy', 'taste-crispy', 'taste-salty', 'type-snack', 'price-moderate', 'time-fast', 'period-lunch', 'period-dinner', 'temp-hot', 'season-all'],
    stats: { pickCount: 0, rejectCount: 0 },
    createdAt: FIXED_TIMESTAMP,
  },
  {
    id: 'demo-w7',
    name: '焗饭',
    tags: ['cuisine-western', 'taste-heavy', 'taste-crispy', 'taste-umami', 'type-rice', 'price-moderate', 'time-normal', 'period-lunch', 'period-dinner', 'temp-hot', 'season-all'],
    stats: { pickCount: 0, rejectCount: 0 },
    createdAt: FIXED_TIMESTAMP,
  },
  {
    id: 'demo-w8',
    name: '法式洋葱汤',
    tags: ['cuisine-western', 'taste-salty', 'taste-umami', 'taste-soft', 'type-soup', 'price-moderate', 'time-normal', 'period-dinner', 'temp-hot', 'season-winter'],
    stats: { pickCount: 0, rejectCount: 0 },
    createdAt: FIXED_TIMESTAMP,
  },
  {
    id: 'demo-w9',
    name: '奶油蘑菇汤',
    tags: ['cuisine-western', 'taste-light', 'taste-umami', 'taste-soft', 'type-soup', 'price-moderate', 'time-normal', 'period-lunch', 'period-dinner', 'temp-hot', 'season-winter'],
    stats: { pickCount: 0, rejectCount: 0 },
    createdAt: FIXED_TIMESTAMP,
  },
  {
    id: 'demo-w10',
    name: '凯撒沙拉',
    tags: ['cuisine-western', 'taste-salty', 'taste-fresh', 'taste-crispy', 'type-cold', 'price-moderate', 'time-fast', 'period-lunch', 'temp-cold', 'season-all'],
    stats: { pickCount: 0, rejectCount: 0 },
    createdAt: FIXED_TIMESTAMP,
  },
  {
    id: 'demo-w11',
    name: '烤鸡腿',
    tags: ['cuisine-western', 'taste-salty', 'taste-fragrant', 'taste-crispy', 'type-hot', 'price-moderate', 'time-normal', 'period-lunch', 'period-dinner', 'temp-hot', 'season-all'],
    stats: { pickCount: 0, rejectCount: 0 },
    createdAt: FIXED_TIMESTAMP,
  },
  {
    id: 'demo-w12',
    name: '意式肉酱面',
    tags: ['cuisine-western', 'taste-heavy', 'taste-umami', 'taste-salty', 'type-noodles', 'price-moderate', 'time-normal', 'period-lunch', 'period-dinner', 'temp-hot', 'season-all'],
    stats: { pickCount: 0, rejectCount: 0 },
    createdAt: FIXED_TIMESTAMP,
  },
  {
    id: 'demo-w13',
    name: '白酱意面',
    tags: ['cuisine-western', 'taste-light', 'taste-umami', 'taste-soft', 'type-noodles', 'price-moderate', 'time-normal', 'period-lunch', 'period-dinner', 'temp-hot', 'season-all'],
    stats: { pickCount: 0, rejectCount: 0 },
    createdAt: FIXED_TIMESTAMP,
  },
  {
    id: 'demo-w14',
    name: '海鲜意面',
    tags: ['cuisine-western', 'taste-umami', 'taste-light', 'taste-fresh', 'type-noodles', 'price-premium', 'time-normal', 'period-lunch', 'period-dinner', 'temp-hot', 'season-all'],
    stats: { pickCount: 0, rejectCount: 0 },
    createdAt: FIXED_TIMESTAMP,
  },
  {
    id: 'demo-w15',
    name: '玛格丽特披萨',
    tags: ['cuisine-western', 'taste-light', 'taste-crispy', 'taste-umami', 'type-staple', 'price-moderate', 'time-normal', 'period-lunch', 'period-dinner', 'temp-hot', 'season-all'],
    stats: { pickCount: 0, rejectCount: 0 },
    createdAt: FIXED_TIMESTAMP,
  },
  {
    id: 'demo-w16',
    name: '薯条',
    tags: ['cuisine-western', 'taste-salty', 'taste-crispy', 'type-snack', 'price-budget', 'time-fast', 'period-snack', 'period-lunch', 'temp-hot', 'season-all'],
    stats: { pickCount: 0, rejectCount: 0 },
    createdAt: FIXED_TIMESTAMP,
  },
  {
    id: 'demo-w17',
    name: '炸鱼薯条',
    tags: ['cuisine-western', 'taste-salty', 'taste-crispy', 'taste-umami', 'type-staple', 'price-moderate', 'time-normal', 'period-lunch', 'period-dinner', 'temp-hot', 'season-all'],
    stats: { pickCount: 0, rejectCount: 0 },
    createdAt: FIXED_TIMESTAMP,
  },
  {
    id: 'demo-w18',
    name: '美式早餐',
    tags: ['cuisine-western', 'taste-salty', 'taste-fragrant', 'taste-crispy', 'type-staple', 'price-moderate', 'time-fast', 'period-breakfast', 'temp-hot', 'season-all'],
    stats: { pickCount: 0, rejectCount: 0 },
    createdAt: FIXED_TIMESTAMP,
  },
  {
    id: 'demo-w19',
    name: '班尼迪克蛋',
    tags: ['cuisine-western', 'taste-light', 'taste-umami', 'taste-soft', 'type-staple', 'price-moderate', 'time-normal', 'period-breakfast', 'temp-hot', 'season-all'],
    stats: { pickCount: 0, rejectCount: 0 },
    createdAt: FIXED_TIMESTAMP,
  },
  {
    id: 'demo-w20',
    name: '法式吐司',
    tags: ['cuisine-western', 'taste-sweet', 'taste-soft', 'taste-fragrant', 'type-staple', 'price-budget', 'time-fast', 'period-breakfast', 'period-snack', 'temp-hot', 'season-all'],
    stats: { pickCount: 0, rejectCount: 0 },
    createdAt: FIXED_TIMESTAMP,
  },
  {
    id: 'demo-w21',
    name: '牛肉汉堡',
    tags: ['cuisine-western', 'taste-heavy', 'taste-salty', 'taste-umami', 'type-snack', 'price-moderate', 'time-fast', 'period-lunch', 'period-dinner', 'temp-hot', 'season-all'],
    stats: { pickCount: 0, rejectCount: 0 },
    createdAt: FIXED_TIMESTAMP,
  },
  {
    id: 'demo-w22',
    name: '鸡肉卷',
    tags: ['cuisine-western', 'taste-light', 'taste-fresh', 'taste-tender', 'type-snack', 'price-budget', 'time-fast', 'period-lunch', 'temp-room', 'season-all'],
    stats: { pickCount: 0, rejectCount: 0 },
    createdAt: FIXED_TIMESTAMP,
  },
  {
    id: 'demo-w23',
    name: '墨西哥卷饼',
    tags: ['cuisine-western', 'taste-medium-spicy', 'taste-salty', 'taste-fresh', 'type-snack', 'price-moderate', 'time-fast', 'period-lunch', 'period-dinner', 'temp-hot', 'season-all'],
    stats: { pickCount: 0, rejectCount: 0 },
    createdAt: FIXED_TIMESTAMP,
  },
  {
    id: 'demo-w24',
    name: '奶油芝士蛋糕',
    tags: ['cuisine-western', 'taste-sweet', 'taste-soft', 'type-dessert', 'price-moderate', 'time-fast', 'period-snack', 'temp-cold', 'season-all'],
    stats: { pickCount: 0, rejectCount: 0 },
    createdAt: FIXED_TIMESTAMP,
  },
  {
    id: 'demo-w25',
    name: '提拉米苏',
    tags: ['cuisine-western', 'taste-sweet', 'taste-soft', 'taste-fragrant', 'type-dessert', 'price-moderate', 'time-fast', 'period-snack', 'temp-cold', 'season-all'],
    stats: { pickCount: 0, rejectCount: 0 },
    createdAt: FIXED_TIMESTAMP,
  },
  {
    id: 'demo-w26',
    name: '布朗尼',
    tags: ['cuisine-western', 'taste-sweet', 'taste-soft', 'taste-fragrant', 'type-dessert', 'price-budget', 'time-fast', 'period-snack', 'temp-room', 'season-all'],
    stats: { pickCount: 0, rejectCount: 0 },
    createdAt: FIXED_TIMESTAMP,
  },
  {
    id: 'demo-w27',
    name: '华夫饼',
    tags: ['cuisine-western', 'taste-sweet', 'taste-crispy', 'taste-soft', 'type-dessert', 'price-budget', 'time-fast', 'period-breakfast', 'period-snack', 'temp-hot', 'season-all'],
    stats: { pickCount: 0, rejectCount: 0 },
    createdAt: FIXED_TIMESTAMP,
  },
  {
    id: 'demo-w28',
    name: '可颂',
    tags: ['cuisine-western', 'taste-sweet', 'taste-crispy', 'taste-fragrant', 'type-dimsum', 'price-budget', 'time-fast', 'period-breakfast', 'period-snack', 'temp-room', 'season-all'],
    stats: { pickCount: 0, rejectCount: 0 },
    createdAt: FIXED_TIMESTAMP,
  },
  {
    id: 'demo-w29',
    name: '法棍三明治',
    tags: ['cuisine-western', 'taste-salty', 'taste-crispy', 'taste-fresh', 'type-snack', 'price-moderate', 'time-fast', 'period-lunch', 'temp-room', 'season-all'],
    stats: { pickCount: 0, rejectCount: 0 },
    createdAt: FIXED_TIMESTAMP,
  },
  {
    id: 'demo-w30',
    name: '牛肉塔可',
    tags: ['cuisine-western', 'taste-medium-spicy', 'taste-salty', 'taste-crispy', 'type-snack', 'price-moderate', 'time-fast', 'period-lunch', 'period-dinner', 'temp-hot', 'season-all'],
    stats: { pickCount: 0, rejectCount: 0 },
    createdAt: FIXED_TIMESTAMP,
  },
  {
    id: 'demo-w31',
    name: '烤羊排',
    tags: ['cuisine-western', 'taste-salty', 'taste-fragrant', 'taste-tender', 'type-hot', 'price-luxury', 'time-slow', 'period-dinner', 'temp-hot', 'season-all'],
    stats: { pickCount: 0, rejectCount: 0 },
    createdAt: FIXED_TIMESTAMP,
  },
  {
    id: 'demo-w32',
    name: '红酒牛肉',
    tags: ['cuisine-western', 'taste-heavy', 'taste-umami', 'taste-tender', 'type-hot', 'price-premium', 'time-slow', 'period-dinner', 'temp-hot', 'season-winter'],
    stats: { pickCount: 0, rejectCount: 0 },
    createdAt: FIXED_TIMESTAMP,
  },
  {
    id: 'demo-w33',
    name: '奶油南瓜汤',
    tags: ['cuisine-western', 'taste-sweet', 'taste-soft', 'taste-light', 'type-soup', 'price-moderate', 'time-normal', 'period-lunch', 'period-dinner', 'temp-hot', 'season-autumn'],
    stats: { pickCount: 0, rejectCount: 0 },
    createdAt: FIXED_TIMESTAMP,
  },
  {
    id: 'demo-w34',
    name: '希腊沙拉',
    tags: ['cuisine-western', 'taste-sour', 'taste-fresh', 'taste-salty', 'type-cold', 'price-moderate', 'time-fast', 'period-lunch', 'temp-cold', 'season-summer'],
    stats: { pickCount: 0, rejectCount: 0 },
    createdAt: FIXED_TIMESTAMP,
  },
  {
    id: 'demo-w35',
    name: '蘑菇浓汤',
    tags: ['cuisine-western', 'taste-umami', 'taste-soft', 'taste-light', 'type-soup', 'price-moderate', 'time-normal', 'period-lunch', 'period-dinner', 'temp-hot', 'season-all'],
    stats: { pickCount: 0, rejectCount: 0 },
    createdAt: FIXED_TIMESTAMP,
  },
]
