import { Dish } from '@/types'

const FIXED_TIMESTAMP = 1700000000000

export const DEMO_DISHES: Dish[] = [
  {
    id: 'demo-1',
    name: '宫保鸡丁',
    tags: ['cuisine-sichuan', 'taste-medium-spicy', 'taste-sour-sweet', 'taste-crispy', 'type-hot', 'price-moderate', 'time-normal', 'period-lunch', 'period-dinner', 'temp-hot', 'season-all'],
    stats: { pickCount: 0, rejectCount: 0 },
    createdAt: FIXED_TIMESTAMP,
  },
  {
    id: 'demo-4',
    name: '麻婆豆腐',
    tags: ['cuisine-sichuan', 'taste-mala', 'taste-soft', 'type-hot', 'price-budget', 'time-fast', 'period-lunch', 'temp-hot', 'season-all'],
    stats: { pickCount: 0, rejectCount: 0 },
    createdAt: FIXED_TIMESTAMP,
  },
  {
    id: 'demo-8',
    name: '酸辣粉',
    tags: ['cuisine-sichuan', 'taste-mala', 'taste-sour', 'taste-slurpy', 'type-noodles', 'price-budget', 'time-fast', 'period-lunch', 'period-snack', 'temp-hot', 'season-all'],
    stats: { pickCount: 0, rejectCount: 0 },
    createdAt: FIXED_TIMESTAMP,
  },
  {
    id: 'demo-11',
    name: '麻辣香锅',
    tags: ['cuisine-sichuan', 'taste-mala', 'taste-heavy', 'taste-fragrant', 'type-hot', 'price-premium', 'time-slow', 'period-dinner', 'temp-hot', 'season-winter'],
    stats: { pickCount: 0, rejectCount: 0 },
    createdAt: FIXED_TIMESTAMP,
  },
  {
    id: 'demo-13',
    name: '水煮鱼',
    tags: ['cuisine-sichuan', 'taste-extra-spicy', 'taste-heavy', 'taste-umami', 'type-hot', 'price-premium', 'time-slow', 'period-dinner', 'temp-hot', 'season-winter'],
    stats: { pickCount: 0, rejectCount: 0 },
    createdAt: FIXED_TIMESTAMP,
  },
  {
    id: 'demo-14',
    name: '回锅肉',
    tags: ['cuisine-sichuan', 'taste-medium-spicy', 'taste-salty', 'taste-fragrant', 'type-hot', 'price-moderate', 'time-normal', 'period-lunch', 'period-dinner', 'temp-hot', 'season-all'],
    stats: { pickCount: 0, rejectCount: 0 },
    createdAt: FIXED_TIMESTAMP,
  },
  {
    id: 'demo-21',
    name: '鱼香肉丝',
    tags: ['cuisine-sichuan', 'taste-medium-spicy', 'taste-sour-sweet', 'taste-umami', 'type-hot', 'price-moderate', 'time-normal', 'period-lunch', 'temp-hot', 'season-all'],
    stats: { pickCount: 0, rejectCount: 0 },
    createdAt: FIXED_TIMESTAMP,
  },
  {
    id: 'demo-41',
    name: '口水鸡',
    tags: ['cuisine-sichuan', 'taste-mala', 'taste-cold-dish', 'type-cold', 'price-moderate', 'time-fast', 'period-lunch', 'period-dinner', 'temp-cold', 'season-summer'],
    stats: { pickCount: 0, rejectCount: 0 },
    createdAt: FIXED_TIMESTAMP,
  },
  {
    id: 'demo-42',
    name: '夫妻肺片',
    tags: ['cuisine-sichuan', 'taste-mala', 'taste-cold-dish', 'type-cold', 'price-moderate', 'time-fast', 'period-lunch', 'period-dinner', 'temp-cold', 'season-summer'],
    stats: { pickCount: 0, rejectCount: 0 },
    createdAt: FIXED_TIMESTAMP,
  },
  {
    id: 'demo-43',
    name: '担担面',
    tags: ['cuisine-sichuan', 'taste-medium-spicy', 'taste-salty', 'taste-slurpy', 'type-noodles', 'price-budget', 'time-fast', 'period-lunch', 'temp-hot', 'season-all'],
    stats: { pickCount: 0, rejectCount: 0 },
    createdAt: FIXED_TIMESTAMP,
  },
  {
    id: 'demo-44',
    name: '辣子鸡',
    tags: ['cuisine-sichuan', 'taste-extra-spicy', 'taste-crispy', 'taste-fragrant', 'type-hot', 'price-moderate', 'time-normal', 'period-dinner', 'temp-hot', 'season-all'],
    stats: { pickCount: 0, rejectCount: 0 },
    createdAt: FIXED_TIMESTAMP,
  },
  {
    id: 'demo-45',
    name: '毛血旺',
    tags: ['cuisine-sichuan', 'taste-extra-spicy', 'taste-heavy', 'taste-umami', 'type-hot', 'price-premium', 'time-slow', 'period-dinner', 'temp-hot', 'season-winter'],
    stats: { pickCount: 0, rejectCount: 0 },
    createdAt: FIXED_TIMESTAMP,
  },
  
  {
    id: 'demo-3',
    name: '清蒸鲈鱼',
    tags: ['cuisine-cantonese', 'taste-light', 'taste-umami', 'taste-fresh', 'type-hot', 'price-premium', 'time-slow', 'period-dinner', 'temp-hot', 'season-all'],
    stats: { pickCount: 0, rejectCount: 0 },
    createdAt: FIXED_TIMESTAMP,
  },
  {
    id: 'demo-9',
    name: '虾饺',
    tags: ['cuisine-cantonese', 'taste-light', 'taste-umami', 'taste-chewy', 'type-dimsum', 'price-moderate', 'time-normal', 'period-breakfast', 'period-snack', 'temp-hot', 'season-all'],
    stats: { pickCount: 0, rejectCount: 0 },
    createdAt: FIXED_TIMESTAMP,
  },
  {
    id: 'demo-15',
    name: '白切鸡',
    tags: ['cuisine-cantonese', 'taste-light', 'taste-umami', 'taste-tender', 'type-hot', 'price-moderate', 'time-normal', 'period-lunch', 'period-dinner', 'temp-hot', 'season-summer'],
    stats: { pickCount: 0, rejectCount: 0 },
    createdAt: FIXED_TIMESTAMP,
  },
  {
    id: 'demo-16',
    name: '肠粉',
    tags: ['cuisine-cantonese', 'taste-light', 'taste-umami', 'taste-soft', 'type-dimsum', 'price-budget', 'time-fast', 'period-breakfast', 'temp-hot', 'season-all'],
    stats: { pickCount: 0, rejectCount: 0 },
    createdAt: FIXED_TIMESTAMP,
  },
  {
    id: 'demo-46',
    name: '叉烧',
    tags: ['cuisine-cantonese', 'taste-sweet', 'taste-fragrant', 'taste-tender', 'type-hot', 'price-moderate', 'time-normal', 'period-lunch', 'period-dinner', 'temp-hot', 'season-all'],
    stats: { pickCount: 0, rejectCount: 0 },
    createdAt: FIXED_TIMESTAMP,
  },
  {
    id: 'demo-47',
    name: '烧鹅',
    tags: ['cuisine-cantonese', 'taste-salty', 'taste-crispy', 'taste-fragrant', 'type-hot', 'price-premium', 'time-slow', 'period-dinner', 'temp-hot', 'season-all'],
    stats: { pickCount: 0, rejectCount: 0 },
    createdAt: FIXED_TIMESTAMP,
  },
  {
    id: 'demo-48',
    name: '煲仔饭',
    tags: ['cuisine-cantonese', 'taste-salty', 'taste-crispy', 'type-rice', 'price-moderate', 'time-slow', 'period-lunch', 'period-dinner', 'temp-hot', 'season-winter'],
    stats: { pickCount: 0, rejectCount: 0 },
    createdAt: FIXED_TIMESTAMP,
  },
  {
    id: 'demo-49',
    name: '干炒牛河',
    tags: ['cuisine-cantonese', 'taste-salty', 'taste-fragrant', 'taste-chewy', 'type-noodles', 'price-moderate', 'time-normal', 'period-lunch', 'period-dinner', 'temp-hot', 'season-all'],
    stats: { pickCount: 0, rejectCount: 0 },
    createdAt: FIXED_TIMESTAMP,
  },
  {
    id: 'demo-50',
    name: '艇仔粥',
    tags: ['cuisine-cantonese', 'taste-light', 'taste-umami', 'type-soup', 'price-budget', 'time-fast', 'period-breakfast', 'period-snack', 'temp-hot', 'season-winter'],
    stats: { pickCount: 0, rejectCount: 0 },
    createdAt: FIXED_TIMESTAMP,
  },
  {
    id: 'demo-51',
    name: '双皮奶',
    tags: ['cuisine-cantonese', 'taste-sweet', 'taste-soft', 'taste-fresh', 'type-dessert', 'price-budget', 'time-fast', 'period-snack', 'temp-cold', 'season-summer'],
    stats: { pickCount: 0, rejectCount: 0 },
    createdAt: FIXED_TIMESTAMP,
  },
  
  {
    id: 'demo-17',
    name: '剁椒鱼头',
    tags: ['cuisine-hunan', 'taste-extra-spicy', 'taste-umami', 'taste-tender', 'type-hot', 'price-premium', 'time-slow', 'period-dinner', 'temp-hot', 'season-all'],
    stats: { pickCount: 0, rejectCount: 0 },
    createdAt: FIXED_TIMESTAMP,
  },
  {
    id: 'demo-18',
    name: '小炒肉',
    tags: ['cuisine-hunan', 'taste-medium-spicy', 'taste-salty', 'taste-fragrant', 'type-hot', 'price-moderate', 'time-normal', 'period-lunch', 'period-dinner', 'temp-hot', 'season-all'],
    stats: { pickCount: 0, rejectCount: 0 },
    createdAt: FIXED_TIMESTAMP,
  },
  {
    id: 'demo-52',
    name: '口味虾',
    tags: ['cuisine-hunan', 'taste-extra-spicy', 'taste-heavy', 'taste-fragrant', 'type-hot', 'price-premium', 'time-slow', 'period-dinner', 'temp-hot', 'season-summer'],
    stats: { pickCount: 0, rejectCount: 0 },
    createdAt: FIXED_TIMESTAMP,
  },
  {
    id: 'demo-53',
    name: '农家小炒',
    tags: ['cuisine-hunan', 'taste-medium-spicy', 'taste-fresh', 'taste-fragrant', 'type-hot', 'price-budget', 'time-fast', 'period-lunch', 'period-dinner', 'temp-hot', 'season-all'],
    stats: { pickCount: 0, rejectCount: 0 },
    createdAt: FIXED_TIMESTAMP,
  },
  
  {
    id: 'demo-54',
    name: '糖醋鲤鱼',
    tags: ['cuisine-shandong', 'taste-sour-sweet', 'taste-crispy', 'taste-tender', 'type-hot', 'price-premium', 'time-slow', 'period-dinner', 'temp-hot', 'season-all'],
    stats: { pickCount: 0, rejectCount: 0 },
    createdAt: FIXED_TIMESTAMP,
  },
  {
    id: 'demo-55',
    name: '九转大肠',
    tags: ['cuisine-shandong', 'taste-salty', 'taste-sweet', 'taste-chewy', 'type-hot', 'price-premium', 'time-slow', 'period-dinner', 'temp-hot', 'season-all'],
    stats: { pickCount: 0, rejectCount: 0 },
    createdAt: FIXED_TIMESTAMP,
  },
  {
    id: 'demo-56',
    name: '葱烧海参',
    tags: ['cuisine-shandong', 'taste-light', 'taste-umami', 'taste-soft', 'type-hot', 'price-luxury', 'time-slow', 'period-dinner', 'temp-hot', 'season-all'],
    stats: { pickCount: 0, rejectCount: 0 },
    createdAt: FIXED_TIMESTAMP,
  },
  
  {
    id: 'demo-57',
    name: '松鼠鳜鱼',
    tags: ['cuisine-jiangsu', 'taste-sour-sweet', 'taste-crispy', 'taste-tender', 'type-hot', 'price-luxury', 'time-slow', 'period-dinner', 'temp-hot', 'season-all'],
    stats: { pickCount: 0, rejectCount: 0 },
    createdAt: FIXED_TIMESTAMP,
  },
  {
    id: 'demo-58',
    name: '红烧狮子头',
    tags: ['cuisine-jiangsu', 'taste-salty', 'taste-tender', 'taste-heavy', 'type-hot', 'price-premium', 'time-slow', 'period-dinner', 'temp-hot', 'season-winter'],
    stats: { pickCount: 0, rejectCount: 0 },
    createdAt: FIXED_TIMESTAMP,
  },
  {
    id: 'demo-59',
    name: '大煮干丝',
    tags: ['cuisine-jiangsu', 'taste-light', 'taste-umami', 'taste-soft', 'type-hot', 'price-moderate', 'time-normal', 'period-lunch', 'temp-hot', 'season-all'],
    stats: { pickCount: 0, rejectCount: 0 },
    createdAt: FIXED_TIMESTAMP,
  },
  
  {
    id: 'demo-60',
    name: '东坡肉',
    tags: ['cuisine-zhejiang', 'taste-sweet', 'taste-salty', 'taste-tender', 'taste-heavy', 'type-hot', 'price-premium', 'time-slow', 'period-dinner', 'temp-hot', 'season-all'],
    stats: { pickCount: 0, rejectCount: 0 },
    createdAt: FIXED_TIMESTAMP,
  },
  {
    id: 'demo-61',
    name: '西湖醋鱼',
    tags: ['cuisine-zhejiang', 'taste-sour-sweet', 'taste-tender', 'taste-umami', 'taste-fresh', 'type-hot', 'price-premium', 'time-slow', 'period-dinner', 'temp-hot', 'season-all'],
    stats: { pickCount: 0, rejectCount: 0 },
    createdAt: FIXED_TIMESTAMP,
  },
  {
    id: 'demo-62',
    name: '龙井虾仁',
    tags: ['cuisine-zhejiang', 'taste-light', 'taste-umami', 'taste-fresh', 'type-hot', 'price-premium', 'time-normal', 'period-dinner', 'temp-hot', 'season-spring'],
    stats: { pickCount: 0, rejectCount: 0 },
    createdAt: FIXED_TIMESTAMP,
  },
  
  {
    id: 'demo-63',
    name: '臭鳜鱼',
    tags: ['cuisine-anhui', 'taste-salty', 'taste-umami', 'taste-tender', 'type-hot', 'price-premium', 'time-slow', 'period-dinner', 'temp-hot', 'season-all'],
    stats: { pickCount: 0, rejectCount: 0 },
    createdAt: FIXED_TIMESTAMP,
  },
  {
    id: 'demo-64',
    name: '毛豆腐',
    tags: ['cuisine-anhui', 'taste-salty', 'taste-soft', 'taste-fragrant', 'type-hot', 'price-moderate', 'time-normal', 'period-snack', 'period-dinner', 'temp-hot', 'season-all'],
    stats: { pickCount: 0, rejectCount: 0 },
    createdAt: FIXED_TIMESTAMP,
  },
  
  {
    id: 'demo-2',
    name: '糖醋里脊',
    tags: ['cuisine-chinese', 'taste-sour-sweet', 'taste-crispy', 'taste-tender', 'type-hot', 'price-moderate', 'time-normal', 'period-lunch', 'period-dinner', 'temp-hot', 'season-all'],
    stats: { pickCount: 0, rejectCount: 0 },
    createdAt: FIXED_TIMESTAMP,
  },
  {
    id: 'demo-10',
    name: '黄焖鸡米饭',
    tags: ['cuisine-chinese', 'taste-salty', 'taste-tender', 'taste-heavy', 'type-rice', 'price-moderate', 'time-normal', 'period-lunch', 'temp-hot', 'season-all'],
    stats: { pickCount: 0, rejectCount: 0 },
    createdAt: FIXED_TIMESTAMP,
  },
  {
    id: 'demo-19',
    name: '红烧肉',
    tags: ['cuisine-chinese', 'taste-salty', 'taste-sweet', 'taste-tender', 'taste-heavy', 'type-hot', 'price-moderate', 'time-slow', 'period-dinner', 'temp-hot', 'season-winter'],
    stats: { pickCount: 0, rejectCount: 0 },
    createdAt: FIXED_TIMESTAMP,
  },
  {
    id: 'demo-20',
    name: '番茄炒蛋',
    tags: ['cuisine-chinese', 'taste-sour-sweet', 'taste-light', 'taste-soft', 'type-hot', 'price-budget', 'time-fast', 'period-lunch', 'period-dinner', 'temp-hot', 'season-all'],
    stats: { pickCount: 0, rejectCount: 0 },
    createdAt: FIXED_TIMESTAMP,
  },
  {
    id: 'demo-65',
    name: '青椒肉丝',
    tags: ['cuisine-chinese', 'taste-light', 'taste-fresh', 'taste-tender', 'type-hot', 'price-budget', 'time-fast', 'period-lunch', 'period-dinner', 'temp-hot', 'season-all'],
    stats: { pickCount: 0, rejectCount: 0 },
    createdAt: FIXED_TIMESTAMP,
  },
  {
    id: 'demo-66',
    name: '土豆丝',
    tags: ['cuisine-chinese', 'taste-light', 'taste-crispy', 'type-hot', 'price-budget', 'time-fast', 'period-lunch', 'temp-hot', 'season-all'],
    stats: { pickCount: 0, rejectCount: 0 },
    createdAt: FIXED_TIMESTAMP,
  },
  {
    id: 'demo-67',
    name: '地三鲜',
    tags: ['cuisine-chinese', 'taste-salty', 'taste-soft', 'type-hot', 'price-budget', 'time-normal', 'period-lunch', 'temp-hot', 'season-all'],
    stats: { pickCount: 0, rejectCount: 0 },
    createdAt: FIXED_TIMESTAMP,
  },
  {
    id: 'demo-68',
    name: '木须肉',
    tags: ['cuisine-chinese', 'taste-light', 'taste-umami', 'taste-tender', 'type-hot', 'price-budget', 'time-fast', 'period-lunch', 'period-dinner', 'temp-hot', 'season-all'],
    stats: { pickCount: 0, rejectCount: 0 },
    createdAt: FIXED_TIMESTAMP,
  },
  {
    id: 'demo-69',
    name: '酸菜鱼',
    tags: ['cuisine-chinese', 'taste-sour', 'taste-light', 'taste-tender', 'type-hot', 'price-moderate', 'time-normal', 'period-lunch', 'period-dinner', 'temp-hot', 'season-winter'],
    stats: { pickCount: 0, rejectCount: 0 },
    createdAt: FIXED_TIMESTAMP,
  },
  {
    id: 'demo-70',
    name: '京酱肉丝',
    tags: ['cuisine-chinese', 'taste-salty', 'taste-sweet', 'taste-soft', 'type-hot', 'price-moderate', 'time-normal', 'period-lunch', 'temp-hot', 'season-all'],
    stats: { pickCount: 0, rejectCount: 0 },
    createdAt: FIXED_TIMESTAMP,
  },
  
  {
    id: 'demo-5',
    name: '寿司拼盘',
    tags: ['cuisine-japanese', 'taste-light', 'taste-umami', 'taste-fresh', 'type-cold', 'price-premium', 'time-normal', 'period-lunch', 'temp-cold', 'season-all'],
    stats: { pickCount: 0, rejectCount: 0 },
    createdAt: FIXED_TIMESTAMP,
  },
  {
    id: 'demo-22',
    name: '拉面',
    tags: ['cuisine-japanese', 'taste-light', 'taste-umami', 'taste-slurpy', 'type-noodles', 'price-moderate', 'time-normal', 'period-lunch', 'temp-hot', 'season-all'],
    stats: { pickCount: 0, rejectCount: 0 },
    createdAt: FIXED_TIMESTAMP,
  },
  {
    id: 'demo-23',
    name: '鳗鱼饭',
    tags: ['cuisine-japanese', 'taste-sweet', 'taste-umami', 'taste-tender', 'type-rice', 'price-premium', 'time-slow', 'period-lunch', 'period-dinner', 'temp-hot', 'season-all'],
    stats: { pickCount: 0, rejectCount: 0 },
    createdAt: FIXED_TIMESTAMP,
  },
  {
    id: 'demo-24',
    name: '天妇罗',
    tags: ['cuisine-japanese', 'taste-light', 'taste-crispy', 'type-hot', 'price-premium', 'time-normal', 'period-lunch', 'period-dinner', 'temp-hot', 'season-all'],
    stats: { pickCount: 0, rejectCount: 0 },
    createdAt: FIXED_TIMESTAMP,
  },
  {
    id: 'demo-71',
    name: '刺身',
    tags: ['cuisine-japanese', 'taste-light', 'taste-umami', 'taste-fresh', 'type-cold', 'price-premium', 'time-fast', 'period-lunch', 'period-dinner', 'temp-cold', 'season-all'],
    stats: { pickCount: 0, rejectCount: 0 },
    createdAt: FIXED_TIMESTAMP,
  },
  {
    id: 'demo-72',
    name: '味噌汤',
    tags: ['cuisine-japanese', 'taste-light', 'taste-umami', 'type-soup', 'price-budget', 'time-fast', 'period-breakfast', 'period-lunch', 'temp-hot', 'season-all'],
    stats: { pickCount: 0, rejectCount: 0 },
    createdAt: FIXED_TIMESTAMP,
  },
  {
    id: 'demo-73',
    name: '猪排饭',
    tags: ['cuisine-japanese', 'taste-salty', 'taste-crispy', 'taste-tender', 'type-rice', 'price-moderate', 'time-normal', 'period-lunch', 'period-dinner', 'temp-hot', 'season-all'],
    stats: { pickCount: 0, rejectCount: 0 },
    createdAt: FIXED_TIMESTAMP,
  },
  {
    id: 'demo-74',
    name: '乌冬面',
    tags: ['cuisine-japanese', 'taste-light', 'taste-umami', 'taste-chewy', 'type-noodles', 'price-moderate', 'time-normal', 'period-lunch', 'temp-hot', 'season-all'],
    stats: { pickCount: 0, rejectCount: 0 },
    createdAt: FIXED_TIMESTAMP,
  },
  
  {
    id: 'demo-6',
    name: '石锅拌饭',
    tags: ['cuisine-korean', 'taste-medium-spicy', 'taste-umami', 'taste-crispy', 'type-rice', 'price-moderate', 'time-normal', 'period-lunch', 'temp-hot', 'season-all'],
    stats: { pickCount: 0, rejectCount: 0 },
    createdAt: FIXED_TIMESTAMP,
  },
  {
    id: 'demo-25',
    name: '部队锅',
    tags: ['cuisine-korean', 'taste-medium-spicy', 'taste-heavy', 'taste-umami', 'type-hot', 'price-premium', 'time-slow', 'period-dinner', 'temp-hot', 'season-winter'],
    stats: { pickCount: 0, rejectCount: 0 },
    createdAt: FIXED_TIMESTAMP,
  },
  {
    id: 'demo-26',
    name: '炸鸡',
    tags: ['cuisine-korean', 'taste-crispy', 'taste-salty', 'type-snack', 'price-moderate', 'time-normal', 'period-dinner', 'period-snack', 'temp-hot', 'season-all'],
    stats: { pickCount: 0, rejectCount: 0 },
    createdAt: FIXED_TIMESTAMP,
  },
  {
    id: 'demo-75',
    name: '泡菜汤',
    tags: ['cuisine-korean', 'taste-medium-spicy', 'taste-sour', 'taste-umami', 'type-soup', 'price-moderate', 'time-normal', 'period-lunch', 'period-dinner', 'temp-hot', 'season-winter'],
    stats: { pickCount: 0, rejectCount: 0 },
    createdAt: FIXED_TIMESTAMP,
  },
  {
    id: 'demo-76',
    name: '冷面',
    tags: ['cuisine-korean', 'taste-sour', 'taste-light', 'taste-slurpy', 'type-noodles', 'price-moderate', 'time-fast', 'period-lunch', 'temp-cold', 'season-summer'],
    stats: { pickCount: 0, rejectCount: 0 },
    createdAt: FIXED_TIMESTAMP,
  },
  {
    id: 'demo-77',
    name: '烤肉',
    tags: ['cuisine-korean', 'taste-salty', 'taste-fragrant', 'taste-tender', 'type-hot', 'price-premium', 'time-slow', 'period-dinner', 'temp-hot', 'season-all'],
    stats: { pickCount: 0, rejectCount: 0 },
    createdAt: FIXED_TIMESTAMP,
  },
  {
    id: 'demo-78',
    name: '年糕',
    tags: ['cuisine-korean', 'taste-medium-spicy', 'taste-chewy', 'taste-sweet', 'type-snack', 'price-budget', 'time-fast', 'period-snack', 'temp-hot', 'season-all'],
    stats: { pickCount: 0, rejectCount: 0 },
    createdAt: FIXED_TIMESTAMP,
  },
  
  {
    id: 'demo-7',
    name: '意大利面',
    tags: ['cuisine-western', 'taste-heavy', 'taste-umami', 'taste-chewy', 'type-staple', 'price-moderate', 'time-normal', 'period-lunch', 'period-dinner', 'temp-hot', 'season-all'],
    stats: { pickCount: 0, rejectCount: 0 },
    createdAt: FIXED_TIMESTAMP,
  },
  {
    id: 'demo-12',
    name: '沙拉',
    tags: ['cuisine-western', 'taste-light', 'taste-fresh', 'type-cold', 'price-moderate', 'time-fast', 'period-lunch', 'temp-cold', 'season-summer'],
    stats: { pickCount: 0, rejectCount: 0 },
    createdAt: FIXED_TIMESTAMP,
  },
  {
    id: 'demo-27',
    name: '牛排',
    tags: ['cuisine-western', 'taste-heavy', 'taste-umami', 'taste-tender', 'type-hot', 'price-luxury', 'time-slow', 'period-dinner', 'temp-hot', 'season-all'],
    stats: { pickCount: 0, rejectCount: 0 },
    createdAt: FIXED_TIMESTAMP,
  },
  {
    id: 'demo-28',
    name: '三明治',
    tags: ['cuisine-western', 'taste-light', 'taste-fresh', 'type-snack', 'price-budget', 'time-fast', 'period-breakfast', 'period-lunch', 'temp-room', 'season-all'],
    stats: { pickCount: 0, rejectCount: 0 },
    createdAt: FIXED_TIMESTAMP,
  },
  {
    id: 'demo-29',
    name: '披萨',
    tags: ['cuisine-western', 'taste-heavy', 'taste-crispy', 'taste-umami', 'type-staple', 'price-premium', 'time-slow', 'period-dinner', 'temp-hot', 'season-all'],
    stats: { pickCount: 0, rejectCount: 0 },
    createdAt: FIXED_TIMESTAMP,
  },
  {
    id: 'demo-79',
    name: '汉堡',
    tags: ['cuisine-western', 'taste-heavy', 'taste-crispy', 'type-snack', 'price-moderate', 'time-fast', 'period-lunch', 'temp-hot', 'season-all'],
    stats: { pickCount: 0, rejectCount: 0 },
    createdAt: FIXED_TIMESTAMP,
  },
  {
    id: 'demo-80',
    name: '焗饭',
    tags: ['cuisine-western', 'taste-heavy', 'taste-crispy', 'taste-umami', 'type-rice', 'price-moderate', 'time-normal', 'period-lunch', 'period-dinner', 'temp-hot', 'season-all'],
    stats: { pickCount: 0, rejectCount: 0 },
    createdAt: FIXED_TIMESTAMP,
  },
  {
    id: 'demo-81',
    name: '法式洋葱汤',
    tags: ['cuisine-western', 'taste-salty', 'taste-umami', 'taste-soft', 'type-soup', 'price-moderate', 'time-normal', 'period-dinner', 'temp-hot', 'season-winter'],
    stats: { pickCount: 0, rejectCount: 0 },
    createdAt: FIXED_TIMESTAMP,
  },
  
  {
    id: 'demo-30',
    name: '汉堡套餐',
    tags: ['cuisine-fastfood', 'taste-heavy', 'taste-crispy', 'taste-salty', 'type-staple', 'price-moderate', 'time-fast', 'period-lunch', 'temp-hot', 'season-all'],
    stats: { pickCount: 0, rejectCount: 0 },
    createdAt: FIXED_TIMESTAMP,
  },
  {
    id: 'demo-31',
    name: '麻辣烫',
    tags: ['cuisine-fastfood', 'taste-mala', 'taste-heavy', 'type-hot', 'price-budget', 'time-fast', 'period-lunch', 'period-dinner', 'temp-hot', 'season-all'],
    stats: { pickCount: 0, rejectCount: 0 },
    createdAt: FIXED_TIMESTAMP,
  },
  {
    id: 'demo-32',
    name: '盖浇饭',
    tags: ['cuisine-fastfood', 'taste-salty', 'taste-heavy', 'taste-umami', 'type-rice', 'price-budget', 'time-fast', 'period-lunch', 'period-dinner', 'temp-hot', 'season-all'],
    stats: { pickCount: 0, rejectCount: 0 },
    createdAt: FIXED_TIMESTAMP,
  },
  {
    id: 'demo-82',
    name: '炸鸡排',
    tags: ['cuisine-fastfood', 'taste-crispy', 'taste-salty', 'type-snack', 'price-budget', 'time-fast', 'period-snack', 'temp-hot', 'season-all'],
    stats: { pickCount: 0, rejectCount: 0 },
    createdAt: FIXED_TIMESTAMP,
  },
  {
    id: 'demo-83',
    name: '煎饼果子',
    tags: ['cuisine-fastfood', 'taste-salty', 'taste-crispy', 'type-snack', 'price-budget', 'time-fast', 'period-breakfast', 'temp-hot', 'season-all'],
    stats: { pickCount: 0, rejectCount: 0 },
    createdAt: FIXED_TIMESTAMP,
  },
  {
    id: 'demo-84',
    name: '肉夹馍',
    tags: ['cuisine-fastfood', 'taste-salty', 'taste-fragrant', 'type-snack', 'price-budget', 'time-fast', 'period-lunch', 'period-snack', 'temp-hot', 'season-all'],
    stats: { pickCount: 0, rejectCount: 0 },
    createdAt: FIXED_TIMESTAMP,
  },
  {
    id: 'demo-85',
    name: '凉皮',
    tags: ['cuisine-fastfood', 'taste-sour', 'taste-light', 'taste-slurpy', 'type-cold', 'price-budget', 'time-fast', 'period-lunch', 'temp-cold', 'season-summer'],
    stats: { pickCount: 0, rejectCount: 0 },
    createdAt: FIXED_TIMESTAMP,
  },
  {
    id: 'demo-86',
    name: '螺蛳粉',
    tags: ['cuisine-fastfood', 'taste-sour', 'taste-medium-spicy', 'taste-slurpy', 'type-noodles', 'price-budget', 'time-fast', 'period-lunch', 'period-dinner', 'temp-hot', 'season-all'],
    stats: { pickCount: 0, rejectCount: 0 },
    createdAt: FIXED_TIMESTAMP,
  },
  
  {
    id: 'demo-33',
    name: '重庆火锅',
    tags: ['cuisine-hotpot', 'taste-mala', 'taste-extra-spicy', 'taste-heavy', 'price-premium', 'time-slow', 'period-dinner', 'temp-hot', 'season-winter'],
    stats: { pickCount: 0, rejectCount: 0 },
    createdAt: FIXED_TIMESTAMP,
  },
  {
    id: 'demo-34',
    name: '潮汕牛肉火锅',
    tags: ['cuisine-hotpot', 'taste-light', 'taste-umami', 'taste-fresh', 'price-luxury', 'time-slow', 'period-dinner', 'temp-hot', 'season-winter'],
    stats: { pickCount: 0, rejectCount: 0 },
    createdAt: FIXED_TIMESTAMP,
  },
  {
    id: 'demo-87',
    name: '鸳鸯锅',
    tags: ['cuisine-hotpot', 'taste-mala', 'taste-light', 'taste-heavy', 'taste-umami', 'type-hot', 'price-premium', 'time-slow', 'period-dinner', 'temp-hot', 'season-winter'],
    stats: { pickCount: 0, rejectCount: 0 },
    createdAt: FIXED_TIMESTAMP,
  },
  {
    id: 'demo-88',
    name: '菌菇火锅',
    tags: ['cuisine-hotpot', 'taste-light', 'taste-umami', 'taste-fresh', 'price-premium', 'time-slow', 'period-dinner', 'temp-hot', 'season-winter'],
    stats: { pickCount: 0, rejectCount: 0 },
    createdAt: FIXED_TIMESTAMP,
  },
  
  {
    id: 'demo-35',
    name: '羊肉串',
    tags: ['cuisine-bbq', 'taste-fragrant', 'taste-medium-spicy', 'taste-crispy', 'type-snack', 'price-moderate', 'time-normal', 'period-dinner', 'period-snack', 'temp-hot', 'season-all'],
    stats: { pickCount: 0, rejectCount: 0 },
    createdAt: FIXED_TIMESTAMP,
  },
  {
    id: 'demo-36',
    name: '烤鱼',
    tags: ['cuisine-bbq', 'taste-fragrant', 'taste-medium-spicy', 'taste-tender', 'type-hot', 'price-premium', 'time-slow', 'period-dinner', 'temp-hot', 'season-all'],
    stats: { pickCount: 0, rejectCount: 0 },
    createdAt: FIXED_TIMESTAMP,
  },
  {
    id: 'demo-89',
    name: '烤翅',
    tags: ['cuisine-bbq', 'taste-medium-spicy', 'taste-fragrant', 'taste-crispy', 'type-snack', 'price-moderate', 'time-normal', 'period-dinner', 'period-snack', 'temp-hot', 'season-all'],
    stats: { pickCount: 0, rejectCount: 0 },
    createdAt: FIXED_TIMESTAMP,
  },
  {
    id: 'demo-90',
    name: '生蚝',
    tags: ['cuisine-bbq', 'taste-umami', 'taste-fresh', 'type-snack', 'price-premium', 'time-normal', 'period-dinner', 'period-snack', 'temp-hot', 'season-summer'],
    stats: { pickCount: 0, rejectCount: 0 },
    createdAt: FIXED_TIMESTAMP,
  },
  {
    id: 'demo-91',
    name: '烤茄子',
    tags: ['cuisine-bbq', 'taste-soft', 'taste-umami', 'taste-fragrant', 'type-snack', 'price-budget', 'time-fast', 'period-dinner', 'temp-hot', 'season-summer'],
    stats: { pickCount: 0, rejectCount: 0 },
    createdAt: FIXED_TIMESTAMP,
  },
  
  {
    id: 'demo-37',
    name: '冬阴功汤',
    tags: ['cuisine-southeast', 'taste-sour', 'taste-medium-spicy', 'taste-umami', 'type-soup', 'price-moderate', 'time-normal', 'period-lunch', 'period-dinner', 'temp-hot', 'season-all'],
    stats: { pickCount: 0, rejectCount: 0 },
    createdAt: FIXED_TIMESTAMP,
  },
  {
    id: 'demo-38',
    name: '泰式炒饭',
    tags: ['cuisine-southeast', 'taste-medium-spicy', 'taste-umami', 'type-rice', 'price-moderate', 'time-normal', 'period-lunch', 'temp-hot', 'season-all'],
    stats: { pickCount: 0, rejectCount: 0 },
    createdAt: FIXED_TIMESTAMP,
  },
  {
    id: 'demo-92',
    name: '咖喱鸡',
    tags: ['cuisine-southeast', 'taste-medium-spicy', 'taste-heavy', 'taste-umami', 'type-hot', 'price-moderate', 'time-normal', 'period-lunch', 'period-dinner', 'temp-hot', 'season-all'],
    stats: { pickCount: 0, rejectCount: 0 },
    createdAt: FIXED_TIMESTAMP,
  },
  {
    id: 'demo-93',
    name: '越南粉',
    tags: ['cuisine-southeast', 'taste-light', 'taste-umami', 'taste-fresh', 'taste-slurpy', 'type-noodles', 'price-moderate', 'time-normal', 'period-lunch', 'temp-hot', 'season-all'],
    stats: { pickCount: 0, rejectCount: 0 },
    createdAt: FIXED_TIMESTAMP,
  },
  {
    id: 'demo-94',
    name: '芒果糯米饭',
    tags: ['cuisine-southeast', 'taste-sweet', 'taste-chewy', 'type-dessert', 'price-moderate', 'time-fast', 'period-snack', 'temp-room', 'season-summer'],
    stats: { pickCount: 0, rejectCount: 0 },
    createdAt: FIXED_TIMESTAMP,
  },
  
  {
    id: 'demo-39',
    name: '麻辣小龙虾',
    tags: ['cuisine-crayfish', 'taste-mala', 'taste-extra-spicy', 'taste-heavy', 'type-hot', 'price-premium', 'time-slow', 'period-dinner', 'temp-hot', 'season-summer'],
    stats: { pickCount: 0, rejectCount: 0 },
    createdAt: FIXED_TIMESTAMP,
  },
  {
    id: 'demo-40',
    name: '蒜蓉小龙虾',
    tags: ['cuisine-crayfish', 'taste-fragrant', 'taste-heavy', 'taste-umami', 'type-hot', 'price-premium', 'time-slow', 'period-dinner', 'temp-hot', 'season-summer'],
    stats: { pickCount: 0, rejectCount: 0 },
    createdAt: FIXED_TIMESTAMP,
  },
  {
    id: 'demo-95',
    name: '十三香小龙虾',
    tags: ['cuisine-crayfish', 'taste-fragrant', 'taste-medium-spicy', 'taste-heavy', 'type-hot', 'price-premium', 'time-slow', 'period-dinner', 'temp-hot', 'season-summer'],
    stats: { pickCount: 0, rejectCount: 0 },
    createdAt: FIXED_TIMESTAMP,
  },
  
  {
    id: 'demo-96',
    name: '珍珠奶茶',
    tags: ['cuisine-dessert', 'taste-sweet', 'taste-chewy', 'type-drink', 'price-budget', 'time-fast', 'period-snack', 'temp-cold', 'season-summer'],
    stats: { pickCount: 0, rejectCount: 0 },
    createdAt: FIXED_TIMESTAMP,
  },
  {
    id: 'demo-97',
    name: '杨枝甘露',
    tags: ['cuisine-dessert', 'taste-sweet', 'taste-fresh', 'type-dessert', 'price-moderate', 'time-fast', 'period-snack', 'temp-cold', 'season-summer'],
    stats: { pickCount: 0, rejectCount: 0 },
    createdAt: FIXED_TIMESTAMP,
  },
  {
    id: 'demo-98',
    name: '冰粉',
    tags: ['cuisine-dessert', 'taste-sweet', 'taste-soft', 'type-dessert', 'price-budget', 'time-fast', 'period-snack', 'temp-cold', 'season-summer'],
    stats: { pickCount: 0, rejectCount: 0 },
    createdAt: FIXED_TIMESTAMP,
  },
  {
    id: 'demo-99',
    name: '红豆汤',
    tags: ['cuisine-dessert', 'taste-sweet', 'taste-soft', 'type-dessert', 'price-budget', 'time-fast', 'period-snack', 'temp-hot', 'season-winter'],
    stats: { pickCount: 0, rejectCount: 0 },
    createdAt: FIXED_TIMESTAMP,
  },
  {
    id: 'demo-100',
    name: '绿豆汤',
    tags: ['cuisine-dessert', 'taste-sweet', 'taste-light', 'type-dessert', 'price-budget', 'time-fast', 'period-snack', 'temp-cold', 'season-summer'],
    stats: { pickCount: 0, rejectCount: 0 },
    createdAt: FIXED_TIMESTAMP,
  },
]
